### ISSUE TITLE
Presentation of orthographically standardized form of search string

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#100]
This means presenting "somewhere" (potentially apparent by default but as a pop-up or button) the strictly normative form corresponding to the spell-relaxed linguistic analysis of the search string, e.g.

- [x] nikiwapamaw -> nikî-wâpamâw
- [x] nipa -> nipâ (the preverb _nipâ-_ is mispelled in MD, lacking vowel length and the hyphen)
- [x] nipaw -> nipâw
- [x] ninipan -> ninipân
- [x] nikimamiyonipan -> 'nikî-ma-miyo-nipân
- [x] enipat -> ê-nipât

The standardization should follow the selection of content representation, i.e. either flavor of SRO or Cree syllabics.

Note that there may be two or more possible linguistic analyses for the same search string, e.g.

- [x] e-nipayan
-> ê-nipâyân <- `PV/e+nipâw+V+AI+Cnj+Prs+1Sg`
-> ê-nipâyan <- `PV/e+nipâw+V+AI+Cnj+Prs+2Sg`

Or:

(`echo nipihk | hfst-lookup -q ~/giella/langs/crk/src/analyser-gt-desc.hfst | cut -f2`)

```
nipihk
-> nipiy+N+I+Loc
-> nîpiy+N+I+Loc
-> nipiw+V+AI+Cnj+Prs+X
-> nîpin+V+II+Cnj+Prs+3Sg
-> nipiw+V+AI+Imp+Imm+2Pl
```
(`echo nipihk | hfst-lookup -q ~/giella/langs/crk/src/analyser-gt-desc.hfst | cut -f2 | hfst-lookup -q ~/giella/langs/crk/src/generator-gt-norm.hfst`)

nipihk ->
- [x] nipîhk (`nipiy+N+I+Loc: 0.000000`)
- [x] nîpîhk (`nîpiy+N+I+Loc: 0.000000`)

- [x] nipihk (`nipiw+V+AI+Cnj+Prs+X: 0.000000`)
- [x] nipiniwahk (`nipiw+V+AI+Cnj+Prs+X: 0.000000`)
- [x] nipinâniwahk (`nipiw+V+AI+Cnj+Prs+X: 0.000000`)

- [x] nîpihk (`nîpin+V+II+Cnj+Prs+3Sg: 0.000000`)

- [x] nipik (`nipiw+V+AI+Imp+Imm+2Pl: 0.000000`)

Note that sometimes there might be two or three alternative normative forms corresponding to the same linguistic analysis, e.g. (from above):

nipihk ->
- [x] [nipihk, nipiniwahk, nipinâniwahk] (`nipiw+V+AI+Cnj+Prs+X` )

**Comment by aarppe** [comment]
Resolving this matches the following user story:

"As a Cree language learner, I want the search results to show me which word form matched (e.g., if I search _nipa_,  the result will say 'matched _nipâ_ - a form of _nipâw_"

**Comment by Madoshakalaka** [comment]
update: I'm on this

**Comment by Madoshakalaka** [comment]
This is implemented and show show on sapir in minutes. Worth noting

when the user query matches a non-lemma form, the following search result is currently **not** followed by an extra entry of lemma. 
> \<non-lemma wordform\>
> form of \<lemma\>
>     English definition

the extra entry of lemma is bettered described in #201 and #209, and will get implemented later.

**Comment by aarppe** [comment]
The general implementation is fine, but the standardization of the search strings still needs some work. In this, we still need to check that the multiple test cases enumerated above all work done properly. Vowel length marking (with circumflexes is done properly), but ignoring hyphens is not. For AEW compliance, _enipat_ -> _ênipât_ is half-way and not according to SRO, we need to get _ê-nipât_.

**Comment by Madoshakalaka** [comment]
I'm looking into the enipat case and the general problem

**Comment by Madoshakalaka** [comment]
@aarppe I found the problem. Part of the workflow is to use fst to analyze user query and use normative generator to generate standardized forms.

The problem in the _enipat_'s case is that the analysis have an Err/Orth tag in it, and the normative generator picks it up.

```
$ hfst-optimized-lookup CreeDictionary/res/fst/crk-descriptive-analyzer.hfstol
enipat
enipat  PV/e+nipâw+V+AI+Cnj+Prs+3Sg+Err/Orth
```
Notice if Err/Orth is stripped, we get the truly normatized form with the dash.
```
$ hfst-optimized-lookup CreeDictionary/res/fst/crk-normative-generator.hfstol

Loading .env environment variables…
PV/e+nipâw+V+AI+Cnj+Prs+3Sg+Err/Orth
PV/e+nipâw+V+AI+Cnj+Prs+3Sg+Err/Orth    ênipât

PV/e+nipâw+V+AI+Cnj+Prs+3Sg
PV/e+nipâw+V+AI+Cnj+Prs+3Sg     ê-nipât
```

@eddieantonio btw is picking up Err/Orth this a feature of our generative fst? It feels way too intelligent.

**Comment by Madoshakalaka** [comment]
I'll fix this problem by stripping Err/Orth in the process.

**Comment by Madoshakalaka** [comment]
@aarppe Can you check if anything else obvious needs to be changed?

**Comment by aarppe** [comment]
The idea with the `+Err/Orth` tag is to allow us to include in our FST known misspellings of frequent word forms, like _mân_ or _man_ for _mâna_, or know non-standard conventions (leaving the hyphen out) and allow the descriptive FST to analyze those but also say that the form is not spelled in the standard way - the normative FST would not recognize those forms at all. So then, when you remove the +Err/Orth tag, you can output the standardized form, as you now do.

I'll go over the above example/test cases separately - we might want to include at least some of them as regression test cases for itwêwina build as well.

**Comment by eddieantonio** [comment]
@Madoshakalaka as @aarppe said, the descriptive analyzer has `+Err/Orth` tags hard-coded in a lot of places (known misspellings).

Could you please add some regression tests for searching for, e.g., enipat?

**Comment by Madoshakalaka** [comment]
sure I will add some regression tests

**Comment by aarppe** [comment]
Currently duplicate of #209.

**Comment by aarppe** [comment]
Duplicate of #209.
