### ISSUE TITLE
Presentation of Plains Cree declination/conjugation classes (i.e. NA[D]-[1-5], VTA-[1-5])

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#101]
Instead of the linguistic codes such as NA-1, NA-2, VTA-1, VTA-2, etc., we could present example/model verbs and nouns to indicate how the noun or verb is inflected.

Ideally, one would use such example verbs which are used in instruction - on the university level, we could base these on Arok's paradigms.

These could implemented by selecting examples for each (which could e.g. be gleaned from Arok's model paradigms). For instance, using Arok's older inflectional/conjugational classes, these could be:

[note that these inflectional subtypes have changed - see comment later below]
VII-v: mihkwâw
VII-n: miywasin
VAI-v: nipâw
VAI-n: pimisin
VTI-1: nâtam
VTI-2: kîsihtâw
VTI-3: mîciw
VTA-1: wîcihêw
VTA-2: nitonawêw
VTA-3: kîskiswêw
VTA-4: nakatêw
VTA-5: ?

Crucially, we could just as well use any other exemplary verbs, but for now we have to select some set that we ourselves consider meaningful.

As for presentation, instead of showing a lexical entry as is currently the case:

1. askihtakwâw (Verb: VII-v)

... one would instead firstly show the following:

2. askihtakwâw (Verb: _mihkwâw_)

... or:

3. askihtakwâw (Verb: like _mihkwâw_)

4. askihtakwâw (like _mihkwâw_)

... and hovering over _tâpiskôc_ would give `VII-v/n` of whatever inflectional subclass the lexical entry would belong to.

The nêhiyawêwin alternative to 3/4 above would be to use _tâpiskôc_, so:

4b. askihtakwâw (tâpiskôc: _mihkwâw_)

**Comment by Madoshakalaka** [comment]
@eddieantonio just a reminder while I'm browsing issues. This is easily achievable, now that our Wordform model class has a `full-lc` field which records exactly the declination class.

**Comment by aarppe** [comment]
Important N.B. to whomever implements this - The plain English example words should be found in the file `crk.altlabel.tsv`.

Ideally, this would be configurable so that the user can decide with of the representations of the inflectional classes they see. And this selection might be tied with some other or meta choices, such as a linguistic (`VTA-1`) or non-linguistic mode (`like: wîcihêw`).

**Comment by aarppe** [comment]
@Madoshakalaka @kobexamoh I've updated https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/master/CreeDictionary/res/crk.altlabel.tsv to conform with the latest AEW inflectional subtype classification.

This means that the representation of the inflectional subtype should now be doable. We could present the plain English relabeling in conjunction with the dictionary entry heads, e.g. `like: nipâw` for `VAI-1,` or also show that with the general word class, e.g. `Verb, like: nipâw` for `VAI-1`.

**Comment by aarppe** [comment]
While this is the original issue on the topic and provides a good overview of the options, it is also somewhat outdated due to later development decisions and our better understanding of the matter, and is better and more comprehensively explained in #445.
