### ISSUE TITLE
Figure out what the deal is with the importer?

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#102]

**Comment by eddieantonio** [comment]
Yo @Madoshakalaka, I can close this, right? We're long past the time that we have no idea if the importer is doing its job or not.

**Comment by Madoshakalaka** [comment]
yes everything is completely figured out (for me)

**Comment by Madoshakalaka** [comment]
and the importer is now well documented
