### ISSUE TITLE
Automatically update changed dependencies on redeploy

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#105]
We need a smart way of updating the dependencies on the server. Right now, it simply does a git pull and touches the .wsgi file to reload the application. We'd like it to do a pip upgrade, but only when the dependencies change.

**Comment by Madoshakalaka** [comment]
I've been working on migrating this project to `pipenv`. `pipenv` will update dependencies to the `Pipfile` and `Pipfile.lock`. On the server side, `pipenv install` will install the newer dependency. So it will  be enough to just add `pipenv install` to the redeploy script.

**Comment by eddieantonio** [comment]
@Madoshakalaka this sort of works now, right? Can we mark this issue as resolved?

**Comment by Madoshakalaka** [comment]
Totally. In addition, `npm install` is also incorporated into the redeploy script so that npm dependencies are also updated
