### ISSUE TITLE
DatabaseManager.log files logs unescaped color code

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#107]
Taken from the log:

> 2019-08-20 18:10:58,371 — DatabaseManager.xml_importer — INFO — [34m22 (lemma, pos, lc) have duplicate fst lemma analysis to others.
Their definition will be merged[39m

Which is blue text on the terminal

Should be dealt with using [formatters](http://uran198.github.io/en/python/2016/07/12/colorful-python-logging.html)

**Comment by eddieantonio** [comment]
This code will be deleted soon.
