### ISSUE TITLE
edit redeploy script before merging feat/DictionaryImporter into master

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#109]
- git pull
- pipenv update
- touch the wsgi script

Also since the database schema changed, need to do a `pipenv run make-migrations && pipenv run migrate && pipenv run manage-db import CreeDictionary/res/dictionaries/crkeng.xml -m 4` manually before it starts to work on sapir. OR, maybe upload `db.sqlite3` via ssh to sapir if the database is already built in development

**Comment by Madoshakalaka** [comment]
oh no there's other stuff. need to reconfigure wsgi-express, disable the old sevice and enable the new service

**Comment by Madoshakalaka** [comment]
the old wsgi-express was in the venv folder but we switched to pipenv so the place is different

**Comment by Madoshakalaka** [comment]
I'd like to figure this out when I'm back

**Comment by eddieantonio** [comment]
> I'd like to figure this out when I'm back

No worries! Please figure it out when you're back!
