### ISSUE TITLE
Search does not work with more complex inflected forms (reduplication, non-lexicalized preverbs)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#114]
Searching some inflected forms (presumably in the inflected paradigms) yields lemmas, but for other more complex inflected forms, there is no match.

Examples:
1. Basic form: ninipan -> lemma match: nipâw (-> normative: ninipân) (+)
2. Reduplication: ninanipan -> lno result (lemma match should be nipâw; normative: nina-nipân) (-)
3. Productive preverb: nohte-nipaw -> lemma-match: nôhtê-nipâw (lexicalised; normative: nôhtê-nipâw) (+)
4. Productive preverb: kakwe-nipaw -> no result (lemma match should be: nipâw; normative: kakwê-nipâw) (-)

Also, missing a hyphen presents no match, though the descriptive model does recognize such forms (but marking them as orthographically nonnormative).

Example:
1. nikinipan -> no result (lemma match should be: nipâw; normative: nikî-nipân)
2. niki-nipan -> lemma match: nipâw (normative: nipâw)
3. ewapamat -> no result (lemma match should be: wâpamêw; normative: ê-wâpamat)
4. e-wapamat -> lemma match: wâpamêw (normative: ê-wâpamat)
5. nêpât (initial change) -> no result (lemma match should be: nipâw; normative: nêpât)

**Comment by eddieantonio** [comment]
@Madoshakalaka, this means that word forms  _must_ be looked up in the FST on each query; if it's only consulting the generated word forms, it's not doing enough :/

**Comment by aarppe** [comment]
Potential solution/Question: might the spell-checker FST (crk.zhfst) combining a weighted error correction model and an FST acceptor be a possible solution?

**Comment by Madoshakalaka** [comment]
let me look into it

**Comment by Madoshakalaka** [comment]
@aarppe @eddieantonio 

I just debugged the code and I have an idea what's happening

Long words short, these three have "Err/Orth" in their fst analyses, which is not handled correctly in the algorithm.
 
nikinipan 'nipâw+V+AI+Ind+Prt+1Sg+Err/Orth'
ewapamat: {'PV/e+wâpamêw+V+TA+Cnj+Prs+3Sg+4Sg/PlO+Err/Orth', 'PV/e+wâpamêw+V+TA+Cnj+Prs+2Sg+3SgO+Err/Orth

The last one though, I didn't know there exists "IC"
nêpât: {'IC+nipâw+V+AI+Cnj+Prs+3Sg'}

They will be a easy fix. I'll inform you when it's ready

**Comment by Madoshakalaka** [comment]
I'm on it

**Comment by aarppe** [comment]
Ok - when using the normative generator, one just has to remove the +Err/Orth tag (resulting from the descriptive analyzer). I believe this issue is related to #130.

**Comment by Madoshakalaka** [comment]
Now it's implemented correctly such that analysis outside paradigm tables will also get matched.

I tested on all 9 examples @aarppe proposed and they all show as expected.

Note for ewapamat and e-wapamat you'll get two results:

![Screenshot from 2019-10-23 14-21-38](https://user-images.githubusercontent.com/44753941/67431222-0beafc80-f5a1-11e9-8aec-78bfc761a856.png)

as ewapamat matches two inflected forms:
{'PV/e+wâpamêw+V+TA+Cnj+Prs+3Sg+4Sg/PlO+Err/Orth', 'PV/e+wâpamêw+V+TA+Cnj+Prs+2Sg+3SgO+Err/Orth'}

We'll soon have UI that shows the original matched form and the details of the inflection (Preverb, reduplication IC...), @eddieantonio is working on it

@aarppe Please try out on sapir to see if there are other improvements

**Comment by aarppe** [comment]
Great! I notice that my example cases weren't entirely complete, and I had overlooked the possibility of multiple normative forms of the same lemma matching one and the same fuzzy search string. While I corrected these above, this probably needs to be pursued as a separate issue.
