### ISSUE TITLE
Dynamically switch orthographies

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#123]
Switch orthographies from a drop-down menu.

Addresses the following user stories:

> * As a Cree language learner, I want to see all written Cree in Standard Roman Orthography with circumflexes (âêîô).
> * As a Cree language learner, I want to see all written Cree  in Standard Roman Orthography with macrons (āēīō).
> * As a Cree language learner, I want to see all written Cree in Western Cree syllabics.

**Comment by aarppe** [comment]
For the sake of explicitness, this selection of orthography concerns Cree words anywhere in the application, not just in the paradigms or normatized search results, but in the interface as well - if I've understood correctly our discussions with Eddie.

**Comment by eddieantonio** [comment]
> For the sake of explicitness, this selection of orthography concerns Cree words anywhere in the application, not just in the paradigms or normatized search results, but in the interface as well - if I've understood correctly our discussions with Eddie.

Correct. It should affect the display of Cree text EVERYWHERE!

**Comment by eddieantonio** [comment]
I increased the priority of this, since I think it's pretty important to MESC. As well, I've been itching to implement it!

**Comment by aarppe** [comment]
Yes, it is a very high MESC priority, and a tangible feature they will appreciate.
