### ISSUE TITLE
“Dictionary source” model

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#125]
We need a model that stores **bibliographic information** about a dictionary source. Its primary key will be the source abbreviation (e.g., CW, MD). It will contain the following fields (like a bibliographic reference!):

 - [x] Abbreviation (primary key)
 - [x] Title
 - [x] Authors
 - [x] Publisher
 - [x] City
 - [x] Year
 - [x] Editor

The `Definition` models must have a **many-to-many** relationship to dictionary sources. These are citations.

For the first iteration, there is no need to automatically import the bibliographic information from the XML; all that's needed is the ability to **modify the fields in the admin interface**.

Addresses user story:

> As an Administrator, I want to integrate words from multiple dictionary sources.

**Comment by aarppe** [comment]
Here are the first two:

Abbreviation (primary key): CW
Title: Cree : nêhiyawêwin : itwêwina / Cree : Words 
Author(s): NA
Editor/Compiler: Arok Wolvengrey
Publisher: Canadian Plains Research Center
City: Regina, Saskatchewan
Year: 2001
URL: NA
Non-academic citation: nêhiyawêwin : itwêwina / Cree: Words. Compiled by Arok Wolvengrey. Regina: Canadian Plains Research Center, 2001.
Academic citation: Wolvengrey, Arok. (2001). nêhiyawêwin : itwêwina / Cree: Words.  Regina: Canadian Plains Research Center.

Abbreviation (primary key): MD
Title: Maskwacîs Dictionary of Cree Words / Nehiyaw Pîkiskweninisa, Maskwachees Cultural College, Maskwacîs, 2009. 
Author(s): NA
Editor/Compiler: Maskwachees Cultural College 
Publisher: NA
City: Maskwacîs, Alberta
Year: 2009
URL: NA
Non-academic citation: Maskwacîs Dictionary of Cree Words / Nehiyaw Pîkiskweninisa, Maskwachees Cultural College, Maskwacîs, 2009.
Academic citation: Maskwachees Cultural College. (2009). Maskwacîs Dictionary of Cree Words / Nehiyaw Pîkiskweninisa, Maskwacîs, 2009.

**Comment by eddieantonio** [comment]
This is done! Antti, if you login to your admin account, should should see the two `DictionarySources` with the correct information.
