### ISSUE TITLE
Add rudimentary support for presenting spoken snippets

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#128]
We need to load recordings from the [recordings-validation-interface]:

Subtasks:

 - [x] Create UX for listening and selecting recordings [Diane]
 - [x] Create HTML/CSS from the designs [Eddie]
 - [x] Write integration test (can copy from old version of itwêwina) [Eddie or Matt]
 - [x] Implement it! [Eddie or Matt]

Address the following user story:

> As a Cree language learner, I want to hear recordings of words, by multiple speakers (women and men).

**Comment by aarppe** [comment]
While we already have an initial batch of recordings, we can substantially multiply this once #135 is undertaken.

**Comment by eddieantonio** [comment]
Rudimentary support is done! When you click on a definition, it will add a little 🔊 icon. Click that and hear a recording! e.g., https://sapir.artsrn.ualberta.ca/cree-dictionary/lemma/185694/

**Comment by aarppe** [comment]
Great! Already tried that and it works!

Do we have a list somewhere of what wordforms we currently have a recording for and available on the new itwêwina? I know several tens from the implementation on our old itwêwina, but a comprehensive list would be useful for demo and testing purposes. 

To be explicit, the intention right now has the rudimentary implementation provides one recording per word form (later to be expanded to more, and with speaker info).

Also later on, we can consider what would be the best place to access recordings. I can understand the current implementation on the paradigm page, but there could be a benefit in seeing those already on the search page, though I can guess this ease-of-access might have downsides.

**Comment by eddieantonio** [comment]
> Great! Already tried that and it works!
> 
> Do we have a list somewhere of what wordforms we currently have a recording for and available on the new itwêwina? I know several tens from the implementation on our old itwêwina, but a comprehensive list would be useful for demo and testing purposes.

Not currently, but I think I can make one relatively easily.

> To be explicit, the intention right now has the rudimentary implementation provides one recording per word form (later to be expanded to more, and with speaker info).
> 
> Also later on, we can consider what would be the best place to access recordings. I can understand the current implementation on the paradigm page, but there could be a benefit in seeing those already on the search page, though I can guess this ease-of-access might have downsides.

Yup! These are the plans for _less_ rudimentary recordings, but in order to enable that, we'd need to add support in https://github.com/UAlbertaALTLab/recording-validation-interface
