### ISSUE TITLE
Allow words that are not in the `Inflections` table to be recognized by lemma

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#130]
@aarppe said:

> it seems that the descriptive FST is still not used, since words with reduplication or lexical preverbs, or grammatical preverbs not in the  full paradigms, are not yet recognized.

I believe this is a tiny error in the lookup algorithm, which will only output a result if it exists in the `Inflection` table in the database, even if the FST recognizes it. If an analysis is given, and there's it's not a known wordform, it should be passed to the normative generator (minus +Err/Orth tags) and be output as a result, linking to its lemma. See #100.

**Comment by Madoshakalaka** [comment]
I'm on this

**Comment by Madoshakalaka** [comment]
this is fixed together with #114
