### ISSUE TITLE
Reorganize paradigms into a more intuitive and easy to search order

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#131]
We will want to shift the plain English and nêhiyawêwin paradigms to the simpler structuring, without the Algonquian division into SAP, Mixed, and Third Person (for Verbs), as user feedback has been that it makes finding the correct form difficult. The Algonquian ordering will  still be accessible in the linguistic *.layout specs.

In practice this means that subjects wlll be presented in Number > Person > Obviation order. And in the case of objects, those will be presented as a cohort, per each subject Number+Person+Obviation feature combination according to the same order.

Something like the following, though I notice that the obviative causes a bit of a headache as to the best natural order.

I -> you (one)
I -> you (all)
I -> him/her
I -> them
I -> him/her/them (further)

You (one) -> me
You (one) -> him/her
You (one) -> us
You (one) -> them
You (one) -> him/her/them (further)

- [x] basic paradigms
- [x] full paradigms

**Comment by aarppe** [comment]
This is now done for all basic paradigms, which need to be incorporated in the new itwêwina.

**Comment by aarppe** [comment]
@Madoshakalaka Started with this - but need to know if layouts are automatically updated or not? At least cujrrently that does not seem to be the case, having updated the `noun-na-full.layout`.

**Comment by Madoshakalaka** [comment]
@aarppe Not yet automatically updated. However, we can make it automatic real quick. I'm working on importing the stems right now. Later I'll make the update automatic

**Comment by aarppe** [comment]
@Madoshakalaka We will need this feature (of automated updating), as we will need to update the full layouts to conform with some discussions we've had with Arok and others. I've already made the changes in the itwêwina repo, so we should be able to test whether these new layouts get parsed correctly.

**Comment by eddieantonio** [comment]
@aarppe, has this been done in the layouts in #488?

**Comment by aarppe** [comment]
@eddieantonio Yes, these have been implemented in the new-FST layouts, and closing this issue is "just" awaiting their uploading and incorporation.
