### ISSUE TITLE
Show Cree dictionary sources properly

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#132]
Prerequisite: #126 

1. The current version now shows only MD (or CW) as a source for some lexical entries, even when such lexical entries occur in both sources and have been properly matched in the XML dictionary source (using Katie's comparison table).
2. In conjunction with this, sometimes the wrong source is provided for the English translation provided, in addition to not providing at all the English translation from the other source.

When clicking on the lexical entry to get the paradigms, the non-formatted page (for paradigm generation) does appear to indicate the sources properly - but this is not apparent when looking at the search results on the landing page.

Examples:

Missing source + wrong source
* search: atahk
* current results:
-- star(MD)
* results should be:
-- A big bright star. (MD)
-- star (CW)

Missing source:
* search: nipaw
* current results:
-- He sleeps.(MD)
* results should be:
-- He sleeps.(MD)
-- s/he sleeps, s/he is asleep (CW)

**Comment by Madoshakalaka** [comment]
Old cree dictionary (students ver.) only displays the first definition. It's still showing only the first definition, which is the cause the observation above.

It's a trival fix and it's fixed right now. The fix will apear on sapir in a later update.
