### ISSUE TITLE
Implement prefix search

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#133]
Alongside potentially finding a lexical entry of which the entire search string (whatever characters have been typed up to any point) is an inflected form, one should also show lexical entries, the beginning of which match the search string - if these haven't already been matches through the linguistic analysis.

Since many lexical entries have lexical preverbs (over 200 but known), the prefix search should also try to match the beginnings of stems occurring after the preverbs.

In all cases, prefix search should ignore vowel length differences, so [a|â] should match [a|â], likewise for [e|i|o].

Example:

1 . Search string:
- nipaw

2a. Matched lexical entry (as a result of successful spell-relaxed analysis):
- nipâw

2b. Partially matched lexical entries (without skipping lexical prefixes): 
- nipaw ayiwinisa (Noun)
- nipawihaw (Verb)
- nipawâkan (Noun, NDA-1)
- nipâwin (Noun, NI-1)
- nîpawi (Verb)
- nîpawihêw (Verb, VTA)
- nîpawipayihow (Verb, VAI)
- nîpawiw (Verb, VAI)
- nîpawiwinihk (Noun, INM)
- nîpawîstam (Verb, VTI)
- nîpawîstamawêw (Verb, VTA)
- nîpawîstawêw (Verb, VTA)
- nîpawîstâtowak (Verb, VAI) 

2c. Partial matches (skipping lexical prefixes):
- matwê-nipâw (Verb, VAI)
- mâci-nipâw (Verb, VAI)
- mâmawi-nipâwak (Verb, VAI)
- mêkwâ-nipâw (Verb) 
- nôhtê-nipâw (Verb, VAI)
- pê-nipâw (Verb, VAI)
- pêyako-nîpawiw (Verb, VAI)
- têpi-nipâw (Verb, VAI)

The following below for later consideration, once the above has been satisfactorily implemented:

I'm not sure if we'd also want to skip reduplicative prefixes (Ca-, Câh, and Ca-Câh-), i.e.

Search: nanipaw or na-nipâw results in nipâw.

I'm also not sure if we'd want to consider skipping grammatical prefixes (ni-, ki-, kî-, wî, ê-, ka-, kâ, etc.)

**Comment by aarppe** [comment]
The (new) user story for this is:

"When I search _nipa_, I want to see both dictionary entries starting with _nipa_, e.g. _nipâw_, as well as dictionary entries that contain _nipa_ in their core stem, e.g. _pê-nipâw_."

**Comment by Madoshakalaka** [comment]
@aarppe this is algorithmically hard to do -- I tried to implement it in PR #369 but it comes with a great performance hit (presumably over 10 seconds for the query string `nipaw`).

@eddieantonio Do you have suggestions on how this should be done?

This can become much more manageable if we have a specific list of prefixes/suffixes, as then a lookup table can be built beforehand which greatly reduces the search time.

**Comment by aarppe** [comment]
Yes, I have a recollection of having discussed that enumerating the prefixes, rather than allowing for unlimited prefix search, would be the way to go.

I can imagine how we could generate a list, or regular expression of prefix sequences which  could be skipped in order to search for stems as well. But that won't be ready for tomorrow.

But @Madoshakalaka we have thought-through prioritization for the next development steps, and I'd keep to it. It starts with a remainder from milestone 1 (#354) and then with the metaissue #346 which has the subissues #190, #325, #257, #258 and #101, in that order.

**Comment by Madoshakalaka** [comment]
@aarppe thanks I'll move to #354
