### ISSUE TITLE
Cree translation for Neahttadigisánit

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#137]
Neahttadigisanit is North Saami for network + digital + words.

What would be an appropriate Cree equivalent?

masinahikan kâ-itâpatak ayapîhk 'dictionary that is useful in the net' – MKIA

**Comment by aarppe** [comment]
_wêhci-itwêwin-masinahikan_ ~ 'easy word book'?

**Comment by eddieantonio** [comment]
I believe the original intent for this issue was that we wanted a name for the infrastructure, which we have settled on **morphodict**. However, the Cree translation is a separate issue (see #702, #707).
