### ISSUE TITLE
Back button doesn't work after navigating to a definition/paradigm

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#138]
Say you search for a word like [acâhkos](http://sapir.artsrn.ualberta.ca/cree-dictionary/search/acahkos/). Click on the definition and try going back to the search page. The URL changes, but the page content stays the same! Instead, I expect to go back to the search page I came from.

**Comment by Madoshakalaka** [comment]
fixed in a recent commit. Back and forward button now both work
