### ISSUE TITLE
Turn off automatic first-letter capitalization in search window

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#145]
At least on some gadgets (e.g. my iPad), the first letter of a search string becomes capitalized automatically - something that is incorrect in the case of Cree SRO. This is a nuisance that it would be nice to have turned off.

If the user intentionally capitalizes the first letter, they can do that, as the descriptive analyzer is able to deal with matching that with the non-capitalized standard Cree word form. The users should also be able to choose to capitalize any letter in the search string (whether English or Cree), irregardless of the orthographically correct/standard form of the Cree or English word form.

**Comment by eddieantonio** [comment]
@aarppe, try this now on your device! http://sapir.artsrn.ualberta.ca/cree-dictionary/

**Comment by aarppe** [comment]
Yes, now Cree SRO words are not capitalized.

And nicely, typing `calgary` or `edmonton` provides a pop-up? which provides the capitalized version. Does that come from matching the search string with English words as they are capitalized in the dictionary sources, or is implemented elsewise?

Though when I start typing `nipaw`, after `ni` I am suggested `NI`, and typing `niy` I am suggested `not` - where do these come from? As to configuring my iPad, I really have my thumb in the middle of my hand, to use a Finnish metaphor (I've done minimal configurations).

**Comment by eddieantonio** [comment]
I think the pop-up is a feature of your iPad? I don't believe we implemented that 😅 I think it's a default of the iPad...
