### ISSUE TITLE
Space characters should be allowed in search strings

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#147]
Our dictionary sources contain at least Cree (and perhaps also English) lexical entries that contain spaces. In Cree SRO, this occurs in (1) multiword phrases (in their standard spelling) and (2) orthographically non-standard spelling of preverbs and reduplicative elements without intervening hyphens.

1. Multiword phrases

acâhkos kâ-osôsit (Noun: comet, tailed star [CW])

acâhkosa kâ-otakohpit (Noun: Starblanket; literally: "One who has Stars as a Blanket"; name of Cree chief, signatory to Treaty 4 [CW])

Though some of these could be inflected, for now it is fine to treat them uninflecting dictionary entries.

2. Nonstandard spellings of complex word forms (using space instead of hyphen in separating preverbs and reduplicative elements)

niki nitawi kiskinwahamakosin
niki nitawi kiskinwahamakosin	PV/nitawi+kiskinwahamâkosiw+V+AI+Ind+Prt+1Sg	0

na nipat
na nipat	RdplW+nipâw+V+AI+Cnj+Prs+3Sg	0

Unless this breaks up something else, we should allow for spaces in the spelling of Cree search strings.

As for multiword English lexical entries, none come immediately to mind, so I will have to do some digging to find if there are any in our dictionary sources.

**Comment by eddieantonio** [comment]
I need to write a test case for this!

**Comment by aarppe** [comment]
Test cases:

1. Multiword phrases

- [ ] acâhkos kâ-osôsit (_comet_)

I suspect that these are currently excluded from inclusion in the outwards available dictionary, as the FST isn't able to recognize them.

In first instance and for the time being they should be treated as if uninflecting particles, since implementing their inflection could be quite complex, involving potentially more than one of the constituent words in complex ways.

E.g., for comet above:
Singular: _acâhkos kâ-osôsit_
Plural: _acâhkosak kâ-osôsicik_
Obviate? Locative? Possession?
Or, how about tense when referring to a historical comet? Should that be: _acâhkos kâ-kî-osôsit_?

2. Misspelled complex word forms

- [ ] niki nitawi kiskinwahamakosin
- [ ] ka ki awasisiwiyan
- [ ] na nipat

**Comment by eddieantonio** [comment]
Misspelled complex word forms work, but multiword phrases don't for some reason. We have to investigate! 🔍
