### ISSUE TITLE
Apostrophes should be recognized in search strings

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#148]
Apostrophes are increasingly used to mark a short, unstressed single vowel.

E.g.
`tân'si` for `tânisi`
`ka-nis'tohtaht` for `ka-nisitohtâht`

Currently, tân'si is matched, perhaps because is is a contraction that is listed in the LEXC part of the FST, but `ka-nis'tohtaht` (example from our Maskwacîs Cree recordings) is not.

The descriptive FST is able to handle this, cf.

```
ka-nis'tohtaht
ka-nis'tohtaht	PV/ka+nisitohtawêw+V+TA+Cnj+Prs+X+3SgO	0
```
... but the analyzing FST used in itwêwina is not. So apparently, search strings with apostrophes are not properly processed.

This can be considered another case of non-standard orthography, besides #147 .

We'll need this to work for English as well, for contractions like `don't` and possessives.

**Comment by eddieantonio** [comment]
Related to #146. As we have learned, I forgot to invert `crk-orth.hfst` before composing it! >.<

**Comment by eddieantonio** [comment]
I've updated the FSTs to the latest (with inverted `crk-orth.hfst`!) and added appropriate test cases. Try it now! http://sapir.artsrn.ualberta.ca/cree-dictionary/search/ka-nis'tohtaht/

**Comment by aarppe** [comment]
Good. Interesting how some issues sometimes get resolved through trying to diagnose something, at least superficially, else.
