### ISSUE TITLE
Present linguistic breakdown with stem and spelled out features

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#153]
This is the suggestion for the first implementation of what is discussed in #99, using option 3 (modified here to include a preverb as well as a different actually attested stem). This does not rule out presenting the same information at the bottom of the full paradigms.

3. Basic relabeling using stem:
nikî-nitawi-wâpamâw ← √wâpam- + Verb + Preverb: nitawi + Transitive Animate + Independent + Future + Intentional + Actor: 1st Person Singular + Goal: 3rd Person Singular

Besides the normatized form of the search string, present a `(?)` or `(!)` radio button that, when clicked, gives the stem as well as the spelled-out version of the linguistic analysis features provided by the FST.

Search with:
_nikiwapamaw_

Primary result:
_nikî-wâpamâw_ **(?)**
form of
_wâpamêw_ 

Secondary result: pressing **(?)** yields a pop-up with the following information:

_wâpam- + Verb + Preverb: nitawi + Transitive Animate + Independent + Future + Intentional + Actor: 1st Person Singular + Goal: 3rd Person Singular_

Tertiary result: preverbs and reduplicative elements are explicitly highlighted and presented
_Preverb: nitawi-_ **(?)**

Pressing **(?)** yields:
_'go and, go to; engaged in'_

The relabeling required by this scheme can be directly implemented based on `itwewina.relabel`. However, on the longer run we likely will want to have a more robust representation of multiple English and Cree plain/linguistic variants for presenting linguistic features or row/column labels in generated paradigms.

**Comment by aarppe** [comment]
The relabelings can be found here in the Giella infrasctructure:

`giella/apps/dicts/nds/src/neahtta/configs/language_specific_rules/user_friendly_tags/itwewina.relabel`

We would actually want to turn this into a single TSV file with multiple columns for the different possible representations of the features we need, and exclude quite much relabeling that is not needed in the new itwêwina. This would potentially serve relabeling of all of the FST features, the dictionary inflectional classes (VTA-1, etc.),  as well as the row/column labels in the paradigms. The new TST file has been specified by @eddieantonio earlier elsewhere, but would have roughly the following structure:

1. FST tag / Dictionary inflectional class / paradigm row/column label: `(+)Prs`
2. Linguistic spelled out version (short): `Present`
3. Linguistic spelled out version (long): `Present tense`
4. Plain English spelled out version: `Something is happening now`
5. nêhiyawêwin spelled out version: `ê-ispayik anohc/mekwac/mâna`

Right now, the first version would cover only the conversion/relabeling of FST feature tags into Linguistic spelled-out labels.

**Comment by aarppe** [comment]
A first stab at this relabeling/alternative labeling file can be found in:

`../giella/langs/crk/inc/paradigms/crk.altlabel`

**Comment by Madoshakalaka** [comment]
@kobexamoh 
https://gtsvn.uit.no/langtech/trunk/langs/crk/inc/paradigms/crk.altlabel
This is the full link of the place Antti mentioned. You'll be needing this file to update our interface!

**Comment by aarppe** [comment]
An online version of the above `crk.altlabel `file now stored in the Norwegian SVN can be found with the following link:

`https://gtsvn.uit.no/langtech/trunk/langs/crk/inc/paradigms/crk.altlabel`

**Comment by aarppe** [comment]
Duplicate in that it is exemplified in #209.

**Comment by eddieantonio** [comment]
Hey, @kobexamoh focus on #209. Doing that will resolve this issue as well!

**Comment by kobexamoh** [comment]
Oh thank goodness, okay! I was about to PM you to ask about which issues to focus on/how best to make sense of them. Thanks for the direction 🙏

**Comment by eddieantonio** [comment]
Closing this in favour of #209.
