### ISSUE TITLE
Present only standardized Maskwacîs Dictionary content

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#154]
Present only those entries from the Maskwacîs Dictionary, that have been standardized in terms of their orthography.

This means that the forms in question have been compared to lexical entries in Cree Words, and the relationship of the English glosses has been assessed. As a by-product this has resulted in the normatization of the spelling of the MD entry, the identification of the stem (from CW), and the identification of the inflectional class (i.e. the N[AI](D)?-[1-5] or V(II|AI|TI|TA)-[1-5] codes from CW). This means that the lemma exists in the FST, and that inflected forms of the lemma can be recognized as well as generated in the paradigms.

If the standardization hasn't been done, the lexical entry will not have a CW-style inflectional category nor a stem - so this information can be used to exclude such content for now, until these forms have been appropriately processed and added. This is something that Arok has expressly wished for.

**Comment by aarppe** [comment]
Currently, these can be identied as having the following XML field:

<stem>md_stem[nr]</stem>

**Comment by aarppe** [comment]
More properly on the longer term, this should be fixed by creating a proper lexical database of the Maskwacîs Dictionary content, which includes the following information:

1. Original MD lexical entry.
2. Normatized MD lexical entry.
3. Matching CW entry, if any. May require the creation of a unique ID on CW side, if match is ambiguous.
4. CW-MD English gloss comparison classification (reflecting how the English glosses are presented if comparable).
5. Cree stem (when appropriate, not for multiword phrases)
6. POS and inflectional class (following CW style).
7. Rapid Words semantic classification numbers
8. Rapid Words semantic classification labels
9. POS-parsed version of MD English gloss (useful for Eng-to-Cree search and in creating inflected English paradigm cells, if not already in CW).

Eventually, this will be extended as a result of the validation of the new words and sentences from the Spoken Dictionary of Maskwacîs Cree project.

**Comment by Madoshakalaka** [comment]
@aarppe Yep, I've done this. This is actually inherently done in the importing step and those not-standardised  have already been marked with an "as_is" label

I just filtered out those "as_is" results

Please do some checks to confirm. 

e.g. right now "nipa" only shows one standardised result, it was showing results like "kill him" from MD.

https://sapir.artsrn.ualberta.ca/cree-dictionary/search/nipa/

**Comment by eddieantonio** [comment]
@aarppe, could you verify this, and then close this issue?

**Comment by aarppe** [comment]
Seems to be the case - checked with _nohtekatew_ and _nohtekatewin_ that are only in MD but not in CW, and are not shown. However, this appears to be an orthographical variation that we have missed, since  _nôhtêhkatêw_ and _nôhtêhkatêwin_ are in CW. The comparisons were done with a descriptive FST before the implementation of -h- addition/removal in the spellrelax files.

We'll need to come up with some MD example case that is not just orthographically divergent from a CW lexical entry (as those should eventually be aggregated), but an entirely distinct lemma, but wasn't able to find any easily.
