### ISSUE TITLE
Creating an on-going comprehensive record of the end-user searches and actions

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#157]
In order for us to monitor how people use this new on-line dictionary, i.e. how do they search (with what search strings), and what functionalities they use (i.e. what actions they take using the dictionary), we'd need to have a comprehensive record of what the users do.

Ideally we'd have this set up already when we start asking the various alpha-testers to start using the application.

If this is automatically done as is the case with itwêwina (via apache), that's great - but besides that it could be useful to apply some processing on such usage data to make it more humanly parsable.

**Comment by eddieantonio** [comment]
This is possible right now! Administrators on `altlab.dev` can access logs, organized by `{year}/{month}` here: `/data/altlab-gw-nginx-logs/`
