### ISSUE TITLE
Tailored test data

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#159]
We can use a subset of `crkeng.xml` for testing, but it's more useful if we have a few **manually-selected** test entries, and then a few randomly selected entries to top it all off.

Also, `engcrk.xml` should contain _at least_ one entry for every lemma here:

Required lemmas:

 - [ ] wâpamêw (VTA)
 - [ ] wâpahtam (VTI)
 - [ ] wâpiw (VAI)
 - [ ] nîpin (VII)
 - [ ] nôhkom (NAD)
 - [ ] mîpit (NID)
 - [ ] mînos (NA)
 - [ ] nipiy (NI)
 - [ ] êkwa (Ipc)
 - [ ] niya (Pron)

Other useful dictionary entry:
 - [ ] nitawi- (PV)

Lemmas required for regression testing:

 - [ ] atâhk
 - [ ] acâhkos
 - [ ] nipâw
 - [ ] amisk
 - [ ] amiskwaciy-wâskahikan

**Comment by eddieantonio** [comment]
@aarppe Do you have any others to add to the _test database_ (a tiny subset of real database) that will be publicly shared in source form?

**Comment by aarppe** [comment]
The ones above are the ones that I've ended up testing whenever encountering a new version.

Perhaps a good representative set for verbs and nouns are the lemmas we use for regression testing of the FST:

maskasiy
mitâs
mitihtihkosiy
ninîkihik
nîskwa
nîtim
nîwa
nôhpan
asikan
askihk
ayapiy
êsa
ihkwa
kihci-okiniy
masinahikanâhtik
niska
pahkwêsikan
wâhkwa
mayakask
mêstakay
miskîsik
miskotâkay
mitêh
mîpit
nîwas
askêkin
astotin
cîmân
maskihkiy
mihko
mîkisasâkay
oskasâkay
ôsi
osk-âyi
pahkêkin
wâwi
atoskêw
mâtow
mîcisow
nêhiyawêw
nipâw
pimisin
mâyâtan
mihkwâw
miywâsin
pimamon
itêw
kiskiswêw
mowêw
nakatêw
natêw
nitonawew
wâpamêw
wîcihêw
kîsihtâw
mîciw
nâtam

In addition, one would like to have some examples from each part of speech, i.e. also pronouns and particles:

Pronouns (I note. that these are not matched in the new itwêwina):
awa
ôma

Particles:
ispîhk
ohci
anohc

**Comment by aarppe** [comment]
Also, do we need English search terms as well? As well as expected results? See #158

**Comment by Madoshakalaka** [comment]
@eddieantonio So I'm creating a new database file called `selected_words.sqlite3` enlisting all the words in this issues page. The onus is then on you to migrate current integration test cases to use these words. Does that sound right?

**Comment by eddieantonio** [comment]
@Madoshakalaka I guess? I mean, I intend the new database to _replace_ the current test database. That is, when `USE_TEST_DB=True`, it should load `selected_words.sqlite3` instead of the old test database. Plus, I have cleverly listed words I already hard-coded into the tests in the above list. The only missing ones I would like to see in the new test database are:

 - amisk
 - amiskwaciy-wâskahikan

I'll edit my top comment and add these to the list!

**Comment by Madoshakalaka** [comment]
@eddieantonio totally understand you!
