### ISSUE TITLE
Search with Cree pronouns does not produce results

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#160]
E.g., searching with the Cree pronouns _oma_ or _awa_ or _niya_ do not yield any results.

In contrast, searching with English words corresponding to the above does produce results

**Comment by Madoshakalaka** [comment]
update: in my development branch, this is fixed. I'll come up with tests to ensure later versions don't break this.

**Comment by eddieantonio** [comment]
Fixed as of 24b6a4fccf79cb7cb1bbef32f7d4776a86f384d8
