### ISSUE TITLE
Need a database/interface for managing our version of the CW, MD, and other crk dictionary sources

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#165]
In order for us to reliably create and supplement the aggregated dictionary source for Cree Words and the Maskwacîs Dictionary, we need a database solution with some practical interface for managing the content, the interrelationships between the lexical entries (assessment similarity or difference of their English glosses), as well as the addition of new lexical entries and new information concerning these entries.

This database would be the source for creating the the aggregate dictionary source used in (the new, mobile-first) _itwêwina_ as well as the LEXC files used in the crk FST.

In the case of CW, we will be getting incremental additions from AEW. In the case of MD, we would be adding to current content through the validation process of the Maskwacîs recordings - so this is connected with the further development of the validation interface/speech database. So, we will need a pipeline for integrating these additions so that they will end up appropriately in _itwêwina_.

For both CW and MD (and other sources), we need to ensure that the lexical entries have a **proper, full FST-stem** as well as a **proper inflectional subclass specification**, that can be used to generate the FST LEXC code. We will also want to generate a `POS-analysis of English glosses` for new lexical entries in either source, so that eventually we can generate inflected versions of the English glosses. Also, for new entries in either source, we will want to have some automation to check if a new lexical entry in one source resembles an existing lexical entry in another source, so that the assessment of semantic similarity of the English glosses can be prompted.

**Comment by snomos** [comment]
This is something we have been looking for for years also in Tromsø. Our present plan is to generalise the structure found in https://satni.uit.no/termwiki/index.php?title=Váldosiidu for terminology to also cover dictionaries, but our experience with the MediaWiki code is mixed, and we don't see this as a viable long-term solution. Also, there is work going on in Helsinki by Mika Hämäläinen targeting the same basic problem.

In the coming year we in Tromsø will have the need to convert at least three dictionaries from various ad-hoc formats to semantically structured xml, and then from there into a tool to allow both editing and maintenance of the dictionary source text as well as synchronisation with lexc sources.

Ideally we would like to separate the monolingual information (lexc, dictionary entry head word + infl. and other information) from the multilingual part (translations, domain specifications, examples, etc), and let the monolingual information be two-way synced with a lexc "database". This way people can continue to work in lexc if they want / need (and it is sometimes way more effective), and the full lexc lemma collection is available for future dictionary enhancements.

We have given these ideas some thoughts, and although we do not have any final solution, I think we should collaborate on this work. More minds, hands and eyes mean more work and good ideas 😃

**Comment by aarppe** [comment]
Our challenge here is that neither of the primary sources (CW nor MD) are static, but both are being added to (CW by AEW through his lexicographical work, and MD based on our recordings word with "new" lexical entries that we will be validating), which need to be continuously contrasted with new additions to either source (not to mention the incorporation of a third dictionary source such as Elders). And these resources are being developed (by others) on whatever platforms, from which we have to import.

Trying to script the aggregation from a number CSV-style sources and comparison files has made it clear that we need some type of proper (relational) database (to deal with the n-to-n relations), and then a linguist-friendly interface to that. At least currently, my idea is a no-frills solution using already existing standard solutions and which an academic can work with (me or our students).

**Comment by aarppe** [comment]
Copying from elsewhere:

@eddieantonio More properly on the longer term, aggregating Cree Words and the Maskwacîs Dictionary should be fixed by creating a proper lexical database of the Maskwacîs Dictionary content, which includes the following information:

1. Original MD dictionary entry.
2. Normatized MD dictionary entry.
3. Matching CW dictionary entry, if any. May require the creation of a unique ID on CW side, if match is ambiguous.
4. CW-MD English gloss comparison classification (reflecting how the English glosses are presented if comparable).
5. Cree stem (when appropriate, not for multiword phrases) <- can be extracted from CW, if match established, but likely good to specify under MD dictionary entry as well.
6. POS and inflectional class (following CW style).
7. Rapid Words semantic classification numbers
8. Rapid Words semantic classification labels
9. POS-parsed version of MD English gloss (useful for Eng-to-Cree search and in creating inflected English paradigm cells, if not already in CW).

The above information, coupled with comparably organized CW content, will allow for the instantaneous and easy dynamic creation of the aggregated Cree dictionaries' content.

Eventually, this will be extended as a result of the validation of the new words and sentences from the Spoken Dictionary of Maskwacîs Cree project.

We should consider whether this should be part of the validation project (as it serves it) or a separate small project.

**Comment by Madoshakalaka** [comment]
@aarppe I just realized this issue is recently (partially) achieved. @eddieantonio and I have switched to a more standard workflow where the database on the server is always persisted unless required to be changed.

We have already created a pretty power admin console that allows many changes to specific words and other things in our database backend. Security/permission-wise, this console is only accessible if your have an user created by administrative people (namely Eddie, Kobe, I and now @aarppe as I just created a admin user for you, I'll send you credentials in email and you can change them once you log in to the console)
 
The login page is accessible by attaching `/admin` to the url.
[https://sapir.artsrn.ualberta.ca/cree-dictionary/admin/](https://sapir.artsrn.ualberta.ca/cree-dictionary/admin/)

I suggest @aarppe try editting wordform on the admin console [https://sapir.artsrn.ualberta.ca/cree-dictionary/admin/API/wordform/](https://sapir.artsrn.ualberta.ca/cree-dictionary/admin/API/wordform/). They will be immediately reflected on the online Cree dictionary site.

**Comment by aarppe** [comment]
Ok, so I logged onto the admin side, and tried to add a hyphen to _ni_, since as a non-independent prefix it should always be written as _ni-_, but then I get the following error message:

![image](https://user-images.githubusercontent.com/15003407/72658489-f5212f80-396e-11ea-9417-e3122cac9a11.png)

I only changed the text, so it's not apparent what else I should change or fix.

**Comment by aarppe** [comment]
@aradu12 this is for you, based on our discussion today - we can probably treat this is a top-level meta-issue, under which we organize a number of more specific individual issues that are more straight-forwardly actionable.

**Comment by aarppe** [comment]
This is now being implemented in its own project: https://github.com/UAlbertaALTLab/dictionary-database-model

**Comment by eddieantonio** [comment]
Moved to UAlbertaALTLab/dictionary-database-model#3.
