### ISSUE TITLE
Dictionary/Lexical entries should not be merged (automatically)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#181]
As a result of fixing #158, we have a new issue in that Cree lexical entries representing different inflected forms (as specified in MD, and in some cases CW) are all merged under the lemma. This results in undesirable behavior, as the translations of the inflected forms are lumped together, when they do not really appropriately concern at all the lemma, but rather the meanings/translations for the inflected forms. An example of undesirable behavior is e.g. (only translations 2-7 are correct for _nipâw_ - translation #1 is for _mêkwa-nipâw_):

![image](https://user-images.githubusercontent.com/15003407/70310010-0541dd00-180f-11ea-8943-604928d5fee0.png)

While AEW has expressed that such inflected forms (or even preverb forms such as _mêkwa-nipâw_ that can be considered derivations, though there are several others) should eventually listed under dictionary/lexical entries as _"related forms"_ (but even then with English translations attached to those forms and not the lemma), for now the aggregate dictionary source has not been created with that in mind. Thus, when there are multiple dictionary entries in the aggregate source, these should be represented as separate dictionary entries in the new _itwêwina_, that is, reflecting how this is implemented in the old _itwêwina_.

So, searching with _nipa_, we should get something like the following entries (besides matches with other lemmas):

1. lemma _nipâw_, as a result of analysing search string _nipa_ with spelling relaxation:
![image](https://user-images.githubusercontent.com/15003407/70310347-b21c5a00-180f-11ea-947a-72fac062344d.png)

2. match of search string _nipa_ directly as inflected form _nipâ_:
![image](https://user-images.githubusercontent.com/15003407/70310437-eee85100-180f-11ea-9702-f89adccf2cbf.png)

3. Match of search string _nipa_ with inflected form _nipâk_, but only with the implementation with prefix search:
![image](https://user-images.githubusercontent.com/15003407/70310460-f9a2e600-180f-11ea-8320-6dfdd425016d.png)

4. Match of search string _nipa_ with another inflected form _nikî-nipân_, but only with the implementation of the prefix search (the same applies for _mêkwa-nipâw_): 
![image](https://user-images.githubusercontent.com/15003407/70310374-c3fdfd00-180f-11ea-9b27-3ad0a102a7a9.png)

**Comment by aarppe** [comment]
Here is another example. Searching with _acahkos_, I do not get separate results for acâhkos and atâhk, even though CW has two distinct lexical entries for the two words.

Regardless of whether a word is a derived form of another (e.g. _acâhkos_ is a diminutive of _atâhk_), if they have distinct lexical entries in either dictionary source, this distinctness should be preserved, and not automatically merged.

Correct behavior is exemplified in the old _itwêwina_:

`https://altlab.ualberta.ca/itwewina/crk/eng/?lookup=acahkos`
![image](https://user-images.githubusercontent.com/15003407/70420521-3537ed00-1a68-11ea-9ce6-5f14c6594dc9.png)

**Comment by Madoshakalaka** [comment]
@aarppe I'm fixing this issue. Worth to mention I believe the _acahkos_ case is related to #176 and it's already fixed. Right now this is what I'm getting for _acahkos_

<img width="650" alt="Capture" src="https://user-images.githubusercontent.com/44753941/71325385-2f4efc80-24a9-11ea-9152-f34bd1684d13.PNG">

**Comment by Madoshakalaka** [comment]
update: this is fixed in development. I will deploy on sapir later.

Note, there are some cases that where two entries really need to be merged. e.g. the following entries exist in `crkeng.xml`:
```
    <e>
        <lg>
            <l pos="N">pisiw</l>
            <lc/>
            <stem>md_stem[nr]</stem>
        </lg>
        <mg>
            <tg xml:lang="eng">
                <t pos="N" sources="MD">A lynx.</t>
            </tg>
        </mg>
    </e>


    <e>

        <lg>
            <l pos="N">pisiw</l>
            <lc>NA-2</lc>
            <stem>pisiw-</stem>
        </lg>
        <mg>
            <tg xml:lang="eng">
                <t pos="N" sources="CW">lynx; bobcat</t>
            </tg>
        </mg>
    </e>
```
I made cautious update to the code so these two is still merged. In short, two entries from xml will get merged only when "the wordform look the same and provided pos/lc can't distinguish them apart". I get the sense that this merging task needs not to be done mechanically, but this is just a small change to our already powerful importing process. And these entries should just consist of a small portion of our source file.

**Comment by Madoshakalaka** [comment]
A Chrismas gift from this fix: now our database permits customized definition to each inflected form, compared to the previous version where we only attach definition to lemmas.

This is a step forward for a better admin console in the future, where definition for each inflection can be manually edited.

**Comment by aarppe** [comment]
Ok - but cases like _lynx_ should be merged in our original database, rather than mechanically afterwards. For whatever resson, this particular match was missed out in our original source comparisons.

Anyhow, when we encounter such cases that might be mergeable, they should be flagged in the databaes, and then the English glosses compared as to whether they are effectively the same or not. In the case of _pisiw_, the CW definition is broader than the one in MD, for whatever reason that we might not be able to recover - so they should be treated as two distinct definitions.

**Comment by Madoshakalaka** [comment]
@eddieantonio we need UI to display potentially existing definition for matched inflection, to achieve what is desired here for search string "nipa". I believe we don't have it in the wireframe.

But as for the issue's case, i.e. 

> definition shouldn't be merged

My fix #200 will achieve it.

I will close this issue when it's merged and  create a new issue regarding the UI for definition of inflections.

**Comment by eddieantonio** [comment]
@Madoshakalaka Please create the UI issue regardless if #200 is merged. I'll review it shortly.

**Comment by Madoshakalaka** [comment]
@eddieantonio sorry I didn't see it earlier.

**Comment by Madoshakalaka** [comment]
@aarppe I closed this issue for now, as it's fixed on Sapir - nipaw now shows only two definitions. Please note that the other definition for inflected forms still do not show for now, even though their definition are correctly registered in the database, showing thoses depends on the interface change mentioned in #201 .
