### ISSUE TITLE
Inflected forms of POS-ambiguous lemmas are not recognized: ê-pipohk, ê-kîsikâk

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#190]
In conjunction with #185, some inflected forms corresponding to lemmas that have two POS are not recognized nor linked to the lemma reading with the right POS. For example:

- [ ] ê-pipok -> pipon (VII)
- [ ] ê-kîsikâk -> kîsikâw (VII)

**Comment by aarppe** [comment]
@Madoshakalaka is this fix available publicly, as I'm still not getting _ê-pipohk_ analyzed?

**Comment by Madoshakalaka** [comment]
@aarppe I didn't upload the new database immediately, should be ok now.
