### ISSUE TITLE
Those II verbs that should get plural forms not getting them in the mobile basic layouts

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#194]
Some but not all II verbs can get a plural, e.g. _pipon_ _'it is winter -> there were [so-and-so-many] winters'_ and _kîsikâw_ _'it is day[time] -> there were [so-and-so-many] days'_. Those plural forms should be apparent in the mobile basic layouts (as in the old _itwêwina_):

![image](https://user-images.githubusercontent.com/15003407/70790783-6e40cc00-1d9e-11ea-963b-2e26b75d7ac0.png)

This is in contrast to others such as _kimiwan_ _'it is raining'_, which should not. For those, the mobile basic layout presentation is currently working as it should be.

![image](https://user-images.githubusercontent.com/15003407/70790950-bcee6600-1d9e-11ea-8e46-9b051283abff.png)

- [ ] _pipon_: singular + plural forms generated
- [ ] _kîsikâw_: singular + plural forms generated
- [ ] _kimiwan_: only singular forms generated

**Comment by Madoshakalaka** [comment]
@aarppe @eddieantonio Our geneartor and analyzer don't seem to know these plural forms:

```
(cree-intelligent-dictionary) beef:~/PycharmProjects/cree-intelligent-dictionary$ pipenv run generate
Loading .env environment variables…
pipon+V+II+Ind+Prs+3Pl
pipon+V+II+Ind+Prs+3Pl  pipon+V+II+Ind+Prs+3Pl  +?



PV/e+pipon+V+II+Cnj+Prs+3Pl
PV/e+pipon+V+II+Cnj+Prs+3Pl     PV/e+pipon+V+II+Cnj+Prs+3Pl     +?



kîsikâw+V+II+Ind+Prs+3Pl
kîsikâw+V+II+Ind+Prs+3Pl        kîsikâw+V+II+Ind+Prs+3Pl        +?



PV/e+kîsikâw+V+II+Cnj+Prs+3Pl
PV/e+kîsikâw+V+II+Cnj+Prs+3Pl   PV/e+kîsikâw+V+II+Cnj+Prs+3Pl   +?



kimiwan+V+II+Ind+Prs+3Pl
kimiwan+V+II+Ind+Prs+3Pl        kimiwan+V+II+Ind+Prs+3Pl        +?



PV/e+kimiwan+V+II+Cnj+Prs+3Pl
PV/e+kimiwan+V+II+Cnj+Prs+3Pl   PV/e+kimiwan+V+II+Cnj+Prs+3Pl   +?


(cree-intelligent-dictionary) beef:~/PycharmProjects/cree-intelligent-dictionary$ pipenv run analyze
Loading .env environment variables…
piponwa 
piponwa piponwa +?



e-pipoki 
e-pipoki        e-pipoki        +?

```

**Comment by aarppe** [comment]
Yes. It turns out I must have been consulting the wrong source, as _pipon_ and _kîsikâw_ are both singular-only II verbs.

```
less src/fst/stems/verb_stems.lexc | egrep '^((kîsikâw)|(pipon)|(kimiwan)):'      
kimiwan:kimiwan3 VIIn_SG ;
kîsikâw:kîsikâ VIIw_SG ;
pipon:pipon3 VIIn_SG ;
```
 I must have mistakenly thought that at least pipon must take a plural, as it could be used to refer to a number of years (winters) ago.

If we trust the FST, this is no longer a bug.
