### ISSUE TITLE
Rank English-to-Cree search results by Cree lemma frequency and/or morpheme co-occurrence weighting

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#197]
Dependent on the calculation of weights in #163 (done) and then their incorporation in our lexical database #254 (next), the following step is actually sorting (primarily English) search results according to the ranking of the Cree lemmas that match the English search strings.

**Comment by aarppe** [comment]
A version of this is now done, and to be found in the Giella SVN in:

~/giella/art/dicts/crk/Wolvengrey/W_aggr_corp_morph_log_freq.txt

This was created with the following scripting:

```
~/Google\ Drive/CreeFST/Wolvengrey/Wolvengrey_1w_morphemes_170207B.txt | gawk 'BEGIN { while((getline < "/Users/arppe/giella/art/corp/crk/ahenakew_wolfart_lemma-freq-sorted.txt")!=0) { n[$2]=$1; tot+=$1; } FS="\t"; while((getline < "Wolvengrey_1w_morphemes_170207B.txt")!=0) { gsub("ý","y",$3); sub("^/","",$5); sub("/$","",$5); nm=split($5,m,"/"); for(i=1; i<=nm; i++) if(m[i]!="") N[m[i]]+=n[$3]*1; FS="\t"; } } NR>=2 { gsub("ý","y",$3); sub("^/","",$5); sub("/$","",$5); nm=split($5,m,"/"); if(n[$3]*1!=0) P=-log(n[$3]*2/tot); else P=-log(1/tot); p=0; for(i=1; i<=nm; i++) if(N[m[i]]*1!=0) p+=-log(N[m[i]]/tot); else p+=-log(1/tot); if(p==0) p=-log(1/tot); printf "%s\t%s\t%s\n", (p+P)/2, $3, $5; }' | sort -k1,1n > ~/giella/art/dicts/crk/Wolvengrey/W_aggr_corp_morph_log_freq.txt
```
The rank is the average of the A-W corpus-based log(P) of the lemma + the joint log(P) of the constituent morphemes (for which frequencies are weighted based on corpus occurrences), with zero frequency/probability of either smoothed as 1/N. The averaging is needed since for some items the derivational breakdown is only partial, leading in some cases to an altogether too good rank due to being based on a single frequent morpheme (and ignoring the rarity of the rest).

Anyhow, this sort of ranking is what should be used for ordering the Cree matches for English word searches, as it will prioritize 1) frequent Cree lemmas/lexical entries and 2) combinations of dictionary-wise and corpus-wise frequent derivational morphemes.

**Comment by aarppe** [comment]
A quick and dirty alternative would be to rank Cree lexical entries based on either 1) the number of constitutuent morphemes (but this is unreliable when the morpheme breakdown is not complete) or 2) the character length of the lemma (following Zipf's law/observation about the inverse relationship of word character length and frequency).

**Comment by aarppe** [comment]
What needs next to happen is for the ranks to be incorporated on the software side.

**Comment by aarppe** [comment]
To make tasks explicit:

- [ ] rank Cree dictionary entries matching English word searches using ranking from #163.

**Comment by aarppe** [comment]
The AWK code above has been turned into a shell-script `giella/langs/crk/tools/shellscripts/wolvengrey-weight.sh` to create a revised weighting for CW content, as follows:

`cat ~/GDrive/CreeFST/Wolvengrey/Wolvengrey_crk2eng_200202_altlab.tsv | tools/shellscripts/wolvengrey-weight.sh /Users/arppe/GDrive/CreeFST/Wolvengrey/Wolvengrey_crk2eng_200202_altlab.tsv /Users/arppe/giella/art/corp/crk/ahenakew_wolfart_lemma-freq-sorted.txt >  ~/giella/art/dicts/crk/Wolvengrey/W_aggr_corp_morph_log_freq.txt `

**Comment by aarppe** [comment]
@Madoshakalaka For some items, the ranking now seems to work as expected, e.g. the three variants of _eat_, cf. _mowêw_, _mîciw_, and _mîcisow_:

![image](https://user-images.githubusercontent.com/15003407/76565325-f010c600-646f-11ea-9655-336b044c41dc.png)

For the various types of _see_, we get as the two top-most matches phrases,  _kîhtwâm ka-wâpamitin_  and _mahti êsa_, that surely could not have so good a ranking, before the triplet that one would expect, i.e. _wâpamêw_, _wâpahtam_ and _wâpiw_.

![image](https://user-images.githubusercontent.com/15003407/76565415-25b5af00-6470-11ea-9854-1f77f76e004f.png)

We need to check how the rankings are in the internal database, as in the original rankings they are as we want them, cf.
```

9.06402	wâpamêw	wâp-/-am
9.39475	wâpiw	wâp-/-i
9.49894	wâpahtam	wâp-/-aht
13.4694	pê-wâpamêw	pê-/wâp-/-am
13.5889	pê-wâpahtam	pê-/wâp-/-aht
14.4171	mahti êsa	mahti/êsa
15.2385	isi-wâpahtam	iT-/-i/wâp-/-aht
15.6734	wâh-wâpahtam	{Câh-}/wâp-/-aht
15.9352	kîhtwâm ka-wâpamitin	kîhtwâm/wâp-/-am
16.4124	namôya wâpiw	namôýa/wâpi-
19.3527	saskaci-wâpamêw	saskat-/-i/wâp-/-am
19.5389	saskaci-wâpahtam	saskat-/-i/wâp-/-aht

```

**Comment by Madoshakalaka** [comment]
@aarppe I think maybe the bug is about multi-word phrases, I'll investigate.

**Comment by aarppe** [comment]
Yes, the phrases are the ones that seem to get too highly ranked - but they do have rankings nonetheless in `engcrk*.xml`.

**Comment by aarppe** [comment]
And those ranks are also in `engcrk*.xml`, cf. e.g.

`<t rank="124" pos="Ipc">kîhtwâm ka-wâpamitin</t>
`

**Comment by Madoshakalaka** [comment]
@aarppe it's fixed for multi-word phrases and should be up online in minutes

**Comment by aarppe** [comment]
The above cases illustrate that in matching MD with CW, there are some minor but still significant orthographical differences, which result in certain matches not being made that should be identified.

E.g. MD _mitsow_ 'He eats.' is not matched with CW _mîcisow_, and likewise MD _wapimew_ is not matched with CW _wâpamêw_.

This probably should be made into its own issue.

**Comment by eddieantonio** [comment]
This is resolved _enough_ for now. As mentioned, further work is to be done in UAlbertaALTLab/dictionary-database-model#2

**Comment by aarppe** [comment]
Yes, it is resolved to the extent that we can achieve now. Ideally, the ranking can be adjusted by tweaking the corpus/dictionary-based ranking model, and I've supplemented that with lemma+wordclass specific weights (in comparison to the current lemma-specific ones), but that still doesn't push _mahti_ down. So, everything might not be achievable algorithmically, and we might need to tweak the weights manually for a few salient cases.
