### ISSUE TITLE
Show definition for inflected forms

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#201]
As discussed [here](https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/181#issue-533839591), it's desirable to show definition for inflected forms (not only lemmas) when they exist. 

Currently we only show users the matched lemmas. This issue depends on the following UI where we'd also show matched inflections.

<img width="477" alt="Capture" src="https://user-images.githubusercontent.com/44753941/71635777-afc9d780-2be4-11ea-912a-24a122bac58b.PNG">

**Comment by aarppe** [comment]
A few important notes:

1. the string _ê-nêhiyawi-kiskinwahamâkosiyân_ could have two analyses, in which one has the preverb _nêhiyawi-_ lexicalized as the lemma _nêhiyawi-kiskinwahamâkosiw_, and the other with the preverb as a productive mofifier of the lemma _kiskinwahamâkosiw_.

Thus, the **two** correct representations for the search string _ê-nêhiyawi-kiskinwahamâkosiyân_ are the following:

![image](https://user-images.githubusercontent.com/15003407/71940173-94c20f00-3172-11ea-8cf0-426960af870b.png)

![image](https://user-images.githubusercontent.com/15003407/71940335-2df12580-3173-11ea-8405-42d8e3b8fa62.png)

**Comment by Madoshakalaka** [comment]
@aarppe I'll try to produce them

**Comment by Madoshakalaka** [comment]
I just noted we do not have "I am learning Cree" in our database but we do have definition for the lemma.
![Screenshot from 2020-01-14 15-27-22](https://user-images.githubusercontent.com/44753941/72388244-b0816400-36e2-11ea-81f4-1ea50442620b.png)


Since not all inflections have definition, and we'll possibly resort to English fst in the future, in the case of matched inflection without definition, should we add a piece of reminder in our user interface that says 

**showing definition for lemma below**

@aarppe @eddieantonio What do you think?

**Comment by Madoshakalaka** [comment]
@aarppe @eddieantonio I just re-examed #153 , so we'll have infomation about the lemma embedded in a popup with "(?)" icon right next to "form of xxxxx".

If I get the idea correctly, we will not show any definition in the case metioned above, and the purpose of "Form of xxxxx (?)" will be to redirect the user to our lemma page. Is this more preferred?

**Comment by eddieantonio** [comment]
> @aarppe @eddieantonio I just re-examed #153 , so we'll have infomation about the lemma embedded in a popup with "(?)" icon right next to "form of xxxxx".
> 
> If I get the idea correctly, we will not show any definition in the case metioned above, and the purpose of "Form of xxxxx (?)" will be to redirect the user to our lemma page. Is this more preferred?

For now, yes! If we don't have a definition for the matched wordform, but we _do_ have a definition for its lemma, we say "ê-wâpamât is a form of [wâpamêw](https://www.spacejam.com/)" and have the definition of "wâpamêw" below it. We can't define the matched wordform because we don't have a definition for it!

**Comment by Madoshakalaka** [comment]
@eddieantonio if we still attach the definition of the lemma, do you think it's neccessary to remind the user **showing definition for lemma** then?

**Comment by aarppe** [comment]
We want to use less linguistic terminology, so I'd think that we'd stick with _blaa is a form of_ (even though 'form' is not so plain English).

**Comment by eddieantonio** [comment]
> @eddieantonio if we still attach the definition of the lemma, do you think it's neccessary to remind the user **showing definition for lemma** then?

For now, let's just show the matched wordform _without_ its definition and say "form of ...", and directly under that search result will be the search result for the matched _lemma_. Recall the mockups:

![Screen Shot 2020-01-14 at 4 40 40 PM](https://user-images.githubusercontent.com/2294397/72392264-d4e23e00-36ec-11ea-9ec2-902b366d42a6.png)

The search for "niskak" matched two wordforms, but it shows four results, because neither result matched a term with a definition; hence, there are two search results per matched wordform.

**Comment by aarppe** [comment]
Importantly, at this point, the dictionary entries in the two sources MD and CW are mostly lemmas, though there is a small fraction of non-lemma inflected forms as well as multi-word phrases (currently, we shouldn't try to inflect multiword dictionary entries). Such non-lemma inflected forms as dictionary entries can be certain possessed forms for dependent nouns (both in MD and CW: _kôhkom_ 'your grandmother' = `nôhkom+N+A+D+Px2Sg+Sg`  <- _nôhkom_ 'my grandmother' = `nôhkom+N+A+D+Px1Sg+Sg`) or imperative forms for verbs (primarily in MD: _âcim_ 'you (one) tell a story (to him)' = `âcimêw+V+TA+Imp+Imm+2Sg+3SgO` <- _âcimêw_ 's/he tells a story to him/her' = `âcimêw+V+TA+Ind+Prs+3Sg+4Sg/PlO`. If the MD inflected forms haven't been standarized, then their not yet accessible.


So, for practically all inflected forms, the two dictionary sources do not have explicit definitions/translations for these forms, nor can we currently yet computational generate the inflected forms of the English translations. So for practically all of these inflected forms there would twice the results (or even more, if the linguistic analysis is ambiguous).

**Comment by aarppe** [comment]
Ok - so the above mock-up makes sense _only if_ the search string matches an inflected form that has an explicit definition (as a dictionary entry), and this word form can be analyzed to have a lemma that also has an explicit definition (among the dictionary entries). So, no anticipation of generated, inflected English translations (we don't have them yet).

If the word form doesn't have an explicit English definition among the dictionary entries, then one would simply say that '[word form] is a form of [lemma]' and provide the English translation for the lemma (which of course, is an inflected form).

**Comment by aarppe** [comment]
[Note that the representations in my comment on _ê-nêhiyawi-kiskinwahamakosiyân_ have been corrected 15.1.2020 to exactly match dictionary content, which was not the case earlier.]

**Comment by Madoshakalaka** [comment]
@eddieantonio can you update here on the most recent mock-up revision?

**Comment by eddieantonio** [comment]
@Madoshakalaka, here it is!

![mockup](https://user-images.githubusercontent.com/2294397/73031405-3b581200-3df9-11ea-98c7-b22289b41050.png)

@kobexamoh, this should look like one "card" in the Zeplin mockup. When tapping the `(?)` icon, it should open up the linguistic breakdown.

**Comment by aarppe** [comment]
In #224 we have some more explicit mock-ups of various scenarios with wordforms and lemmas (the ones in #209 are slightly dated).

**Comment by Madoshakalaka** [comment]
implemented in #226

**Comment by aarppe** [comment]
Duplicate of #209.
