### ISSUE TITLE
Bad search bar responsiveness under development

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#204]
Half or more of the search bar may overflow, failing local integration tests involving typing.

@eddieantonio I discovered more details for you. For me, this only happens under development. See the comparison below: The first is http://localhost in development, the second is [https://sapir.artsrn.ualberta.ca/cree-dictionary](https://sapir.artsrn.ualberta.ca/cree-dictionary). Both are rendered with the same viewport size in chrome phone emulator.

![local](https://user-images.githubusercontent.com/44753941/72102371-0f5e6c00-32e4-11ea-8033-1de842e83a8f.png)
![prod](https://user-images.githubusercontent.com/44753941/72102374-11282f80-32e4-11ea-94c0-3a40d3748374.png)

**Comment by Madoshakalaka** [comment]
It happens only under development, but it fails local integration tests. It is important as it hinders further integration test creation.

**Comment by eddieantonio** [comment]
I want to address [PEBKAC](https://en.wiktionary.org/wiki/PEBCAK) before I do some serious debugging. Does this happen on the master branch? Have you run rollup and have the latest version of the CSS created? Do you start the server using `npm start`?

This could just as well be a documentation bug, or a workflow bug.

**Comment by Madoshakalaka** [comment]
it's a PEBTIAV - Problem Exists Between True IDE and Vim. :fire:
