### ISSUE TITLE
Going from lemma detail page to home page by cleaning search bar does not erase lemma detail content

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#207]
This can be reproduced by the following procedures

- Go to search page [/search/wapamew](https://sapir.artsrn.ualberta.ca/cree-dictionary/search/wapamew/)
- click on the hightlighted link "wâpamêw"
- `Ctrl/Command + A` to select everything from the search bar
- press `backspace/delete`

![Screenshot from 2020-01-14 15-52-03](https://user-images.githubusercontent.com/44753941/72389543-d8be9200-36e5-11ea-9d48-8a52f78004e1.png)

**Comment by eddieantonio** [comment]
This is no longer replicable ¯\_(ツ)_/¯

Closing!
