### ISSUE TITLE
Presentation of orthographically standardized form and linguistic breakdown

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#209]
A. Search string _enipat_ -> single analysis, English definition only for lemma, no English definition for inflected form:

![image](https://user-images.githubusercontent.com/15003407/73315132-89e82080-41ec-11ea-976b-364de384eac8.png)

When clicking the `(?)` buttons, the following information becomes apparent (pops up):

![image](https://user-images.githubusercontent.com/15003407/73315155-9a989680-41ec-11ea-963a-553249482bc5.png)

B. Search string: ewapamat -> two analyses, same lemma, English definition only for lemma; no English definition for the inflected forms:

B1. **_First analysis:_**
![image](https://user-images.githubusercontent.com/15003407/73315226-c7e54480-41ec-11ea-9250-f36394d8c33f.png)

When clicking the `(?)` buttons, the following information becomes apparent (pops up):

![image](https://user-images.githubusercontent.com/15003407/73315283-eb0ff400-41ec-11ea-85b4-2046620855a5.png)

B2. _**Second analysis:**_
![image](https://user-images.githubusercontent.com/15003407/73315319-00851e00-41ed-11ea-84a2-f1b3115765a7.png)

When clicking the `(?)` buttons, the following information becomes apparent (pops up):

![image](https://user-images.githubusercontent.com/15003407/73315339-0da20d00-41ed-11ea-8b47-fba05f72e92c.png)

![image](https://user-images.githubusercontent.com/15003407/73315366-1c88bf80-41ed-11ea-827f-214cfa3d80dc.png)

C. Search string: _nicihciy_ -> one analysis, English definition for both inflected form + lemma

![image](https://user-images.githubusercontent.com/15003407/73315550-9ae56180-41ed-11ea-870b-5e88a54694fc.png)

When clicking the `(?)` button , the following information becomes apparent (pops up):

![image](https://user-images.githubusercontent.com/15003407/73315603-c2d4c500-41ed-11ea-9c41-545630deac40.png)

**Comment by aarppe** [comment]
@eddieantonio Did my best understanding of the UI design, with the two cases above. I suppose each of these could be split with the (inflected) wordform in one box and the lemma in another, but I have to say that that starts getting somewhat confusing/repetitive, though I may be wrong.

**Comment by Madoshakalaka** [comment]
@aarppe are you suggesting we indicate the different between "definition for both lemma and inflected form" and  "definition for lemma only" with a newline?
i.e.

>\<inflection\>
>form of \<lemma\>

and

>\<inflection\>
>form of
> \<lemma\>

A side note, the exclamation mark feels too aggresive to me.

**Comment by aarppe** [comment]
That was my error. I wasn't aiming at treating the two cases differently - for reasons of space I'd have 'form of' always on a line of its own.

I was taking the exclamation/question marks from whatever mock-ups i had seen, though I didn't usually consult the UI designer's source which I should. Generally, using (?) would seem appropriate, as one is asking for more information.

You might note that I put the part-of-speech (Noun, Verb, etc.) with the dictionary entry rather than the inflected form, because in principle a derived form could have another P-O-S code than the lemma/dictionary entry.

On the other hand, I had the (!) or (?) button that gives the linguistic breakdown in conjunction with the inflected form rather than the dictionary entry, because the analysis concerns the inflection/derivation, and less the dictionary entry (which mostly is a lemma).

Anyhow, the above notes are cosmetic tweaks that can be adjusted as we see best.

**Comment by aarppe** [comment]
See #224 and #227 for updated mock-up versions of the above.

**Comment by aarppe** [comment]
The relabeling schemes can be found here in issue #153: https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/153#issuecomment-576921074

**Comment by aarppe** [comment]
@kobexamoh In terms of priority, here is an ordered listing of subtasks for presenting the dictionary entry match and linguistic breakdown:
- [ ] 1. moving the dictionary entry for an inflected form between the standardized form and the `form of ...` line (see _nicihciy_ above)
- [ ] 2. relabeling of FST feature tags (to linguistic ones), e.g. `Ind` -> `Independent`, regardless of formatting
- [ ] 3. inclusion of proper stems (once the `<stems>` field is imported from the dictionary source).
- [ ] 4. improving the formatting of the linguistic breakdown (e.g. presenting a feature per line on smaller screens, and/or 1) prefix features and 2) suffix features together and 3) the stem on a line of their own), dynamically adapted based on screen size.

Steps 1-3 above are minimally satisfactory, after which we can devote further time on step, potentially based on alpha user feedback.

**Comment by eddieantonio** [comment]
Hey @kobexamoh! Since #240 and #241 is merged, you can use the **user-friendly tags** and are no longer blocked here. 😃

**Comment by aarppe** [comment]
Yes, https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/pull/240#issuecomment-582231367

The originally unintended result (Plain English relabeling) turned out to be a good one (i.e. matching with the paradigms).

**Comment by aarppe** [comment]
If steps 1-3 above have tests, then we can close this issue, with step 4 having been moved into its own issue #266.
