### ISSUE TITLE
search results do not show upon visiting /search/user_query/

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#210]
If one visits [https://sapir.artsrn.ualberta.ca/cree-dictionary/search/niskak/](https://sapir.artsrn.ualberta.ca/cree-dictionary/search/niskak/), the query "niskak" will appear on the search bar, but search results won't show untill you make changes on the search bar.

**Comment by Madoshakalaka** [comment]
actually this works for me locally -- I can't reproduce the issue. Can anybody confirm? @eddieantonio @kobexamoh

**Comment by eddieantonio** [comment]
I can still reproduce :(

Try this: https://sapir.artsrn.ualberta.ca/cree-dictionary/search/wapamew/

**Comment by eddieantonio** [comment]
Lol nm, I just didn't wait long enough for the app to redeploy >.<

Please close this again!
