### ISSUE TITLE
Use conventional web way of doing search

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#212]
Right now it redirects to`?q=searchterm`. Frankly, this is the most appropriate way to do things on the web -- the `/search/searchterm` is kind of a weird way to do things, but either way, the `?q=searchterm` should, in fact, execute the appropriate search. Related to #210.

**Comment by aarppe** [comment]
@eddieantonio It looks like:

1. pressing the enter key, after inputting a string in the search box, such as _mici_, does result in that string being searched (and matched), or
2. one ends up on the landing page, if there is no match.
3. also, matching is done with every input character even without pressing the enter key, and
4. if one presses the enter key after a string that isn't a wordform, like _mi_ or _mic_ (even taking into account the spelling relaxation), one ends up on the landing page.

So, isn't this working as it should?

**Comment by aarppe** [comment]
But now I notice that pressing enter with a legitimate search string results in a match, but so that the (i) info-button no longer produces a pop-up window for the linguistic breakdown nor the preverbs, if apparent. So, there is a vestigial bug.

**Comment by eddieantonio** [comment]
I've changed this issue to the following:

Search _should_ follow the conventions of other websites, like 

* Google: <https://www.google.com/search?q=foo>
* GitHub: <https://github.com/search?q=foo>
* mdn <https://developer.mozilla.org/en-US/search?q=foo>
* DuckDuckGo <https://duckduckgo.com/?q=foo>

etc.

Why? Mostly because my browser picks up on it automatically: 

![Screen Shot 2020-03-10 at 10 11 29 AM](https://user-images.githubusercontent.com/2294397/76333712-9f566d00-62b7-11ea-9582-d2e245ed42aa.png)
![Screen Shot 2020-03-10 at 10 11 48 AM](https://user-images.githubusercontent.com/2294397/76333720-a3828a80-62b7-11ea-914b-0a3c1fedcb76.png)
![Screen Shot 2020-03-10 at 10 11 59 AM](https://user-images.githubusercontent.com/2294397/76333740-aa110200-62b7-11ea-982f-edc119dc0769.png)

Except my browser thinks the search page is `/search/herp?q=`! 😩
