### ISSUE TITLE
Add regression test for displaying standardized form of enipat

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#215]
The standardized form should be "ê-nipât" (rather than ênipât without dash) and the user should be shown the below

![Screenshot from 2020-01-16 16-13-05](https://user-images.githubusercontent.com/44753941/72570823-2b7d8280-387b-11ea-96dd-3f77097d5973.png)

**Comment by aarppe** [comment]
You've got more cases enumerated in #100.

**Comment by eddieantonio** [comment]
This has been tested since f04b22d9c4bfdc46ab984fe1f00f481e317b9e0b
