### ISSUE TITLE
Matching Cree forms with long vowels unmarked not working

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#218]
Pursuant #195, in searching with a Cree word ignoring vowel length, e.g. _kihci-mohkomaninahk_ for _kihci-môhkomâninâhk_ or _kihci-mohkoman_ for _kihci-môhkomân_, does not result in a match. Contrary to our assumption, one needs to get the vowel-length-diacritics right, which is not the expected behavior. Does the hyphen derail the matching algorithm?

**Comment by Madoshakalaka** [comment]
I think it's fixed now
