### ISSUE TITLE
Create glossary in docs/

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#220]
Our projects involve lots of terminology, and we need to make sure we're being consistent with our terminology

Here are some terms we need to define

 - [x] analysis
 - [x] definition
 - [x] lemma
 - [x] wordform
 - [x] ~~inflection~~
 - [x] ~~lexical category~~
 - [x] ~~lexical~~ dictionary entry
 - [x] normatize/standardize
 - [x] (dictionary) source

@aarppe any other terms?

> **Edit**: added terms by @aarppe 
 
- [x] dictionary entry
- [x] inflectional category
    - [x] conjugation [formal] — subtype of inflectional category
    - [x] declination [formal] — subtype of inflectional category
- [x] part-of-speech
- [x] word class
- [x] stem
- [x] (inflectional) paradigm
    - [x] conjugation [informal] (see _paradigm_)
- [x] ~~(orthographically) standardized/normatized form~~
- [x] derived form
- [x] gloss (synonym of definition???)
- [x] translation (synonym of definition)
- [x] ~~inflected form~~
- [x] derivation
- [x] morpheme

For each term, we should state whether its:

 - "common" speak or "formal" speak
 - if the term refers to something being stored ANYWHERE in our apps
 - if it's stored, is it _essential_ or _accidental_ state

Use these as inspiration, though I think we should avoid copy-pasting from these.

https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/wiki/Glossary
https://github.com/UAlbertaALTLab/itwewina/blob/development/docs/glossary.md

**Comment by aarppe** [comment]
For starters, some if which are more or less synonyms of the terms already enumerated above:
- [ ] gloss
- [ ] translation
- [ ] derivation
- [ ] dictionary entry
- [ ] stem
- [ ] (inflectional) paradigm
- [ ] inflected form
- [ ] derived form
- [ ] (orthographically) standardized/normatized form
- [ ] inflectional category
- [ ] declination
- [ ] conjugation
- [ ] part-of-speech
- [ ] word class

**Comment by eddieantonio** [comment]
All of these terms have been defined since 6631600!
