### ISSUE TITLE
Typing "ayiman" does not result in "âyiman"

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#223]
The correct word is "âyiman", but search for it without the diacritic yields nothing. Spell-relax should match it with or without the diacritic.

https://sapir.artsrn.ualberta.ca/cree-dictionary/search/%C3%A2yiman/

https://sapir.artsrn.ualberta.ca/cree-dictionary/search/ayiman/

**Comment by eddieantonio** [comment]
Potentially related to #222?

**Comment by Madoshakalaka** [comment]
it's fixed now
