### ISSUE TITLE
Presenting inflected Cree word forms with explicit or generated English definitions

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#224]
Following up on #209, this issue focuses on example mock-ups of cases/searches that match with dictionary entry providing an explicit or generated translation of an inflected word form of some particular lemma.

1. Explicit translations:

![image](https://user-images.githubusercontent.com/15003407/72946978-c96ec280-3d3d-11ea-95cd-9bd4044aaf25.png)

![image](https://user-images.githubusercontent.com/15003407/72946989-d095d080-3d3d-11ea-8452-9fd0fc745b05.png)

![image](https://user-images.githubusercontent.com/15003407/72947000-d7244800-3d3d-11ea-99de-86e7c05153b4.png)

2. Generated translation (we do not have this yet, but have plans on how to do it):

![image](https://user-images.githubusercontent.com/15003407/72947028-edca9f00-3d3d-11ea-9dd4-c991736202b6.png)

The ![image](https://user-images.githubusercontent.com/15003407/72947085-32563a80-3d3e-11ea-8fe8-8b83c3b00a02.png) sign indicates **_Computer-generated translation_**.

**Comment by aarppe** [comment]
@eddieantonio This is an mock-up of dealing with these forms that we discussed this afternoon. Maybe one might add some hairline between the translation for the inflection and the information concerning the lemma.

**Comment by Madoshakalaka** [comment]
update: explit definition is now shown in production. Icons are now not incorparated because automatic English definition generation is not yet there.

**Comment by aarppe** [comment]
The only icon that is relevant for the generation of inflected English definitions is the exclamation mark - which is supposed to indicate such generated translations.

On the other hand, what can and should already be implemented is the provision of the linguistic breakdown (i.e. the spelling out of the underlying analysis FST tags), which can be toggled with the question mark icon. When there is a preverb, one can get the full translation of that by toggling a question mark icon as well.

**Comment by eddieantonio** [comment]
Fixed as of #462; @aarppe, please reopen if you think otherwise.
