### ISSUE TITLE
We have too many dang issues!

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#229]
The amount of overlapping and outdated issues we have is getting a bit out-of-hand. @aarppe, could you please go on a spree and close all outdated/already addressed issues, and close issues that that overlap or are covered by other issues?

To start with, you can mark issues with `duplicate`, and then link them together, and THEN close some issues. That way, your dev team has less to worry about!

**Comment by aarppe** [comment]
I've now gone over the open issues. One should start with #205, and follow the lead issues mentioned there, namely #209 and #224 for AEW compliance, and then #128 and #149 for MESC compliance, and #123 for making the last step for us to no longer need the old itwêwina.

Everything else are either bugs or other unexpected functionality in current implementation, or nice improvements. Obvious bugs should be fixed, but anything else shall be considered after these minimum features are implemented miminally satisfactorily.

**Comment by Madoshakalaka** [comment]
closed for being too sassy
