### ISSUE TITLE
Test database and XML do not include all relevant entries

### ISSUE THREAD

**Issue by Madoshakalaka** [UAlbertaALTLab/cree-intelligent-dictionary#230]
test database shows the following result:
![Screenshot from 2020-01-24 15-17-39](https://user-images.githubusercontent.com/44753941/73108140-bcc4a880-3ebc-11ea-9ead-c16788fd0373.png)

while in production:
![Screenshot from 2020-01-24 15-17-45](https://user-images.githubusercontent.com/44753941/73108143-be8e6c00-3ebc-11ea-8cb8-8b75c8b4871b.png)

Further inspection suggests that "kawinêw" is only included in `test_dictionaries/engcrk.xml` but not `test_dictionaries/crkeng.xml`, which suggests `DatabaseManager/build_test_db.py` does not include all relevant infomation as expected.

**Comment by eddieantonio** [comment]
This has been fixed since engcrk.xml disappeared (Since at least 1d1a8f6e1aa1d7939e62ad23968b5d466371b6bb)
