### ISSUE TITLE
Ordering of dictionary information for inflected forms with English definition

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#232]
As a specific observation/argument pertaining to #209, the more I look at the actual current search results, e.g. with _kôhkom_ (edited and annotated so that this screenshot is understood as something to be changed):

![image](https://user-images.githubusercontent.com/15003407/73418850-49ff6700-42da-11ea-80bf-7f0d10efb04e.png)

... the more I think that ordering of the definition and lemma should be revised, so that the English translation for the inflected form, here _kôhkom_, follows immediately after the form, then followed by `form of`, and then a separate line for the lemma and its English translation. The translation _'your grandmother'_ concerns really only _kôhkom_ but not _nôhkom_ (which is the lemma, as the 1st person singular possessed form is used as such for dependent animate nouns), so the current ordering is confusing - rather, I'd see something like the following:

![image](https://user-images.githubusercontent.com/15003407/73319497-d0904780-41f9-11ea-982d-ac888d5b03ee.png)

Clicking on the ![image](https://user-images.githubusercontent.com/15003407/73319523-db4adc80-41f9-11ea-828d-2b51d0c12db3.png) button next to the **_inflected form_** _kôhkom_ would then give the following linguistic breakdown:

![image](https://user-images.githubusercontent.com/15003407/73402321-4bb13680-42aa-11ea-8835-0204f8285ba3.png)

I suppose this could be dealt with by turning the lemma after `_form of_` into a very small font, but we end up repeating the lemma twice.

Note that the "simplified" or _general_ (English-relevant) word class for both _nôhkom_ and _kôhkom_ is noun, so that should be presented twice.

For an inflected form without a translation, the general word class (Noun, Verb, Particle, Pronoun) shouldn't be presented at all, but rather in conjunction with the lemma.

When the search string _**matches**_ directly with the lemma, e.g. searching with _nôhkom_, one should provide a linguistic breakdown for the lemma, i.e having a ![image](https://user-images.githubusercontent.com/15003407/73402488-a34fa200-42aa-11ea-8f5d-b8426947a3e5.png) button next to the lemma in its standard form:

![image](https://user-images.githubusercontent.com/15003407/73402428-8024f280-42aa-11ea-9a95-c78f6db9dd74.png)

Clicking the ![image](https://user-images.githubusercontent.com/15003407/73402474-9d59c100-42aa-11ea-946e-1c0298cc94c3.png) button then gives the following information:

![image](https://user-images.githubusercontent.com/15003407/73402457-97fc7680-42aa-11ea-8329-72306eefabc9.png)

If there is no English translation for the inflected form, then nothing will be presented and that space/line omitted.

**Comment by eddieantonio** [comment]
I like this! @kobexamoh, this is a good one for you!

**Comment by aarppe** [comment]
Note that the **_stem_** is a separate field in the dictionary source, that we have for all CW content, and MD content that matches with CW content. However, for MD content not matching CW content, we do not yet have a stem. The stem is the lemma without the inflectional affixes, e.g. _-ohkom-_ for _nôhkom_.

**Comment by eddieantonio** [comment]
Fixed as of #462; @aarppe, please reopen if you think otherwise.

**Comment by aarppe** [comment]
@eddieantonio Yes, this has been subsumed by other issues, and is effectively closed now. Whatever further modifications we do to the UI presentation (e.g. do we want/need to present the lemma in 'form of'), those would become new issues.
