### ISSUE TITLE
Stem should be imported into the Wordform model

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#235]
For wordforms that are lemmas (all from `CW`, which might be matched with `MD` but not always not), they must also keep track of the stem. This is needed for presentation in the linguistic breakdown (#153, #209)

e.g.., atim (NA) has the stem "atimw-". This would show up in the linguistic breakdown, so breaking down "atimwak" would be: "atimw- + Noun + Animate + Plural".

e.g., maskwa (NA) has the stem "maskw-". so "your bear" kimaskom = your + "maskw-" + Noun + Animate + Singular. 

e.g., nôhkom (NAD) has the stem "-ohkom-", so "my grannies" nôhkomisak = my + -ohkom- + Noun + Animate + Dependent + Plural

For non-dependent nouns and verbs, the stem ends with a hyphen, because the stem is not a wordform by itself, but requires a suffix. For dependent nouns, the stem begins and ends with a hyphen, because they obligatorily need both a prefix and a suffix.

**Comment by Madoshakalaka** [comment]
:cry: I got this

**Comment by aarppe** [comment]
The stems are provided in the old XML in the `<stem>...</stem>` field. All CW dictionary entries should have a stem, and if/when MD ones have been linked to CW entries, then they share the stem.

For dictionary entries solely in MD, the stems need to be manually added, later on.

**Comment by aarppe** [comment]
@Madoshakalaka In terms of immediate priority, we can make do in the linguistic breakdown with **just the lemma**, _without any hyphens generated before or afterwards_, until the stem importation is done. When the stem import is done, **no hyphens should be generated** but one should use the stems exactly as they are.

**Comment by aarppe** [comment]
Stems can be found in the crk-to-eng aggregate XML file, i.e. `giella/art/dicts/crk/crkeng_cw_md.xml` (the other way around was intended for linking English search words with the headwords of the Cree dictionary entries, but not have the entire content).

**Comment by aarppe** [comment]
In particular, the stems are in: `~/giella/art/dicts/crk/crkeng_cw_md_200314.xml`, also to be found on sapir. Note that some entries (in particular multipart words) do not have stems. In such a case, when we get to implementing their presentation, we can just show a hyphen `-`.

**Comment by aarppe** [comment]
@Madoshakalaka While you're looking into importing various things from the XML files, you should also import the **stem** field in `crkeng*.xml`. This would allow us to eventually show that in the linguistic analysis/breakdown, or separately in further information.

**Comment by eddieantonio** [comment]
Blocked by #389 (I think...?)

**Comment by eddieantonio** [comment]
Fixed! Thanks, @Madoshakalaka!
