### ISSUE TITLE
The corpus/dictionary-based ranking of Cree dictionary entries needs to be implemented.

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#236]
When I search with the English word _sleep_, I get the following results:

![image](https://user-images.githubusercontent.com/15003407/73429379-cb65f200-42f8-11ea-9fa2-9fc77db8c4ac.png)

As this is not optimal, we need to incorporate in the database the ranks generated  #197, and sort the English search results accordingly.

This is the ordering of the above results, if using the said ranking and below simple code:

`cat sleep.txt | gawk 'BEGIN { while((getline < "W_aggr_corp_morph_log_freq.txt")!=0) rank[$2]=$1; } { if($0 in rank) printf "%f\t%s\n", rank[$0], $0; }' | sort -k1,1n`
```
7.825700	nipâw
10.577700	kapêsiw
11.394300	katikoniw
11.394300	wîhpêmêw
12.258400	nipâwin
12.414200	itihkwâmiw
12.716700	nipêhêw
13.014200	nipâsiw
13.653900	nipâskâkow
13.703600	nôhtê-nipâw
13.724200	pêyakohkwâmiw
13.758000	pê-nipâw
13.768300	miyohkwâmiw
14.216900	nipêskâkow
14.360700	nipâskiw
14.537100	nîsohkwâmiwak
14.916800	têpihkwâmiw
14.985200	wîhpêmitowak
15.096200	nistohkwâmiwak
15.217600	mostihkwâmiw
15.232900	têpi-nipâw
15.564200	kîsôhkwâmiw
15.819600	nipêhkâsow
15.961500	mâmawi-nipâwak
16.022300	matwêhkwâmiw
16.087400	ayamihkwâmiw
16.089100	micimihkwâmiw
16.166200	kiyâmihkwâmiw
16.166200	sâpohkwâmiw
16.368900	nâspitihkwâmiw
16.412400	kîskwêhkwasiw
16.412400	sîpihkwasiw
16.731100	wîhpêmiskwêwêw
16.867000	wâpanihkwâmiw
18.515300	wîci-wîhpêmêw
18.964500	tahtotipiskwêw
19.442900	pôsâhkwâmiw
20.815500	kikaskisinihkwâmiw
21.938100	nipêskâkêmakan
24.910700	mosêtiyêhkwâmiw
```

**Comment by Madoshakalaka** [comment]
I don't usually sleep with bare buttocks. But yes, this makes a lot of sense for English keyword search. 
> this is not optimal

Yes, search resulted matched from English results is just unsorted and left random. We have "todo:" in the proper place for English search sorting code.

This looks straightforward to implement with `giella/art/dicts/crk/Wolvengrey/W_aggr_corp_morph_log_freq.txt`!

**Comment by aarppe** [comment]
@Madoshakalaka Good - since the giella/art directory (on SVN) requires special access, just let me know where we keep the dictionary source files (that are not public) so that I can copy the W_*.txt file there, if you can't get hold of the file otherwise.

**Comment by eddieantonio** [comment]
> I don't usually sleep with bare buttocks. 

Evidently neither do nêhiyawak:

>     24.910700	mosêtiyêhkwâmiw

**Comment by aarppe** [comment]
Duplicate of #197.
