### ISSUE TITLE
Linguistic breakdown popup (❓) should be keyboard-accessible

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#237]
The linguistic breakdown popup (the thing selectable by hovering over the (❓) button) should be accessible via the keyboard, namely by pressing the <kbd>Tab</kbd> key.

Here is the current (incorrect) behaviour:

![tabbing 2020-01-30 10_03_58](https://user-images.githubusercontent.com/2294397/73472185-dc8a1f80-4347-11ea-8a3a-2bbad7fb240d.gif)

**EXPECTED**: when I press <kbd>Tab</kbd>  when the search button 🔍 is selected, then the (❓) should be selected. Pressing <kbd>Shift</kbd> + <kbd>Tab</kbd> when "form of nipâw" is selected should move focus to (❓). I'm not sure whether it's a good idea to automatically popup the linguistic breakdown as soon as it's selected, or to let it act as a button, which can be activated by pressing <kbd>Space</kbd>.

---

@kobexamoh: this can probably be done in the same pull request that fixes #209.

**Comment by Madoshakalaka** [comment]
@eddieantonio very keyboard accessible now
