### ISSUE TITLE
The (❓) should be a ℹ️ icon instead

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#239]
> _That's not what I thought that would do._
>
>  — Dr. Jordan Lachler

Currently, to get the linguistic breakdown for a word, you have to hover or tap the blue (❓) icon next to the head. Could we make something more intuitive?

One alternative is to use the ℹ️icon (or the https://fontawesome.com/icons/info-circle?style=solid from fontawesome).

@kobexamoh, @atticusha  I'd like to hear your opinion on this!

**Comment by kobexamoh** [comment]
> That's not what I thought that would do.
> 
> — Dr. Jordan Lachler

So I see this quote from Dr Lachler – I didn't get a chance to ask him about this interaction. When he saw the icon, what did he think it would do? That might help with picking a different icon.

**Comment by atticusha** [comment]
> Ninja edit: sorry, the above is phrased better as two questions: what did he think pressing the icon would do? What was he _intending_ to do?
> 
> (Those help in nailing down a better/more intuitive icon!)

I believe that Mr. doctor professor director Jordan Lachler was under the impression that the icon would offer some sort of help menus or instruction set. I assumed the same.

I think the ℹ️ emoji would probably be better here. Alternatively we could use 👁 because I find it exceedingly uncomfortable.

**Comment by eddieantonio** [comment]
Lol I think https://fontawesome.com/icons/info-circle?style=solid is fine:

![info-icon](https://user-images.githubusercontent.com/2294397/73595843-01160100-44da-11ea-9300-7d0d5717666c.png)


And yes, I too think he thought the (❓) would give some sort of help text; instead it should show the linguistic breakdown ("more info")

**Comment by eddieantonio** [comment]
I changed the title, as this is now an improvement to be implemented! 👍

**Comment by kobexamoh** [comment]
Final update to this incoming – gonna be pinging y'all for a review in an hour or so 🤞

**Comment by Madoshakalaka** [comment]
isn't this fixed
