### ISSUE TITLE
Preverb breakdown needs to provide English definitions for preverbs

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#248]
Following up on #244, click on the preverb (e.g. nitawi-) in the linguistic breakdown

![image](https://user-images.githubusercontent.com/15003407/74075755-633a9e80-49d1-11ea-84e5-f065505af894.png)

... is not giving the English translation. Instead, clicking the link takes you to the front/landing page.

- [x] clicking on/hovering over preverb provided in linguistic analysis should present English definition (probably as a pop-up, rather than going to the preverb dictionary entry).

**Comment by Madoshakalaka** [comment]
@aarppe hey I know this is a feature to be implemented. `bug` tags makes me nervous.

**Comment by Madoshakalaka** [comment]
This is implemented by #251
