### ISSUE TITLE
Incorporate lemma rankings in our lexical database

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#254]
With #163 being completed with the calculation of weights available in: `~/giella/art/dicts/crk/Wolvengrey/W_aggr_corp_morph_log_freq.txt`, the next step is to read in and incorporate these weights in our lexical database.

Once this is done, the actual ranking of search results in #197 can proceed.

**Comment by aarppe** [comment]
The necessary ranking file `W_aggr_corp_morph_log_freq.txt` can be found on sapir in: `/data/texts/crk/dicts/itwewina/`

**Comment by aarppe** [comment]
Note that lemma rankings are now incorporated in the latest engcrk*.xml file, namely `engcrk_cw_md_200220.xml`, to be found in `sapir:/data/exps/itwewina/neahtta/dicts/`

**Comment by eddieantonio** [comment]
@aarppe Can I close this, and continue the conversation in #197?

**Comment by aarppe** [comment]
See duplicate comment: https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/197#issuecomment-598412707

**Comment by aarppe** [comment]
N.B. on the longer term (post-XML), I'd think that we want to import the rankings separately from a lemma/morpheme frequency list extracted from a corpus/dictionary.

**Comment by Madoshakalaka** [comment]
@aarppe thanks, I didn't realize the ranking is already incorporated in the new xml.

**Comment by aarppe** [comment]
No problem - though note that the ranks are only in the `engcrk*.xml` (not `crkeng*.xml`)

**Comment by aarppe** [comment]
Things look much better now, e.g. for 'eat' or 'speak':

![image](https://user-images.githubusercontent.com/15003407/76675987-de6d1280-6584-11ea-81d8-e15a4e5ff6b7.png)

![image](https://user-images.githubusercontent.com/15003407/76675995-eb8a0180-6584-11ea-8a4a-66bc23dcdffc.png)

And even here for 'see':

![image](https://user-images.githubusercontent.com/15003407/76676015-05c3df80-6585-11ea-85ce-988bfb4606ee.png)

The reason for _mahti_ ending up first is because that is the ranking that the corpus/dictionary-based script creates:

```
7.83899	mahti	mahti
9.06402	wâpamêw	wâp-/-am
9.39475	wâpiw	wâp-/-i
9.49894	wâpahtam	wâp-/-aht
```

We can fix that, of course - but I'm hoping that the importation of the corpus/dictionary-based weights is a straight-forward procedure.

**Comment by aarppe** [comment]
@Madoshakalaka Ain't this done already? Or do we need some tests to validate?

**Comment by Madoshakalaka** [comment]
@aarppe Yes this is done done. I'll close it now
