### ISSUE TITLE
Read into lexical database new version of crkeng_md_cw*.xml

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#255]
Since we now have processed the latest version of CW, both as dictionary content (`giella/art/dicts/crk/crkeng_cw_md_200208.xml`) and expanding the lexicon of the crk FST, this new content should be uploaded into our lexical database.

**Comment by aarppe** [comment]
For our reference, the code for creating the above file is the following (the second file should be kosher, in excluding all MD-only dictionary entries):

```
cat ~/Google\ Drive/CreeFST/Wolvengrey/Wolvengrey_crk2eng_200202_altlab.tsv | gawk -F"\t" 'BEGIN { while((getline < "/Users/arppe/giella/art/dicts/crk/crkeng_cw_md.xml")!=0) { print; if(match($0, "l pos.+>([^<]+)", s)!=0) lemma[s[1]]=s[1]; } } NR>=2 { if(!($1 in lemma)) { pos=""; if(match($3,"^N")!=0) pos="N"; if(match($3,"^V")!=0) pos="V"; if(match($3,"^I")!=0) pos="Ipc"; if(match($3,"^Pr")!=0) pos="Pron";  if($8!="") stem=$8; else stem=$7; if(index(stem," ;; ")!=0) stem=""; gsub("[\"]+","", $4); print "<e>"; print "   <lg>"; print "      <l pos=\""pos"\">"$1"</l>"; print " <lc>"$3"</lc>"; print "      <stem>"stem"</stem>"; print "   </lg>"; print "   <mg>"; print "   <tg xml:lang=\"eng\">"; print "      <t pos=\""pos"\" sources=\"CW\">"$4"</t>"; print "   </tg>"; print " </mg>"; print "</e>"; print "" } }' > /Users/arppe/giella/art/dicts/crk/crkeng_cw_md_200207.xml
```

```
cat /Users/arppe/giella/art/dicts/crk/crkeng_cw_md_200207.xml | gawk '{ if($0!="<e>") rec = rec sprintf("%s\n", $0); else { if(!(index(rec, "sources=\"MD\"")!=0 && index(rec, "sources=\"CW\"")==0)) printf "%s", rec; rec = sprintf("%s\n", $0); } } END { printf "%s", rec; }' > /Users/arppe/giella/art/dicts/crk/crkeng_cw_md_200208.xml
```

I didn't try to create the eng-to-crk direction, since that would need redoing the entire current XML file. Nevertheless, that should be reconstructible using the English words in the definitions as the indices. On the longer term, unless we have a manually crafted eng-to-crk source, I'm not convinced we need a separate file for that, rather than automatically generating eng-to-crk from crk-to-eng source.

**Comment by aarppe** [comment]
@Madoshakalaka Uploading the latest CW (+ MD) content would be a very useful improvement, as Arok's new source includes all reduplicative elements with translations (though coded as Preverbs).

I'm not sure we want to include those as preverbs proper in the FST, as that would allow any 
_Ca-/Câh_- combine with any stem, without matching the initial V/C of the stem, unless some changes are made. But we would want to be able to link in the English translations/definitions.

Using the latest file Should also ensure that only standardized MD content is shown, for now.

**Comment by aarppe** [comment]
The previous script had the fault of not disambiguating dictionary entries having exactly the same headword, and distinguishable only with the wordclass, or in some instances by the inflectional subcategory (there might be even case where the dictionary entries share wordclass and inflectional category, and differ only in terms of their definition, i.e. represent different senses of the same headword).

The revised script is as follows:

`cat ~/GDrive/CreeFST/Wolvengrey/Wolvengrey_crk2eng_200202_altlab.tsv | gawk 'BEGIN { FS="\n"; RS=""; while((getline < "/Users/arppe/giella/art/dicts/crk/crkeng_cw_md.xml")!=0) { def=0; for(i=1; i<=NF; i++) { if(match($i, "l pos=(.+)>([^<]+)", s)!=0) lex=s[2] if(match($i,"<lc>([^<]+)", s)!=0) infl=s[1]; if(index($i,"sources=\"CW\"")!=0 || index($i,"sources=\"MD CW\"")!=0) def=1; } if(def) { print; print ""; pos=infl; sub("-.+$","",pos); lemma[lex" "pos]=infl; } else print "MISSING: "ix > "/dev/null"; } # for(i in lemma) #   print i; FS="\t"; RS="\n"; } NR>=2 { gsub("ý","y"); infl=$3; sub("-.+$","",infl); ix=$1" "infl; if(!(ix in lemma)) { pos=""; ++nr; if(match($3,"^N")!=0) pos="N"; if(match($3,"^V")!=0) pos="V"; if(match($3,"^I")!=0) pos="Ipc"; if(match($3,"^Pr")!=0) pos="Pron"; if($8!="") stem=$8; else stem=$7; if(index(stem," ;; ")!=0) stem=""; gsub("[\"]+","", $4); print "<e>"; print "   <lg>"; print "      <l pos=\""pos"\">"$1"</l>"; print "      <lc>"$3"</lc>"; print "      <stem>"stem"</stem>"; print "   </lg>"; print "   <mg>"; print "   <tg xml:lang=\"eng\">"; print "      <t pos=\""pos"\" sources=\"CW\">"$4"</t>"; print "   </tg>"; print " </mg>"; print "</e>"; print "" } }' > ~/giella/art/dicts/crk/crkeng_cw_md_200218.xml`

There is still one, for the moment, less meaningful glitch - as we don't yet present the inflectional code, though this is information we'd certainly want to present. Since AEW has changed the inflectional subcategory coding, lexical entries from the older version of CW can have an old category coding, whereas those from the newest version of CW will use the new coding.

The end result can be found in: `~/giella/art/dicts/crk/crkeng_cw_md_200218.xml`

**Comment by aarppe** [comment]
Implemented some edits in the above code so that the necessary XML and dictionary source preambles and coda are included in the revised result.

**Comment by Madoshakalaka** [comment]
update: the new xml file is already used in the test database, will use it to build the production database soon.

**Comment by Madoshakalaka** [comment]
@aarppe `crkeng_cw_md_200218.xml` is being used in production right now.

**Comment by aarppe** [comment]
@Madoshakalaka How straight-forward is currently the uploading of new crk-to-eng (and eng-to-crk) XML files? I've made a few adjustments to add the MD entries for _wâpamêw_ and _mîcisow_ (and related words) to match with their CW counterparts, which had been missed out earlier.

**Comment by Madoshakalaka** [comment]
@aarppe I'd say it's very straigh-forward. It just takes 5 minutes. However it does require some setup. I'll make a seperate issue right now for this.
