### ISSUE TITLE
Update crk FST to match new version of crkeng_md_cw*.xml

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#256]
In conjunction with #255, we need to update our crk FST to the latest version matching with the new dictionary content.

**Comment by aarppe** [comment]
Ideally, we would have an semi-automatic pipeline for taking the latest version of the crk FST. But what we need to figure out for ourselves is whether the FST used by itwêwina is updated automatically when the FST is updated, or whether this needs to be initiated by a linguist/programmer.

Nevertheless, we would want a simple, single updating command for this, likely with some diagnostics to ensure that the functionalities of itwêwina won't break (-> new issue?).

**Comment by aarppe** [comment]
This update is really important, as the latest FST implements fixes to the affixation of nouns (only shorter _-is_ diminutives, unless otherwise indicated by corpus evidence, plural-only nouns) and verbs (correct suffixes for several inflectional subtypes of TA verbs with some frequent lemmas such as _itêw_ - e.g. `2Sg>3SgO` imperative should be _isi_ with an _-s-_). In addition, it adds several thousand new lemmas, so that their inflected forms can be recognized and generated in paradigms.

Thus, it should be undertaken at our earliest convenience.

**Comment by aarppe** [comment]
Examples of less desirable behavior that the new FST fixes:

1. Productive generation of double diminutives: search with _asikanis_ (or _askikanisis_), and receive both _asikanis_ and _asikanisis_. Since we have no corpus example of the longer form, only the shorter form, _asikanis_, should be recognized and presented.

![image](https://user-images.githubusercontent.com/15003407/74401271-fadb2b00-4ddd-11ea-9527-f13a6e7ad706.png)

2. Wrong imperative forms for TA verbs: iti is recognized and generated as the 2Sg>3SgO imperative for itêw, where isi would be the correct (there are also some other fixes to the VTA imperatives):

![image](https://user-images.githubusercontent.com/15003407/74401483-9c627c80-4dde-11ea-90fc-367ae506eb77.png)

**Comment by aarppe** [comment]
@eddieantonio As for getting multicharacter symbols out of HFST (or XFST), I recalled that there is an option that sort of does that, the `print-space` variable toggled with the `-X` option, cf.

```
echo "me-miyo-miyo-na-nah-nipacik" | hfst-lookup -q -X print-space src/analyser-gt-desc.hfst
m e - m i y o - m i y o - n a - n a h - n i p a c i k	  IC+    RdplW+         PV/miyo+        PV/miyo+           RdplW+ RdplS+     n i p â w +V +AI   +Cnj  +Prs     +3Pl  	0.000000
```
Of course, this appear to work only for `hfst-lookup `and not `hfst-optimized-lookup`.

**Comment by aarppe** [comment]
@eddieantonio General observation that might, or might not matter here, but can apply generally - have we remembered to invert the FOMA FST when converting from the HFST ones (or invert the original HFST FST)?

**Comment by Madoshakalaka** [comment]
@eddieantonio don't close this for now please, I don't think the production database is built with the newest fst. I'm working on it right now.

**Comment by Madoshakalaka** [comment]
@aarppe this should be achived now.

**Comment by aarppe** [comment]
Great!

I just did my routine checks with a few select Cree and English words. In this respect, where can I find the comprehensive set of search words (Cree or English) that I presume are tested before release?
