### ISSUE TITLE
Implement links from recordings to speakers (individually and collectively) from itwêwina

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#259]
[@aradu12 This is a duplicate cross-over from https://github.com/UAlbertaALTLab/itwewina/issues/111]

- [x] links to individual speakers from individual recordings spoken by them
- [x] link to collective speaker/project page either as a speaker tab and/or from the About page

1. clicking speaker name in conjunction with the recording snippet in itwêwina either takes one to that speaker's picture and bio page (so simply a link is required) - if this is created within the validation app, then itwêwina just needs to treat it properly.

2. Clicking a 'Speakers' tab, or clicking a link on the itwêwina About page will follow a link to wherever under the validation app we end up placing info on the speakers as a whole, and about the project, and that page will then have further links to get more info on the individual speakers.

So, this is connected with making the speaker info available under the validation app, i.e. issue https://github.com/UAlbertaALTLab/recording-validation-interface/issues/35 in that project.

Temporary solution available as under the interim project webpage:

`http://altlab.ualberta.ca/maskwacis/Speakers/speakers.html`

This is located on sapir in:

`/var/www/maskwacis/Speakers
`
... under the general project page:

`/var/www/maskwacis`

The above page (for speakers) presents the pictures (with names) that we have managed to take of the speakers. Clicking the individual speaker thumbnail produces a full-size picture. Later on, this full-size picture should have a Cree and English bio text to the right (or alternatively implemented through the validation app).

-----

I've now revised the implementation of each speaker picture so that for each Cree speaker we have an `*.html` file, the name of which prefixed with their speaker code, e.g. `MAR.html` for MJL. These *.html files contain some CSS styling and other formatting that provides the full name in the `<title>` element, setting black as the background, and window-size-dependent resizing of the image. This solution allows for the addition of the Cree and English speaker bio texts, as e.g. a pane on the right-hand side, once we are able to collect that information.

All the above mentioned `XXX.html` files are to be found through the following URL:

http://altlab.ualberta.ca/maskwacis/Speakers/

For instance, for Cree speaker MJL the correspoding speaker bio/picture `*.html `file is as follows:

http://altlab.ualberta.ca/maskwacis/Speakers/MAR.html

I've also used ImageMagick/convert to adjust the file size as approx. 256k, with all images being in JPG format and named as `*.jpg`. This size appears to retain sufficient quality, but could be potentially upped to 512k, if we come to that conclusion later.

Therefore, linking the speaker info in conjunction with the audio snippets with the speaker-specific webpages (now with just their name and picture) should now be straight-forward to implement through the validation app, making use of the speaker code.

**Comment by aarppe** [comment]
@kobexamoh This would be for you, eventually.

**Comment by kobexamoh** [comment]
As of a few minutes ago this has been addressed by #441 and merged into master. I _think_ we can mark this as closed/resolved, but once live I'm sure there may be feedback or suggestions.

**Comment by eddieantonio** [comment]
I think this one is done! Check out <https://sapir.artsrn.ualberta.ca/cree-dictionary/about> for the link to all the speakers, and an individual word <https://sapir.artsrn.ualberta.ca/cree-dictionary/word/mistik/?full_lc=NA-3> for links to all the speakers!

@aarppe, any follow ups to this implementation can be addressed in an new issue.

**Comment by aarppe** [comment]
For whatever reason, the links are not working on my end, e.g.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/15003407/84708360-95c74b80-af1d-11ea-96d6-2bba8c7b048a.png">

The files and directories are in place in sapir, and the permissions haven't changed, so I'm wondering if this is a local matter.

**Comment by kobexamoh** [comment]
@aarppe that looks like Firefox, right? I'll test it on my device as well and see what might be occurring – please hold!

**Comment by aarppe** [comment]
@kobexamoh Yeah, it's Firefox.

On Firefox, I can hear the recordings but not access the links. In Safari, I can access the links, but not hear the recordings. Weird, and beats me.

**Comment by eddieantonio** [comment]
> @kobexamoh @eddieantonio We can have a separate issue for improving the UI. But for whatever reason, the links are not working on my end, e.g.
> 
> <img alt="image" width="567" src="https://user-images.githubusercontent.com/15003407/84708360-95c74b80-af1d-11ea-96d6-2bba8c7b048a.png">
> 
> The files and directories are in place in sapir, and the permissions haven't changed, so I'm wondering if this is a local matter?

Could you please include the URL in your Firefox browser for the link that was not found? I could not replicated this in my version of Firefox.

<img width="938" alt="Screen Shot 2020-06-15 at 4 30 08 PM" src="https://user-images.githubusercontent.com/2294397/84712322-80561f80-af25-11ea-83b3-09f203cc301c.png">

**Comment by aarppe** [comment]
Here's the link at my end:

https://altlab.ualberta.ca/maskwacis/Speakers/MAR.html

What I'm noticing is that at my end the lock symbol is not crossed with a red line, in contrast to your screenshot:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/15003407/84712544-1be79000-af26-11ea-9cc6-8fcd7dc8a146.png">
