### ISSUE TITLE
Linguistic breakdown popup should not overlap icons ℹ️

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#268]
And it shoudn't. This can probably be fixed with a `z-index`.

@kobexamoh might fix this in the process of fixing #266.

**Comment by Madoshakalaka** [comment]
yep try z-index

**Comment by kobexamoh** [comment]
Was this knocked off already at some point? I went to look into it a while back and made a note that (for me) it didn't seem like the breakdowns were overlapping icons.

Did a previous PR from someone take care of this issue or did I totally misread it while under the weather?

**Comment by eddieantonio** [comment]
I can still replicate this in Firefox:

![Screen Shot 2020-03-13 at 9 33 01 AM](https://user-images.githubusercontent.com/2294397/76635833-ab3b6c80-650d-11ea-9cb6-ba60c65e30d3.png)

**Comment by eddieantonio** [comment]
Fixed in #337.
