### ISSUE TITLE
Use HFST to generate paradigms, if FOMA flookup / python-fst-lookup don't work

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#269]
@Madoshakalaka Upon waiting for the resolution of #256, if FOMA flookup / python-fst-lookup don't work, use HFST for generating the inflected wordforms in the paradigms. That way, at least the paradigms will be correct, even if the recognition might not exactly work yet.

**Comment by aarppe** [comment]
I've consulted Miikka on this, and his first diagnosis is that there might be an error in the HFST-to-FOMA conversion, rather than the original FST. He's looking into this, having received the original FSTs from me.

**Comment by eddieantonio** [comment]
@Madoshakalaka, could you take a look at this?

**Comment by eddieantonio** [comment]
The latest HFSTOL is merged into master. @Madoshakalaka, please merge master and use this to update the new database :D

**Comment by Madoshakalaka** [comment]
:D
