### ISSUE TITLE
Cannot find âyiman in new dictionary contents

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#274]
When using a newly build test DB, I can't find "âyiman" or "ayiman"

<img width="612" alt="search for âyiman" src="https://user-images.githubusercontent.com/2294397/74686016-6ed65400-518d-11ea-8225-00b92ed34acc.png">

But it's in the test database!

```
SQLite version 3.28.0 2019-04-15 14:49:49
Enter ".help" for usage hints.
sqlite> SELECT * FROM API_wordform WHERE text='âyiman';
7|âyiman|NI-1|âyiman+N+I|1|1|N|7
8|âyiman|VII-n|âyiman+V+II|1|1|V|8
```

The response is... empty?

This is causing errors in #272.

**Comment by eddieantonio** [comment]
I wonder if this is due to a mismatch between the FST and the dictionary contents 🤔🤔🤔

**Comment by eddieantonio** [comment]
I tried both the new and the old FST and they have the same lemma/POS

```python
# within CreeDictionary/res/fst:
>>> fst = FST.from_file('crk-descriptive-analyzer.fomabin')
[('âyiman', '+N', '+I', '+Sg'), ('âyiman', '+V', '+II', '+Ind', '+Prs', '+3Sg')]
>>> list(fst.analyze('ayiman'))
[('âyiman', '+N', '+I', '+Sg'), ('âyiman', '+V', '+II', '+Ind', '+Prs', '+3Sg')]
```

The generated dictionary content looks like this:

```xml
<?xml version="1.0"?>
<r>
	<e>
		<lg>
			<l pos="V">âyiman</l>
			<lc>VII-n</lc>
			<stem>âyiman-</stem>
		</lg>
	</e>
	<e>
		<lg>
			<l pos="N">âyiman</l>
			<lc>NI-1</lc>
			<stem>âyiman-</stem>
		</lg>
	</e>
</r>
```

Although I edited it for brevity, there's actually no `<mg>` or `<tg>` tags??!???!??!?! Is this an issue in the test data generator?

**Comment by eddieantonio** [comment]
**UPDATE**: the reason that there is no definition for _âyiman_ in the dictionary is because the dictionary does not contain a definition for _âyiman_!

Did something go wrong in the creation of `crkeng.xml`?

---

SVN r187348:

```sh
$ sha384sum crkeng_cw_md_200208.xml
b0e56e7f31b5a9b280114659a6575f7f4617726bdf25185ba5763a6bc1d8feaf27e508a26119f289ac4323179bf0c89c  crkeng_cw_md_200208.xml
$ grep --context=10 âyiman crkeng_cw_md_200208.xml
   </lg>
   <mg>
   <tg xml:lang="eng">
       <t pos="V" sources="CW">it is expensive, costly (spiritually)</t>
   </tg>
   </mg>
</e>

<e>
   <lg>
      <l pos="N">âyiman</l>
      <lc>NI-1</lc>
--
      <lc>NI-1</lc>
      <stem>âyiman-</stem>
   </lg>
</e>

<e>
   <lg>
--
   </lg>
</e>

<e>
   <lg>
      <l pos="V">âyiman</l>
      <lc>VII-n</lc>
--
      <lc>VII-n</lc>
      <stem>âyiman-</stem>
   </lg>
</e>

<e>
   <lg>
--
   </lg>
</e>

<e>
   <lg>
      <l pos="Ipc">âyimanohk</l>
      <lc>IPC</lc>
      <stem></stem>
   </lg>
   <mg>
   <tg xml:lang="eng">
       <t pos="Ipc" sources="CW">in a difficult place</t>
   </tg>
   </mg>
</e>

--
--
   <tg xml:lang="eng">
       <t pos="Ipc" sources="CW">[grammatical preverb; defines a changed conjunct clause; often a relative clause, i.e. who, which]</t>
   </tg>
   </mg>
</e>

<e>
   <lg>
      <l pos="N">kâ-âyimahk</l>
      <lc>INM</lc>
      <stem>âyiman- VII-n</stem>
   </lg>
   <mg>
   <tg xml:lang="eng">
       <t pos="N" sources="CW">difficult times; the Depression</t>
   </tg>
   </mg>
</e>
```

@aarpe, could you please investigate and regenerate the files?

**Comment by aarppe** [comment]
Yes, I can see that the basic NI and VII dictionary entries for _âyiman_ do have the lemma and inflectional category, but do not have a translation for whatever reason. That seems to be a problem already in the previous version of crk_cw_md.xml from a year back.

So, needs investigating.

**Comment by aarppe** [comment]
This should now be fixed in: `crkeng_cw_md_200218.xml` which can be found on `sapir` in: `/data/texts/crk/dicts/itwewina/`

**Comment by eddieantonio** [comment]
Confirmed. This issue is fixed!

**Comment by eddieantonio** [comment]
https://altlab.ualberta.ca/itwewina/crk/eng/?lookup=ayiman

So... the new XML is not only incorrectly formatted, but is also missing `<source>` information. This issue is still open :/

**Comment by eddieantonio** [comment]
@aarppe make sure you take care to both generate the obligatory XML nonsense, i.e.,

```xml
<?xml version="1.0" encoding="UTF-8"?>
<r>

</r>
```

As well as keeping the source information:

```xml
<!-- The dictionary sources -->
   <source id="CW">
      <title>Cree : Words / nēhiyawēwin : itwēwina</title>
   </source>
   <source id="MD">
      <title>Maskwacîs Cree Dictionary</title>
   </source>
```

I will **not** update dictionary contents unless all of these steps are done properly.

**Comment by eddieantonio** [comment]
I manually added this to `sapir:/data/exps/itwewina/neahtta/dicts/crkeng-20200218.xml`, and thus this issue can be closed yet again.

**Comment by aarppe** [comment]
My apologies for overlooking the XML and dictionary source preambles - I seem not to have been at my most careful when reviewing the revised XML, as this stuff was in the previous attempt, with its own issues, but got lost when parsing the records in a less gawkian way.

Anyhow, the fixes needed were straight-forward and now revised in the script in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/255#issuecomment-588062041.

**Comment by aarppe** [comment]
@eddieantonio will these end up on the new itwêwina as well?

Also, does the import script create an English-to-Cree index of the `crkeng*.xml` automatically (hopefully so), or does one need to create that `engcrk*.xml` as well (hopefully not).

Currently, a good test word for the new AEW content is _acâwêsiw_ (Verb, VAI-1) 's/he buys a little (of it), s/he buys some (of it)CW'.

**Comment by eddieantonio** [comment]
> @eddieantonio will these end up on the new itwêwina as well?

Yes: I'll do that tomorrow.

> Also, does the import script create an English-to-Cree index of the `crkeng*.xml` automatically (hopefully so), or does one need to create that `engcrk*.xml` as well (hopefully not).

No: we have no implementation of this right now. Could you please make a new issue?

> Currently, a good test word for the new AEW content is _acâwêsiw_ (Verb, VAI-1) 's/he buys a little (of it), s/he buys some (of it)CW'.

Thanks! I'll make sure to test this tomorrow!

**Comment by aarppe** [comment]
We now have issue #285 for creating engcrk.xml.

For old NDS-based itwêwina purposes, I couldn't resist the temptation to create that XML file, just to make sure that the content is what I believe it should be. The end result is in: `sapir:/data/exps/itwewina/neahtta/dicts/engcrk_cw_md_200220.xml`

Ideally, for the new itwêwina, we need not have an explicit English-to-Cree dictionary until one has been created manually, to supplant an automatically created one.
