### ISSUE TITLE
Basic mixed paradigm

### ISSUE THREAD

**Issue by katieschmirler** [UAlbertaALTLab/cree-intelligent-dictionary#277]
Should show 3 > 1,2 rather than 3', 3 would be much more common and thus the logical choice

**Comment by Madoshakalaka** [comment]
@katieschmirler congrats you are officially a software developer!

**Comment by katieschmirler** [comment]
https://giphy.com/gifs/animation-party-rainbow-l2JhIJb4MP9BZgFRm

**Comment by aarppe** [comment]
Yes, we should add 3Sg > 2Sg, rather than the further obviative cases, though I'd keep 3Sg > 4 and 4 > 3Sg.

**Comment by aarppe** [comment]
@eddieantonio I fixed these in VTA paradigm source CSV file: CreeDictionary/res/layouts/verb-ta-basic.layout.csv - I hope that is the right source file, but how does this get incorporated in the public version?

**Comment by eddieantonio** [comment]
> @eddieantonio I fixed these in VTA paradigm source CSV file: CreeDictionary/res/layouts/verb-ta-basic.layout.csv - I hope that is the right source file, but how does this get incorporated in the public version?

We have to use the `update-layouts` command. I'll check it out.

**Comment by eddieantonio** [comment]
In the meantime @aarppe, could you please address UAlbertaALTLab/plains-cree-fsts#7? I tried to lookup one of these forms this morning and it failed :(
