### ISSUE TITLE
Something is very wrong with the database importer

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#286]
I learned the hard way that if something fails, it _will_ delete the production DB.

I'm doing work in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/tree/emergency-database-manager

@Madoshakalaka, please help at your earliest convenience.

**Comment by Madoshakalaka** [comment]
yep, I can help if it needs refactoring or better documentation
