### ISSUE TITLE
Create guidelines document that lists genuine example cases from our dictionary

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#291]
When designing user interface and functionalities, use only dictionary entries available in our dictionary sources, and pertaining to Cree morphology.

If we do not, we might end up designing functionality or appearance for which we have no or only few concrete dictionary data which could make use of such features.

**Comment by eddieantonio** [comment]
Hey Antti! Is this referring to any specific instances in our codebase? If so, could you please enumerate them? In other words, could you please explain how this is a "feature"?

I'm asking because the wording makes this seem like more of a **guideline** than an _issue_. An issue, in the GitHub sense has a clear termination — e.g., a condition when the issue can be closed. We, the developers, can then use the open issues to gauge what to work on, and resolve existing open issues. If this particular open issue is actually a perpetual guideline, then it _defeats the purpose of having an issue tracker!_

**Comment by aarppe** [comment]
I think some of the fuzziness we have in the implementation of functionalities is using (Cree word) examples that are not apparent in our dictionary sources, e.g. _niskak_ (plural of _niska_ and a form of _nîskâw_) is not an inflected form in either CW or MD. However, we do have genuine examples, e.g. _nicihciy_, _nîminâniwan_, and _sîsîpis_.

At the very least, going forward we should only use example words from our sources. If you don't know an appropriate one, don't make up one but consult the linguists.

Also, we could consider revising the mock-ups to use genuine rather than made-up Cree word examples. That would be a proper issue, but I'm not sure if it's worth doing, in particular if we need to ask the UI designer to do that.

But if not an issue, where does one put guidelines?

**Comment by eddieantonio** [comment]
@aarppe I would put guidelines in a markdown document within `docs/`.

Could you please **create a pull request** of a new document, outlining some "approved" examples to use in our presentation?

**Comment by eddieantonio** [comment]
I've changed the issue title, because this makes it an actionable item with a clear resolution! 🎉

**Comment by aarppe** [comment]
These are sprinkled among a bunch of previous issues, such as #209, #227, and #228. Those should be using verified examples from our Dictionary sources.

**Comment by eddieantonio** [comment]
Okay: could you please create the markdown file named something like`docs/guidelines.md` or `docs/example-cases.md`?

**Comment by aarppe** [comment]
We now have a first version for `docs/example-cases.md` in:

`https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/master/docs/example-cases.md`

**Comment by eddieantonio** [comment]
Resolved as of 37326f59765356ec195723280424d0cf26d2cceb

**Comment by aarppe** [comment]
Note that the examples in `example-cases.md` present genuine cases from our dictionary sources that can be used to test various functionalities. But those examples (the current content) are not necessarily the most frequent usage cases that one would want to use as the first introductory examples for a user of _itwêwina_. I might yet add such exemplary examples.
