### ISSUE TITLE
Improve layout of word form search results

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#296]
As a improvement of #205,  improve visual organization of standardized forms, lemmas, definitions, linguistic breakdowns, etc., as detailed in #224 and #232.

**Comment by eddieantonio** [comment]
@kobexamoh, this one is for you, and is an extension of your current work.

**Comment by eddieantonio** [comment]
Not enough detail in this issue, plus most of this has been fixed in #462; @aarppe, please reopen if you think otherwise. The linguistic breakdown is better documented in #266.

**Comment by aarppe** [comment]
This has been subsumed by other issues, which have now been addressed there.
