### ISSUE TITLE
Add Cree translation to search box text

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#297]
The following is the Cree translation for 'Search for a Cree or English word':

_nitona nêhiyaw-itwêwin ahpô âkayâsîwi-itwêwin_

We should add that to the greyed text appear in the search box, after the English instruction.

**Comment by eddieantonio** [comment]
@aarppe, could you please provide a mockup of what this would look like? I'm having difficulty visualizing exactly how this will work.

**Comment by aarppe** [comment]
[Edited the Cree wordings after some second thoughts]
So, in addition to the English instruction 'Search in Cree or in English' in grey in the search box, in:

![image](https://user-images.githubusercontent.com/15003407/75184419-95523d00-5701-11ea-9c3f-4b5cf9fb5353.png)

... I would add after that 'nitona nêhiyaw-itwêwin ahpô âkayâsîwi-itwêwin', so that the box would rather say:

'Search in Cree or in English / nitona nêhiyaw-itwêwin ahpô âkayâsîwi-itwêwin'

Maybe cramming all this in one and the same search box is squeezing in too much, or maybe this is something that could change with the language choice. So this really isn't the highest priority, but something we'd want to consider eventually.

**Comment by eddieantonio** [comment]
This is part of providing Cree as an interface language. We need to find a translator for that first, and setup the i18n infrastructure for this first!

I'm closing in favour of #97.

**Comment by aarppe** [comment]
Ok, I can agree.

The previous time we used Jean Okimâsis (and Arok) for that, and both are participants on our Partnership application. I could imagine that this might also benefit from more people and a dedicated terminology workshop, maybe in one or more people coming up with initial proposals which could be discussed before a final conclusion would be made. And yes, we should set up a proper technical infrastructure for maintaining the various linguistic localizations (similar to what the Giella folks had done for NDS).
