### ISSUE TITLE
Expanded (CW) preverb definitions are missing

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#305]
Something has happened to expanding preverbs, so that the preverbs themselves and their English definitions are not shown:

![image](https://user-images.githubusercontent.com/15003407/75388857-df265900-58a2-11ea-8bc2-a0b33df22184.png)

I've indicated that if merging MD and CW preverbs is causing problems, then we might leave out the MD preverbs for now. But I haven't understood/intended that to mean that we'd leave (CW) preverbs out entirely.

**Comment by aarppe** [comment]
Or then they aren't, as per snapshot right now at 20:27 on Thu 27.2.2020:

![image](https://user-images.githubusercontent.com/15003407/75509191-e4b79800-59a3-11ea-8279-07c6eab7499c.png)

**Comment by eddieantonio** [comment]
I believe this was fixed yesterday in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/commit/e7bbf16703073c1561f2c0b4e9d135d0d9fee156#diff-600a72a544ee5ba3263ad88672409250
