### ISSUE TITLE
Use hfst-(optimized-)lookup to analyze Cree word forms, if python lookup doesn't work

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#307]
Use `hfst-lookup` for analyzing Cree word forms, as an interim solution if it turns out that the python lookup doesn't work and while that is being fixed.

**Comment by eddieantonio** [comment]
Hey @Madoshakalaka, could you handle this up next with the interim `hfstol` module?

**Comment by Madoshakalaka** [comment]
@eddieantonio of course

**Comment by aarppe** [comment]
@Madoshakalaka Are we using this HFST (or hfstol) implementation for now, for word form recognition? If so, then this can be closed along with #256.

**Comment by Madoshakalaka** [comment]
@aarppe Yes, we are currently using the newest `.hftstol` files
