### ISSUE TITLE
Incorrect forms presented (and recognized) by current FST

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#340]
As a motivation for #256, here are the examples of less desirable behavior of the current FST that the new FST fixes, and why we need to implement #269 and #307:

1. Productive generation of double diminutives: search with _asikanis_ (or _askikanisis_), and receive both _asikanis_ and _asikanisis_. Since we have no corpus example of the longer form, only the shorter form, _asikanis_, should be recognized and presented.

![image](https://user-images.githubusercontent.com/15003407/74403872-fca8ec80-4de5-11ea-8d5b-87ae8ac22985.png)

2. Wrong imperative forms for TA verbs: _iti_ is recognized and generated as the `2Sg>3SgO` imperative for _itêw_, where _isi_ would be the correct (there are also some other fixes to the VTA imperatives):

![image](https://user-images.githubusercontent.com/15003407/74403727-8efcc080-4de5-11ea-8621-019bb6570560.png)

_Originally posted by @aarppe in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/256#issuecomment-585544560_

**Comment by aarppe** [comment]
@Madoshakalaka In the above, I'm making explicit why we need to be able to use the new FST (even with HFST) for both recognizing search strings as well as generating the standardized forms of those strings.

**Comment by eddieantonio** [comment]
This is not a new issue. Please add this a comment to #256.
