### ISSUE TITLE
Make the feedback/email info more easily discoverable

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#341]
Now, the suggestion for feedback or suggestions is at the very bottom of the `About` page, which makes it difficult to easily discover.

![image](https://user-images.githubusercontent.com/15003407/76676226-f5146900-6586-11ea-8441-6872d70fdcf9.png)

Maybe we could mention `feedback` as its own subpage, with the `altlab@ualberta.ca` email there?

**Comment by aarppe** [comment]
Looks fine. I suppose we could want to use the longer `altlab+itwewina@ualberta.ca` for emailing, but that would turn relatively long, in particular on the mobile screen. What if we show just the shorter email on the 'Contact Us' page, but clicking that visual email produces the longer email for one's email application?

**Comment by eddieantonio** [comment]
Good idea. I'll implement it soon
