### ISSUE TITLE
Many English proper names not resulting in a Cree match

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#343]
Many English proper names, e.g. Cree, Edmonton, Calgary, Canada, Canadian, etc. do not result in a matching Cree word - even though they do appear to be in the `engcrk.xml` source, cf.
```

...
<e>
   <lg xml:lang="eng">
      <l pos="English">cree</l>
   </lg>
   <mg>
   <tg xml:lang="crk">
      <trunc sources="CW">Starblanket; literally: One who has Stars as a Blanket; name of Cree chief, signatory to Treaty 4</trunc>
      <t rank="124" pos="N">acâhkosa kâ-otakohpit</t>
   </tg>
   </mg>
...
```

**Comment by eddieantonio** [comment]
I noticed this too :(

**Comment by Madoshakalaka** [comment]
This is caused by missing English Search Capitalization Relaxation and is fixed now

**Comment by Madoshakalaka** [comment]
@eddieantonio sorry I was meant to submit a pr. But I accidentally pushed two commits to master. 

Commit b583cbc8de00c9e835f9e8dd4d91d935a18fc27d adds capitalization
Commit 5c8cbbe83d9965e0ad5ed37d9628b365987a6bfa adds regression tests for it

**Comment by eddieantonio** [comment]
@Madoshakalaka, thanks for linking the commits. Looks good!

**Comment by aarppe** [comment]
Re: Capitalization for English (and for Cree). Generally, I'd presume that we match searches irrespective of whether a search string is correctly or incorrectly capitalized. For Cree, the descriptive Giella FST incorporates a REGEXP for doing that, but I don't think we included that for the abbreviated FST we do ourselves. Nevertheless, for Cree content, that is by standard always in lowercase (and that applies to CW heads as well as standardized MD heads), so whatever search string that is Cree can be turned into lower case. 

In the latest engcrk*.xml, I've turned the English search terms all into lowercase (as you can see in the example above for _Cree_ -> _cree_). In some rare cases that could result in ambiguity in matches, but then we'd just present the two (or more) results.

**Comment by eddieantonio** [comment]
I am increasingly convinced that the `engcrk.xml` is no longer the correct solution. We'll index the definitions with a tf.idf-based search with corpus weighting.

**Comment by aarppe** [comment]
Yes, `engcrk.xml` shouldn't be the correct solution, as it is generated from `crkeng.xml` and corpus/dictionary weights, with the added level of lemmatization of the words in the English definitions (supplemented to the English search indices).

But I'm presuming that on the longer term we won't be using anything like `engcrk.xml` at all, unless we get a genuine English-to-Cree dictionary source - but rather accessing the words in the English definitions as found in the next dictionary database. Nevertheless, I'd still include as indices also the lemmas corresponding to the wordforms in those definitions.
