### ISSUE TITLE
Certain English words not getting all expected Cree matches

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#344]
Searching for _bear_, one gets many matches but not _maskwa_.

**Comment by eddieantonio** [comment]
Currently _maskwa_ shows up: https://itwewina.altlab.app/search?q=bear however, I feel like it should be ranked as the first one. c.f., #786 

See also the survey results:

https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/tree/main/src/CreeDictionary/search_quality/survey_results
