### ISSUE TITLE
Present multiple recordings from multiple speakers

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#347]
Now that we have rudimentary inclusion of recordings, we would want to expand that to include all recordings from multiple speakers relevant to a particular dictionary entry. The mockup that I have for this is from September 2019.

![image](https://user-images.githubusercontent.com/15003407/76694065-aa045f80-6633-11ea-80a0-2af26f5f1f49.png)

This likely requires a number of subtasks, for which here are a few notes:

1. It seems like a good idea to present for a lemma recordings of any wordforms in that lemma's paradigm (or at least a representative subsample).

![image](https://user-images.githubusercontent.com/15003407/76694094-2434e400-6634-11ea-8936-4e9a449d4511.png)

2. It has also seemed a good idea (for now) to present all recordings, even by the same speaker, since that exhibits the various types of variation in pronouncing. Once we have fully implemented a quality assessment of individual recordings (which is under way as part of the annotation project), we can rule out bad recordings (mainly having intervening other sounds to a disturbing extent).

3. If we have not been able to standardize the orthography of the wordforms, then we can in the first instance just show the names of the speakers, without the transcription (for now, even for related word forms).

4. We would want to be able to link to the speaker pages from the speaker names within _itwêwina_.

**Comment by aarppe** [comment]
@kobexamoh This is the issue that I'd focus on, once you get the ones you're working on finished, since being able to show more recordings (since we already have them) would be an important feature for the Maskwacîs Cree community where the recordings were done - they'd want to see the fruits of their labor. This will likely require some work on the backend as well. (And I'd say that I'd do this even before the paradigm pop-outs.)

**Comment by aarppe** [comment]
This issue is linked with #259, but this issue is the more important one.

**Comment by eddieantonio** [comment]
@kobexamoh, when implementing this do _not_ show the matched wordform from the query; just show the speaker and their dialect.

e.g., instead of `tipiskam (Louise Wildcat, Maskwacîs)` just show `Louise Wildcat, Maskwacîs`.

The reason: the recordings database doesn't always spell things correctly; see #149.

**Comment by aarppe** [comment]
@kobexamoh Yes, until we have standardized the orthography of the annotated speech snippets, we do not want to show those wordforms - but we do want such an implementation that switching to showing those wordforms is straight-forward, when we're ready for it.

**Comment by aarppe** [comment]
@kobexamoh To reinforce what was said in our meeting today, this issue, as well as two other of the UI issues concerning the recordings can be committed individually, in the spirit of incremental progress. In this way, we can get new versions steadily out there, and test them individually as to how well they work, rather than packing all into a single big commit. So, I'm looking forward to the implementation of this!

**Comment by kobexamoh** [comment]
Apologies @aarppe! I thought I had sent the commit on Friday evening before bed – I've just pushed the code and am pulling it all together for a PR now 👍

**Comment by eddieantonio** [comment]
Fixed in #408
