### ISSUE TITLE
Relabel also feature sequences

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#348]
Alongside relabeling individual features, sometimes we would like to enable the relabeling of feature sequences. Sometimes the relabeling makes most sense for a feature sequence/multiple rather than individual features - and sometimes treated a feature sequence as one would be desired for one type of relabelings but not for others.

Examples are:
- Actor + Goal pairs for TA verbs, e.g.: `1Sg+2SgO`-> `I -> you (one)` 
- Future Conditional: `Fut+Cond` -> `When something is happening`
- Future Intentional: `Fut+Int` -> `Someone wants something to happen`
- Future Definite: `Fut+Def `-> `Something will [certainly] happen`
- Dependent nouns (perhaps): `N+A+D` -> `like: nôhkom, nîpit`

We'd want to relabel feature sequences before individual features. The `crk.altlabel` file already has some of these feature sequence relabelings.

**Comment by aarppe** [comment]
@kobexamoh So this would be eventually for you to implement (depending on the order you're progressing through the various UI issues).

**Comment by aarppe** [comment]
Moving a comment from #401 here, where it better belongs:
> @kobexamoh @eddieantonio Implementing the multi-feature relabeling issue #348 would be crucial here in making the linguistic analysis information more easily understandable. It would make sense to combine the specific wordclass info, i.e. `II`, `AI`, `TI`, `TA` for verbs and `A`, `I`, `A+D`, `I+D` for nouns, with the general wordclass feature (`V`, `N`, `Ipc`).
> 
> So, one would prefer the following relabeling scheme for an AI verb such as _pîsin_:
> 
> `+V+AI` -> `Action word — like: mîcisow`
> `+Ind` -> `ni-/ki- word`
> `+Prs` -> `something is happening now`
> `+3Sg` -> `s/he`
> 
> Even more important this grouping is for TA verbs such as _wâpamât_ -> wâpamêw+V+TA+Cnj+3Sg+4Sg/PlO:
> 
> `+V+TA` -> `Action word — like: wîcihêw`
> `+Cnj` -> `ê-/kâ- word`
> `+Prs` -> `something is happening now`
> `+3Sg+4Sg/Pl` -> `s/he -> him/her/them`
> 
> ... or imperative forms, e.g. _wâpam_ -> wâpamêw+V+TA+Imp+Imm+2Sg+3SgO:
> 
> `+V+TA` -> `Action word -- like: wîcihêw`
> `+Imp+Imm` -> `Command -- immediate`
> `+Prs` -> `something is happening now`
> `+2Sg+3Sg0` -> `you -> him/her`
> 
> For nouns, the following would be the preferred formatting:
> 
> _niwâwima_ 'my eggs' ->` wâwi+N+I+Px1Sg+Pl`:
> `+N+I` -> `Naming word — like: cimân, wâwi`
> `+Px1Sg` -> `my`
> `+Pl` -> `many`
> 
> `kôhkoma` 'my further grandmothers' -> nôhkom+N+A+D+Px2Sg+Obv
> `+N+A+D` -> `Naming word — like: nôhkom, mitâs`
> `+Px2Sg` -> `your (one)`
> `+Obv` -> `further`
> 
> Most of this relabeling is already implemented in `crk.altlabel.tsv`, but I can check if there's anything missing.

**Comment by eddieantonio** [comment]
Hey @aarppe! This is implemented in #453 — I'm waiting for that to be reviewed. In the meantime, there _are_ discrepancies and mistakes in `crk.altlabel.tsv`; could you double check that file and make sure all the labels look right? I think the label for `3Sg+4Sg/PlO` needs some work, for example.

**Comment by aarppe** [comment]
@eddieantonio Looked at `crk.altllabel.tsv`. In the plain English relabeling, I've indicated obviative through combining singular and plural pronouns, so `s/he/them`, and only added `further` for the further obviative, i.e. `5Sg/Pl[O]`.
