### ISSUE TITLE
Update dictionary DB with latest crk-to-eng and eng-to-crk source

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#354]
Upload the crk dictionary database with the revised crk-to-eng and eng-to-crk source (addition of some MD entries and revised ranks/weights) created in  #345.

**Comment by aarppe** [comment]
@Madoshakalaka I created this as a new issue so that we could incorporate the essential content of the minutely updated XML sources from #345.

**Comment by aarppe** [comment]
@Madoshakalaka Ok, but watch out that itwêwina doesn't break and we won't get again some preverb-type issues, as we have a meeting with MESC tomorrow where we're going to touch upon itwêwina.

**Comment by Madoshakalaka** [comment]
@aarppe I'm wrting a regression test on the preverb issue right now, to ensure it won't happen again. Also I'll avoid merging big changes today, so that itwewina is as stable as possible

**Comment by Madoshakalaka** [comment]
done, updated
