### ISSUE TITLE
Preverb translations have mixed up

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#355]
Using our example wordform _ê-kî-nitawi-kâh-kîmôci-kotiskâwêyâhk_, all the preverbs get weird and incorrect definitions/translations, cf.

![image](https://user-images.githubusercontent.com/15003407/77111626-48564380-69ed-11ea-9bab-ee00e0a7f792.png)

These all appear to have multiple definitions, when there should be only one. And among the multiple translations, one appears to be correct, but the others entirely incorrect. Those incorrect definitions do not come out of the XML source, I've just checked.

![image](https://user-images.githubusercontent.com/15003407/77111656-54da9c00-69ed-11ea-9bc0-742cfae52adb.png)

![image](https://user-images.githubusercontent.com/15003407/77111686-6328b800-69ed-11ea-9e0c-c88b8aa4bdbb.png)

![image](https://user-images.githubusercontent.com/15003407/77111762-7e93c300-69ed-11ea-96bc-496c0a855657.png)

![image](https://user-images.githubusercontent.com/15003407/77111732-73409780-69ed-11ea-9526-9aabfb831bdc.png)

**Comment by aarppe** [comment]
@Madoshakalaka Drawing your attention to this weird issue that Arok noticed today.

**Comment by Madoshakalaka** [comment]
@aarppe sure thing

**Comment by eddieantonio** [comment]
@Madoshakalaka Please have a look at this soon. I want to record demos, and I can't demo the preverb feature because literally all of the preverbs are wrong! 😩

**Comment by aarppe** [comment]
@Madoshakalaka This issue has a higher priority than the spoken paradigms (though that is important as well, but can wait the little while until this one is solved).

**Comment by Madoshakalaka** [comment]
@aarppe Looking into it right now

**Comment by Madoshakalaka** [comment]
@aarppe @eddieantonio I can't reproduce any of it both locally and in prod?? what is happening???

**Comment by aarppe** [comment]
The error was there when I reported it, but seems to have gotten at least partially fixed. I don't know why or by whom, but we should know explicitly why that happened, and potentially got fixed by itself.

Nevertheless, _maci-_ still has one duplicate entry, where the readings _maci-_ 'evil, etc.' and _mâci-_ 'begin etc.' are both correct, cf.

![image](https://user-images.githubusercontent.com/15003407/77493850-d07f8300-6e09-11ea-9aca-7356ba6905e9.png)

**Comment by eddieantonio** [comment]
![n725075089_288918_2774](https://user-images.githubusercontent.com/2294397/77494967-e17dc380-6e0c-11ea-98c2-37f8c5406ad4.jpg)

**Comment by Madoshakalaka** [comment]
@eddieantonio I love your humor

**Comment by Madoshakalaka** [comment]
@aarppe I've created a regression test to warn the developers to prevent future issues alike happen

**Comment by Madoshakalaka** [comment]
@aarppe I figured it out. I didn't restart the process on Sapir the last time I upload the new database to Sapir. In-memory content and the new database thus became inconsistent. The issue dissapeared cuz new commits triggered restarts on Sapir later.

All in all, it's an operational error and it shouldn't re-occur.
