### ISSUE TITLE
Proposal: use emoji on search results page instead of general/specific word class

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#358]
During our design QA with Diane and @kobexamoh, we considered the option of dropping the general word class text (e.g., Noun, Verb) and replacing it with the simplified emoji. I decided to implement it just for fun as can be seen in this video: https://youtu.be/55_oFnzqQas

![Screen Shot 2020-03-23 at 3 46 52 PM](https://user-images.githubusercontent.com/2294397/77366410-92a53080-6d1d-11ea-8b19-8c44cdbe2c05.png)

Replacing the general word class with emoji helps in a few ways:

 * there was too much text on the screen — too much horizontal space; this saves a bit of horizontal space
 * "Noun" and "Verb" don't tell you enough information about a word in Cree
 * It's easy to scan for the form you want when looking up an English word. This is my personal opinion, but I would much rather stare at this emoji than try to work out if I want a VTI or a VAI. I've never internalized these terms :/

The downsides are that it is a "cute" way of display word class; some people may rather see "Verb" or even "VTA". The other is that I think this is a new thing for Plains Cree, but it is not unprecedented in Algonquian languages: I got the idea from an Anishinabemowin educator: https://twitter.com/Niigaatikwe/status/1113128787334610945

@aarppe, please share your thoughts. I think this is a whole lot more usable.

**EDIT**: the experimental implementation is in this branch: https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/tree/experiment/wordclass-emoji. It is NOT production-ready!

**Comment by aarppe** [comment]
Yes, I think that it is actually an informative and cool way to represent crucial information, and the rendition above conveys more about the nature of the verbs that just 'Verb'. I can understand that some folks will find it too cute and want more "precision".

I could imagine that for younger folks and school pupils the emojis would be the way to go, and leave out some of the stuffiness of linguistic terms.

Of course, we could argue about what are the best emojis to represent animate and inanimate participants (I want a bear!), but the ones you have chosen seem actually quite good.

If we implement this for verbs, I thikn we'd need to have emojis for nouns (NA, NI, NDA, NID) as well as pronouns (PrA, PrI), and Particles (and Preverbs).

That the [i] button still provides the more precise formulations of the features probably is sufficient in allowing us to eat our cake and save it too, by combining a visual representation with linguistic precision.

The way that this was intended to be dealt with is that users have an option of selecting what form of representation they want for linguistic features, and indeed crk.altlabel made allowances for that. Maybe we could allow for pupils and other users to choose their favorite emojis as well?

**Comment by aarppe** [comment]
Is there an emoji for a Cree/Indigenous face/person?

**Comment by eddieantonio** [comment]
> Is there an emoji for a Cree/Indigenous face/person?

Nope. I used the [🧑 ADULT emoji](https://emojipedia.org/emoji/%F0%9F%A7%91/), which is supposed to be gender-neutral, which I then applied the [🏽 Fitzpatrick Type-4 skin tone modifier](https://emojipedia.org/person-medium-skin-tone/). Anecdotally, when my Indigenous friends text me with emojis representing themselves, they use this skin tone modifier, so there's that :joy:

The result is 🧑🏽

Here's the emoji I was thinking:

* NA: 🧑🏽
* NI: 📘
* NID: 👤📘
* NAD: 👤🧑🏽
* VII: 📘➡️
* VAI: 🧑🏽➡️
* VTI: 🧑🏽➡️📘
* VTA: 🧑🏽➡️🧑🏽
* PrA: 👤
* PrI: ???
* IPC: ???
* IPV: ???

I don't have a distinction for PrA/PrI, nor do I have emoji for particles and preverbs ¯\\\_(ツ)\_/¯

**Comment by aarppe** [comment]
Since pronouns "point" to things, and we have used for now the plain English translation as `Pointing word` (some linguists even consider them verby), what if we'd use the arrow and the sign for animate/inanimate:

PrA: ➡️🧑🏽
PrI: ➡️📘

Particles are hard. I came up with the less-than-great translation `Linking word', in which case we could use the link/chain emoji:

IPC: 🔗

Preverbs are even harder - maybe we can use whatever we use for Particles for the time being.

I'm also thinking if we'd want to make the dependent relationship more explicit in the dependent nouns with a left-pointing arrow ⬅:, or a two-ways arrow ↔ , i.e.

NID: 👤⬅📘
NAD: 👤⬅🧑🏽

However, book is not an integral part of 'person', so something like a body part could be truer to the nature of those words:

NID: 👤⬅ 👁️ or 🙋‍♂️(man with raised hand)  
NAD: 👤⬅🧑🏽 or 👫(man holding hands with a woman)

**Comment by aarppe** [comment]
I was thinking if emojis for prototypical places (and time) could separately or individually be used for (Indeclinable) particles:

IPC/location - house: 🏠
IPC/time - 12 o'clock: 🕛

**Comment by aarppe** [comment]
N.B. The implementation of this issues is linked with issues #348 (and #101 to some extent).

**Comment by eddieantonio** [comment]
@kobexamoh Let's use this set for now:

NA: 🧑🏽
NI: 📘
NID: 👤📘
NAD: 👤🧑🏽
VII: 📘➡️
VAI: 🧑🏽➡️
VTI: 🧑🏽➡️📘
VTA: 🧑🏽➡️🧑🏽

every other word class: ⚡️

e.g.:
PrA: ⚡️
PrI: ⚡️
IPC: ⚡️
IPV: ⚡️

**Comment by aarppe** [comment]
Pronouns could use the arrow and referent:

PrA: ➡️🧑🏽
PrI: ➡️📘

**Comment by aarppe** [comment]
Note on terminology:
* V, N: general word class (as in English, but also in Cree)
* VII, VAI, VTI, VTA, NA, NI, NAD, NID: specific word class (as in Cree, but not in English)
* VII-1n, VII-1v, VII-2n, VII-2v, NA-1, NA-4, NA-4w: inflectional subcategory
