### ISSUE TITLE
Dynamically generate a sitemap.xml with ALL THE WORDFORMS!

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#365]
> **User story**: As a Cree language learner, when I search for a Cree word in my search engine of choice, it should link to a page on itwêwina.

How do we let search engines like Google, Bing, Duck Duck Go, etc. know that we're a Cree dictionary? By having them crawl our site! But since web crawlers need _links_ to crawl, we need to provide links to all of our _stored_ wordforms. The solution: `sitemap.xml`.

The sitemap.xml should list both all general pages (e.g., `about`, `contact-us`), but also every `/word/XXX` page.

@aarppe, I know you don't want Google to just show the definition on their search page. You can disable this by using the [`nosnippet` directive](https://support.google.com/webmasters/answer/35624#nosnippet).

We'll probably want to provide a `robots.txt` as well with a link to the `sitemap.xml`.

**Comment by Madoshakalaka** [comment]
I highly suspect Google will truncate an extra long sitemap for a domain (with no evidence, just doubting)

**Comment by Madoshakalaka** [comment]
I can do this later. I have experience with Django's sitemap generation before

**Comment by aarppe** [comment]
What I was thinking was the initially we could make available all the Cree word forms that can be found in the **basic/core** paradigms, rather than in the full paradigms. Otherwise, we'd just be giving "Google" access to our entire vocabulary - though that is something we have been thinking of doing anyhow through [Unimorph](https://www.aclweb.org/anthology/2020.lrec-1.483.pdf), but in a way that we'd control more.

**Comment by aarppe** [comment]
When we generate the word-forms in the basic and full paradigms, at the same time I'd think we'd want to consider generating the synthesizations of all these word-forms as well, for so that these can be made available in the paradigms, or even more generally, in itwêwina as well.

**Comment by aarppe** [comment]
@andrewdotn Let us do this for the basic/core paradigms, to start of with. Nevertheless, in the beginning, before they've been properly validated and publicized, we wouldn't want to make the word recordings available outside itwêwina - for a myriad of reasons.
