### ISSUE TITLE
Recordings are cut-off or do not play in Safari (macOS/iOS)

### ISSUE THREAD

**Issue by atticusha** [UAlbertaALTLab/cree-intelligent-dictionary#367]
It really do be that way sometimes.

**Comment by Madoshakalaka** [comment]
@atticusha congrats u now comp scientist

**Comment by eddieantonio** [comment]
This one is somewhat high priority because MESC uses iPads in the classroom; plus iPhones are decently popular in Alberta...

**Comment by eddieantonio** [comment]
So I've done a tiny bit of digging into this, and this is what Safari does:

It requests A SINGLE BYTE from the request at first????

(Tried this on https://sapir.artsrn.ualberta.ca/cree-dictionary/word/kotiskâwêw/)

```http
GET /validation/recording/ecfcdbfc0e0969e9d513a6984398df943a505084c0ef846b0337d78abf7d5ddb.m4a HTTP/1.1
Accept: */*
Range: bytes=0-1
Host: sapir.artsrn.ualberta.ca
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
Accept-Language: en-ca
Accept-Encoding: identity
Connection: Keep-Alive
X-Playback-Session-Id: 167298D2-DBD7-40C2-AE6F-487A75F5F38C
```

The way I implemented the recordings hosting _does not support partial content_, so it sends the entire dang file all at once:

```http
HTTP/1.1 200 OK
Content-Type: audio/m4a
X-Content-Type-Options: nosniff
Cache-Control: public, max-age=31536000
ETag: "ecfcdbf"
Date: Sat, 30 May 2020 16:12:22 GMT
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Keep-Alive: timeout=5, max=100
Content-Length: 12664
Connection: Keep-Alive
Server: gunicorn/20.0.4
```

I'm assuming Safari expects `206 Partial Content` response; then it sees the full response, and fails to play the file???!??!?!

I think the simplest solution is to configure Apache to host the static files, as it knows how to send Partial Content requests, and my terrible implementation is not only (relatively) slow, but also I don't want to have to code stuff that Apache already knows how to do. 😩

**Comment by eddieantonio** [comment]
@atticusha or @Madoshakalaka; could either of you please try this out on iPhones? I tried to fix this in UAlbertaALTLab/recording-validation-interface#86.

If it does work, (e.g., on https://sapir.artsrn.ualberta.ca/cree-dictionary/search?q=tree), then please close this issue!

**Comment by eddieantonio** [comment]
> They good
