### ISSUE TITLE
Searching with English swim does not result in yâhyânam among the Cree results

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#369]
Following up on #354, when one searches with the English verb _swim_ ...

https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/346
![image](https://user-images.githubusercontent.com/15003407/77796315-a6f66f80-7034-11ea-90e3-a1b2068c41c5.png)

... one does not get the Cree dictionary entry _yâhyânam_ among the many results, even though that is for certain in the XML source, cf.

```
<e>
   <lg xml:lang="eng">
      <l pos="English">swim</l>
   </lg>
...
   <mg>
   <tg xml:lang="crk">
      <trunc sources="CW">s/he swims; s/he swims in s.t.</trunc>
      <t rank="15.1566" pos="V">yâhyânam</t>
   </tg>
   </mg>
...


```

**Comment by aarppe** [comment]
@Madoshakalaka Here's the details of one of the issues I had run into, where we're not getting the match that we would want.

**Comment by Madoshakalaka** [comment]
@aarppe 
Our current `descriptive-analyzer.hfstol` file does not recognize yâhyânam, thus this word is not imported into the database when building it.

```
yâhyânam
yâhyânam        yâhyânam        +?
```
The latest `.hfstol` in #376 do recognize it

```
$ hfst-optimized-lookup newest.hfstol 

yâhyânam
yâhyânam        yâhyânam+V+AI+Ind+Prs+3Sg
```

I'll rebuild the database when #376 is merged

**Comment by aarppe** [comment]
Ok - other example cases are (vocative forms that are possible for [some] kinship nouns):

```
mosom
mosom	nimosôm+N+A+D+Voc+Sg	0.000000

nitanis
nitanis	nitânis+N+A+D+Px1Sg+Sg	0.000000
```

There are also some changes in the FST that have ramifications on the paradigms - namely the Unspecified actor forms for VAI verbs - so that is a further reason using the latest FST.

**Comment by aarppe** [comment]
Ideally, this type of FST update should be doable with a simple invocation, every time that we have a new version of the FST that we've tested and want to make use of in itwêwina. Nevertheless, we do not want such FST updating to happen automatically, but always with on human initiative (this has its own issue #257).

**Comment by aarppe** [comment]
When this is fixed, might it end up resolving also #369?

**Comment by aarppe** [comment]
@Madoshakalaka Please do note @eddieantonio's observation in #376 about the new FST apparently breaking something in itwêwina?

**Comment by aarppe** [comment]
The search with _swim_ now matches with _yâhyânam_, which is the desired result.

@Madoshakalaka However, _yâhyânam_ has two English definitions which are exactly the same.

![image](https://user-images.githubusercontent.com/15003407/79526698-18698280-8023-11ea-9baf-d179cbe518ed.png)

Might that be due to some remnant from the old version of the dictionary database?
