### ISSUE TITLE
Cree yâhyânam does not get analyzed by the FST, even though that has been implemented

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#370]
Recently, we have added if the inflection _yâhyânam_ and some thirty other VAI-3 verbs into the FST.

```
hfst-lookup -q src/analyser-gt-desc.hfst
yahyanam
yahyanam	yâhyânam+V+AI+Ind+Prs+3Sg	0.000000

niyahyanen
niyahyanen	yâhyânam+V+AI+Ind+Prs+1Sg	0.000000
```

However, the current itwêwina is not able to recognized that verb _yâhyânam_ at all, suggesting that the FST that is being used is not up-to-date. The form yâhyânam is only recognized as is, matching with the dictionary entry having that head.

![image](https://user-images.githubusercontent.com/15003407/77796996-ea051280-7035-11ea-9a62-b2d2a14d3864.png)

This is indicated by the linguistic analysis pop-up showing just the relabelings for `V` and `AI`.

**Comment by aarppe** [comment]
@Madoshakalaka Here's the other bug I had encountered.

**Comment by Madoshakalaka** [comment]
@aarppe got it

**Comment by eddieantonio** [comment]
@Madoshakalaka: I'll resync the Plains Cree FST mirror with giella, which should then make an automatic PR 👍

**Comment by aarppe** [comment]
The various forms of _yâhyânam_ are now properly analyzed and presented. Though for whatever reason the paradigms do not yet get generated.
