### ISSUE TITLE
The ranks do not seem to have become updated

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#371]
When searching for the English _see_, I'm still seeing the Cree _mahti_ as the first match, even though I've changed its rankings so that it should occur after all of _wâpamêw_, _wâpahtam_, and _wâpiw_,

I've checked that the rankings in `engcrk_200713.xml `are indeed correct, cf.

```
cat ~/giella/art/dicts/crk/engcrk_cw_md_200317.xml | grep 'rank=' | egrep '>((wâpamêw)|(wâpahtam)|(wâpiw)|(mahti))<' | sort -u
      <t rank="9.06402" pos="V">wâpamêw</t>
      <t rank="9.39475" pos="V">wâpiw</t>
      <t rank="9.49894" pos="V">wâpahtam</t>
      <t rank="9.5" pos="Ipc">mahti</t>
```

**Comment by aarppe** [comment]
@Madoshakalaka Here's the third discrepancy - did you update the rankings as well, as I revised them for the newest English-to-Cree file, `engcrk_cw_md_200317.xml`.

**Comment by Madoshakalaka** [comment]
oh I'm pretty sure ranks in engcrk.xml is not used. I'm work on import that.

**Comment by aarppe** [comment]
Ok, so where do you take the ranks from then?

I've updated in Giella the file with the ranks:

```
egrep '\s((wâpamêw)|(wâpahtam)|(wâpiw)|(mahti))\s' ~/giella/art/dicts/crk/Wolvengrey/W_aggr_corp_morph_log_freq.txt 
9.06402	wâpamêw	wâp-/-am
9.39475	wâpiw	wâp-/-i
9.5	mahti	mahti
9.49894	wâpahtam	wâp-/-aht
```
But I'm not sure that I've copied and updated that to sapir. I though that we might be extracting the ranks from the XML file for now, though on a longer term, it may be better to keep that ranks in a source file of their own.

**Comment by Madoshakalaka** [comment]
The only thing used is the `W_aggr_corp_morph_log_freq.txt` created on 02-14

now that I realize the rankings is also not fully applied in the level of our code:

here's the code for ranking search results

https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/8fea69ad9e9ef2bc94cb02338b7d617ec989ee63/CreeDictionary/API/models.py#L740-L778

the code is very intuitive and could be paraphrased to the following:
```
For entry A and entry B

if both entry A and entry B are matched by Cree, compare their modified-lev-distance to the user query

if one of them is matched by English while the other is matched by Cree, present the Cree result first.

if both A B are matched by English, compare their rankings in `W_aggr_corp_morph_log_freq.txt`, if it's not found in `W_aggr_corp_morph_log_freq.txt` present it at the end.
```

**Comment by aarppe** [comment]
@Madoshakalaka I've not uploaded and updated the revised ranking file on `sapir`, in:

`/data/texts/crk/dicts/itwewina/`

The size of the new fine is minutely different from the previous one:

`-rw-rw---- 1 arppe domain users   898185 Mar 27 17:22 W_aggr_corp_morph_log_freq.txt`

I had previously thought that we could import the rankings from the engcrk*.xml file, but the weights on the above file are just as good (and probably more straight-forward, as they are independent of any English translations).

**Comment by Madoshakalaka** [comment]
@aarppe I have updated the `W_aggr` file you should see changed in 5 minutes.

Protip: You can update `W_aggr_corp_morph_log_freq.txt` in our repository just as how you update `crkaltlabl.tsv`. Changes will be take into effects in minutes if the build pass.
