### ISSUE TITLE
Prefix features should also end up on their own lines

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#373]
When searching with a Cree word like _ê-kî-nitawi-kâh-kîmôci-kotiskâwêyâhk_, with preverbs (`PV/...+`) and reduplication elements (`RdplW+` and `RdplS+`), the preverbs currently do nt end up on their own line, in contrast to the suffix features:

![image](https://user-images.githubusercontent.com/15003407/77935914-59b21200-726f-11ea-8ca4-6675d391e1b0.png)

So, the visual presentation should be updated so that also prefixal features in the pop-up are shown each on their own line. In the above screenshot, that is NOT yet the case for the preverbs - they should appear similar to the suffix features, each on their own line.

**Comment by aarppe** [comment]
@kobexamoh This fix is for you.

**Comment by eddieantonio** [comment]
@aarppe, does this screenshot demonstrate what the issue you're talking about?

**Comment by aarppe** [comment]
I've fixed the screenshot above, which illustrates the current undesired state of affairs, where the presentation of prefixal features (preverbs and reduplication, and initial change) is NOT YET  correct - they should appear similar to the suffix features, each on their own line.

**Comment by eddieantonio** [comment]
Blocked by #462 — it will cause a merge conflict if I try to fix this simultaneously :/
