### ISSUE TITLE
Find a new deployment strategy

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#377]
We will be deploying to new machines soon. We need to find a new way to both run the application and deploy it. I think now is a good time to experiment with Docker. Here's my idea:

 - Create a Dockerfile that builds an image with:
     - all of the Python dependencies installed
     - all of the compiled/staticfiles generated. E.g., compiled and minified JS
 - Our Travis script will create a new Docker image and publish it to... somewhere
 - Our deploy script will simply pull the latest image, and redeploy it — no compilation will happen on the production server, and no need to install npm or node.

**Comment by Madoshakalaka** [comment]
I like this proposal a lot. This is more a standard approach afaik

**Comment by eddieantonio** [comment]
My experiments are in #378

**Comment by eddieantonio** [comment]
The work in #378 was _way_ more difficult than I thought. I'm gonna give this one a break for a bit, while I figure out the deployment of our _other_ apps!

**Comment by Madoshakalaka** [comment]
I consider this roughly done. A new issue should be proposed when it's time to migrate to the new infrastructure
