### ISSUE TITLE
Search doesn't return particle phrases consistently

### ISSUE THREAD

**Issue by katieschmirler** [UAlbertaALTLab/cree-intelligent-dictionary#381]
If I search e.g. _kotak_, I get all forms containing _kotak_ (phrase and single-word), but if I search e.g. _eka_ or _namôya_, I only get the particle, not any of their many phrases---I can get the phrase if only if I search it in its entirety, which is unhelpful to a learner.

**Comment by aarppe** [comment]
This seems to have gotten implemented, cf.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/15003407/126586446-39c000f9-c3e8-48d3-addc-722380dc3e2e.png">

**Comment by aarppe** [comment]
@katieschmirler Does this now work better for you?

**Comment by katieschmirler** [comment]
Yes, much better! I do notice when I search _namôya_ now, it also returns (following all the previously missing particle phrases) a number of nouns where I'm struggling to see the formal or semantic connections (in most cases)--not an issue, I'm just curious as to what aspects of the search functionality result in this.

**Comment by aarppe** [comment]
The semantically unrelated tail of the search results should be turned into an issue of its own, thus closing this issue.
