### ISSUE TITLE
yâhyânam does not get a paradigm

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#388]
While various inflected forms of _yâhyânam_ are recognized, the corresponding paradigm is not generated.

This appears to be due to the paradigm request having an unnecessary inflectional code (`VAI-3`), cf. the code at the very bottom:

![image](https://user-images.githubusercontent.com/15003407/79527278-65018d80-8024-11ea-9e26-0eb3d168937a.png)

**Comment by aarppe** [comment]
@Madoshakalaka Take a look at the link at the bottom of the window, when hovering over the dictionary entry before clicking to get the paradigm:

`https://sapir.artsrn.ualberta.ca/cree-dictionary/search?q=yâhyânam/?full_lc=VAI-3`

My understanding is that the final segment `?full_lc=VAI-3` is unnecessary, and probably part of the reason why one cannot get to the paradigm.

**Comment by Madoshakalaka** [comment]
@aarppe 

fst only know yâhyânam as VAI: yâhyânam+V+AI+Ind+Prs+3Sg

but the xml file I have indicates yâhyânam is both VAI and VTI:

```
<e>
   <lg>
      <l pos="V">yâhyânam</l>
      <lc>VTI-1</lc>
      <stem>yâhyân-</stem>
   </lg>
   <mg>
   <tg xml:lang="eng">
       <t pos="V" sources="CW">s/he swims; s/he swims in s.t.</t>
   </tg>
   </mg>
</e>

<e>
   <lg>
      <l pos="V">yâhyânam</l>
      <lc>VAI-3</lc>
      <stem>yâhyân-</stem>
   </lg>
   <mg>
   <tg xml:lang="eng">
      <t pos="V" sources="CW">s/he swims; s/he swims in s.t.</t>
   </tg>
 </mg>
</e>
```

One of them needs to be corrected I think?

**Comment by aarppe** [comment]
@Madoshakalaka An older version of the dictionary had that verb as both VAI and VTI, but the latest version has it only as a VAI. So, we should exclude the VTI reading from the XML source.

**Comment by Madoshakalaka** [comment]
@aarppe may I know the scripts that generate those xml from tsvs? I'm interested in trying it myself and produce a newer `crkeng_200529.xml`

**Comment by aarppe** [comment]
I have a script that did that, which would be straight-forward to run, or reimplement, if we had only one single source, namely CW. But since we have also MD, we need to integrate the two, and the script that I have still leaves a hundred or several cases where a linguist is needed, and which are really difficult to resolve programatically.

So, one should ideally do this in our DDB (nad that was the intention), where in importing we would need to identify cases where the two dictionaries might have entries for the same linguistic headword. Then, we'd need to judge whether the definitions are effectively the same, or just similar but different, or concern entirely unrelated words. In such a case, one would prefer having a linguist decide, which shouldn't take too long - and once that has been done once, then one would not want to need to do that decision again (unless the dictionary entries change in either dictionary).

**Comment by aarppe** [comment]
@Madoshakalaka  There still seems to be something weird going on -- as we get a right-seeming match, but also entirely incorrect matches:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/15003407/83310301-c5115500-a1c8-11ea-8596-4b5377f99121.png">

<img width="641" alt="image" src="https://user-images.githubusercontent.com/15003407/83310334-e70ad780-a1c8-11ea-8d5e-570f94606196.png">

**Comment by aarppe** [comment]
The AI versions of yâhyânam and nihtâ-yâhyânam get their paradigms, while the TI ones don't. That is how things should be, since Arok has reclassified these lemmas as AIs.

That these are turning up is due to the old and new version of the dictionary entry remaining in the dictionary source XML, and as far as I can see, this should be fixable by removing such old dictionary entries from the XML, and is covered in #372,  (so not a proper _itwêwina_ coding issue). The headache for us is finding the entire set of such reclassification in the XML source, instead of the piecemeal discover that we've ended up following for now.
