### ISSUE TITLE
Enable search with derivational morphemes

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#391]
Following #390, index dictionary content also with derivational content in order to allow for searching the Cree dictionary entries for ones with a matching derivational morpheme.

**Comment by aarppe** [comment]
E.g. searching with `wâp-`, one would get 131 matching dictionary entries, of which the first 20 are the following:

```
cat ~/GDrive/CreeFST/Wolvengrey/Wolvengrey_crk2eng_200202_altlab.tsv | gawk -F"\t" '$10 ~ /\/wâp\-\// { gsub(" ;; ","",$10); gsub("[/]+","/",$10); print $1"\t"$10; }' | head -20
awasi-wâpahki	/awas-/-i/wâp-/-an/{-k}{-i}
isi-wâpahtam	/iT-/-i/wâp-/-aht/
kiskinowâpahcikêw	/kiskinw-/wâp-/-aht/-ikê/
kiskinowâpahkêw	/kiskinw-/wâp-/-am/-kê/
kiskinowâpahkêwin	/kiskinw-/wâp-/-am/-kê/-win/
kiskinowâpahtam	/kiskinw-/wâp-/-aht/
kiskinowâpahtihêw	/kiskinw-/wâp-/-aht/-h/
kiskinowâpahtihiwêw	/kiskinw-/wâp-/-aht/-h/-iwê/
kiskinowâpahtihiwêwin	/kiskinw-/wâp-/-aht/-h/-iwê/-win/
kiskinowâpamâkan	/kiskinw-/wâp-/-am/-âkan/
kiskinowâpamêw	/kiskinw-/wâp-/-am/
kiskinowâpiw	/kiskinw-/wâp-/-i/
kiskinowâpiwin	/kiskinw-/wâp-/-i/-win/
kîhtwâm ka-wâpamitin	kîhtwâm/wâp-/-am/
misi-wâpamêk	/mis-/-i/wâp-/-amêkw/
okiskinowâpiw	/o-/kiskinw-/wâp-/-i/-w/
pê-wâpahtam	pê-/wâp-/-aht/
pê-wâpamêw	pê-/wâp-/-am/
saskaci-wâpahtam	/saskat-/-i/wâp-/-aht/
saskaci-wâpamêw	/saskat-/-i/wâp-/-am/
```

**Comment by aarppe** [comment]
In implemeting this search, we need to figure out the following:

1. Will one need to provide the initial/final hyphens, to distinguish the search string as a derivational morpheme in contrast to the usual strings? Will leaving out the hyphens result in overgeneration?

2. How to deal with derivational morphemes for which the exponent is the same but the meaning is different, e.g. `-n1 `, `-n2` and `-n3`. AEW codes these with numbers - will we require these numeric indices, or rather opt to ignore such indices?

3. How/Where do we present the entire derivational make-up of a dictionary entry? (Probably best dealt with as a separate issue of its own).

**Comment by eddieantonio** [comment]
Marking as duplicate in favor of #726; however, the comments here are useful too!
