### ISSUE TITLE
Revise paradigm and layout files for verbs to match marking of tense as preverb rather than suffix-feature

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#392]
As of today, the crk FST has been revised so that tense is rather marked with the associated preverb (_kî-_, _wî-_, or _ka-_) rather than as a suffixal feature (`+Prt`, `+Fut+Int`, `+Fut+Def`). This also means that present tense is an unmarked case and  does not have a feature any more (`+Prs`).

This requires that the references to the old tense features anywhere need to be updated to match this new preverb-marking, in the specification of paradigms and layouts as well as in relabeling. In relabeling, we can make use of the standard format for alternative labels of preverbs as well as definitions in CW.

For the verbal paradigms and their layouts, the changes should be deterministic, with the following template:

_ninipân_: `nipâw+V+AI+Ind+Prs+1Sg -> nipâw+V+AI+Ind+1Sg` 
_nikî-nipân_: `nipâw+V+AI+Ind+Prt+1Sg -> PV/ki+nipâw+V+AI+Ind+1Sg` 
_niwî-nipân_: `nipâw+V+AI+Ind+Fut+Int+1Sg -> PV/wi+nipâw+V+AI+Ind+1Sg` 
_nika-nipân_: `nipâw+V+AI+Ind+Fut+Def+1Sg -> PV/ka+nipâw+V+AI+Ind+1Sg `

_ê-nipâyân_: `nipâw+V+AI+Cnj+Prs+1Sg -> PV/e+nipâw+V+AI+Cnj+1Sg` 
_ê-kî-nipâyân_: `nipâw+V+AI+Cnj+Prt+1Sg -> PV/e+PV/ki+nipâw+V+AI+Cnj+1Sg` 
_ê-wî-nipâyân_: `nipâw+V+AI+Cnj+Fut+Int+1Sg -> PV/e+PV/wi+nipâw+V+AI+Cnj+1Sg `

This also means that the affixation of other tense/aspect grammatical preverbs take the unmarked stem case (i.e. what used to be marked as present tense with `+Prs`, but which no longer has that feature/tag). This makes the feature/tag representation of such tense/aspect preverbs more coherent.

**Comment by aarppe** [comment]
In order for this not to disrupt itwêwina's functioning, this means making changes in four places at the same time:
- [ ] 1. Removing the tense suffix tags from the basic paradigm layouts for all verbs
- [ ] 2. Updating the FSTs to the latest ones where this change has been implemented.
- [ ] 3. Updating the full paradigm specifications for verbs which are used to pregenerate the core inflected forms.
- [ ] 4. Make sure that the new preverbal tense features (`PV/ki+`, `PV/wi+`, `PV/ka+`) are treated similar to other preverbs in the presentation of the search results.

**Comment by aarppe** [comment]
@eddieantonio Has the new branch `new-paradigm-and-layouts` been implemented according to the standard practice? I hoped to have made it available on our repo and not just on my own MBA.

**Comment by eddieantonio** [comment]
> @eddieantonio Has the new branch `new-paradigm-and-layouts` been implemented according to the standard practice? I hoped to have made it available on our repo and not just on my own MBA.

Yes, it looks right as far as I can tell! We might have conflicts when merging with master, so look out for that!

**Comment by aarppe** [comment]
Ok, good. I implemented also `git branch --set-upstream-to=origin/develop new-fst-and-paradigm-layouts` so that it would be linked to the main branch (as that was suggested). Now, `Branch 'new-fst-and-paradigm-layouts' set up to track remote branch 'develop' from 'origin'.`

**Comment by eddieantonio** [comment]
> Ok, good. I implemented also `git branch --set-upstream-to=origin/develop new-fst-and-paradigm-layouts` so that it would be linked to the main branch (as that was suggested). Now, `Branch 'new-fst-and-paradigm-layouts' set up to track remote branch 'develop' from 'origin'.`

That... is incorrect! The name locally and the name on the remote (i.e., GitHub) should be the same. So please run the following command:

```sh
git branch --set-upstream-to=origin/new-paradigm-and-layouts
```

**Comment by aarppe** [comment]
Ergh. I had already run the above git command. So when I tried to run the one you recommend, I get the following error message:

**Comment by aarppe** [comment]
> git branch --set-upstream-to=origin/new-paradigm-and-layouts

Ran this in the correct repo. Hopefully now all is good.
