### ISSUE TITLE
Ambiguous words do not get paradigms

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#395]
Searching for _nôhtêpayiw_, I do get a match with two dictionary entries:

![image](https://user-images.githubusercontent.com/15003407/80140077-acc46f80-8564-11ea-997b-ff6dd65dd36a.png)

But I cannot get a paradigm for either. Neither can I get a full analysis, even though the computational model does provide that:

```
hfst-lookup -q src/analyser-gt-desc.hfst
nôhtêpayiw
nôhtêpayiw	nôhtêpayiw+V+AI+Ind+3Sg	0.000000
nôhtêpayiw	nôhtêpayiw+V+II+Ind+3Sg	0.000000
```
The same applies for _ayâw_:

![image](https://user-images.githubusercontent.com/15003407/80140359-10e73380-8565-11ea-8554-5d1093d0c34c.png)

I suspect this is connected with _ayâw_ being either an II, AI, or TI verb.

**Comment by aarppe** [comment]
@Madoshakalaka Clicking on the lemma (e.g. _ayâw_ or _nôhtêpayiw_ or _yâhyânam_) still doesn't provide a paradigm!!! (This may be

**Comment by Madoshakalaka** [comment]
@aarppe it takes five minutes or so for the redeployment to finish

**Comment by Madoshakalaka** [comment]
@aarppe a good indicator is the yellow dot to the side of my pr #419 above. It indicates the redeployment is still going on.

**Comment by Madoshakalaka** [comment]
@aarppe when it turns to a green tick that when the change is merged to production server.

**Comment by Madoshakalaka** [comment]
@aarppe You are right...I do still have difficulty opening the paradigm page. I'll follow up on this shortly after!

**Comment by Madoshakalaka** [comment]
@aarppe looks like it was just a slow update. Check now, should be OK

**Comment by aarppe** [comment]
Yes, now it works where it should, and what doesn't work is due to discrepancies in the source XML which is for the linguists to fix.
