### ISSUE TITLE
Info pop-up is hard to read

### ISSUE THREAD

**Issue by atticusha** [UAlbertaALTLab/cree-intelligent-dictionary#401]
When you hover over the blue (i) button on the results page, you get a set of linguistic information. From what I understand, it's hard to make this dynamic to the user's current resolution, so it's been made permanently narrow. This is not a problem in and of itself, but it results in the following:

![Screen Shot 2020-05-05 at 10 57 23 AM](https://user-images.githubusercontent.com/37557159/81093656-a5d02200-8ebf-11ea-9763-88b9677f0afd.png)

Personally, I find this kinda hard to read. Could we put some indenting and bullets or ticks or something? I've done. really quick mock up:

![mockup](https://user-images.githubusercontent.com/37557159/81094316-8d143c00-8ec0-11ea-8a44-84ae1ca24d5d.png)

**Comment by aarppe** [comment]
We used to have plus signs.

Another aspect is that being able to relabel multi-tag sequences should result in more easily digestible labels.

**Comment by eddieantonio** [comment]
Hey @atticusha, let me know how it looks now!

https://sapir.artsrn.ualberta.ca/cree-dictionary/search?q=pisin

![Screen Shot 2020-06-09 at 10 41 53 AM](https://user-images.githubusercontent.com/2294397/84175909-dd416980-aa3d-11ea-8dbb-4db9c75a0ba1.png)

**Comment by atticusha** [comment]
yes, other than the indentation or bulletin I'd give this a 10/10.

Although, testing on my computer right now I get the following, which is sort of weird (especially given that the first item should be of a different level than the others, but I think it's just being played with right now?
![Screen Shot 2020-06-09 at 11 23 07 AM](https://user-images.githubusercontent.com/37557159/84179849-cd2c8880-aa43-11ea-850d-e291afd986f0.png)

**Comment by aarppe** [comment]
@kobexamoh @eddieantonio Implementing the multi-feature relabeling issue #348 would be crucial here in making the linguistic analysis information more easily understandable. It would make sense to combine the specific wordclass info, i.e. `II`, `AI`, `TI`, `TA` for verbs and `A`, `I`, `A+D`, `A+I` for nouns, with the general wordclass feature (`V`, `N`, `Ipc`).

So, one would prefer the following relabeling scheme for an AI verb such as _pîsin_:

`+V+AI` -> `Action word — like: mîcisow`
`+Ind` -> `ni-/ki- word` 
`+Prs` -> `something is happening now`
`+3Sg` -> `s/he`

Even more important this grouping is for TA verbs such as _wâpamât_ -> wâpamêw+V+TA+Cnj+3Sg+4Sg/PlO:

`+V+TA` -> `Action word — like: wîcihêw`
`+Cnj` -> `ê-/kâ- word` 
`+Prs` -> `something is happening now`
`+3Sg+4Sg/Pl` -> `s/he -> him/her/them`

... or imperative forms, e.g. _wâpam_ -> wâpamêw+V+TA+Imp+Imm+2Sg+3SgO:

`+V+TA` -> `Action word -- like: wîcihêw`
`+Imp+Imm` -> `Command -- immediate` 
`+Prs` -> `something is happening now`
`+2Sg+3Sg0` -> `you -> him/her`

For nouns, the following would be the preferred formatting:

_niwâwima_ 'my eggs' ->` wâwi+N+I+Px1Sg+Pl`:
`+N+I` -> `Noun — like: cîman, wâwi`
`+Px1Sg` -> `my` 
`+Pl` -> `many`

`kôhkoma` 'my further grandmothers' -> nôhkom+N+A+D+Px2Sg+Obv
`+N+A+D` -> `Noun — like: nôhkom, mitâs`
`+Px2Sg` -> `your (one)` 
`+Obv` -> `further`

Most of this relabeling is already implemented in `crk.altlabel.tsv`, but I can check if there's anything missing.

**Comment by eddieantonio** [comment]
> yes, other than the indentation or bulletin I'd give this a 10/10.
> 
> Although, testing on my computer right now I get the following, which is sort of weird (especially given that the first item should be of a different level than the others, but I think it's just being played with right now?
> ![Screen Shot 2020-06-09 at 11 23 07 AM](https://user-images.githubusercontent.com/37557159/84179849-cd2c8880-aa43-11ea-850d-e291afd986f0.png)

This is because I used CSS that Safari doesn't understand :/ Fixed!

![Screen Shot 2020-06-09 at 3 32 42 PM](https://user-images.githubusercontent.com/2294397/84203330-8439fb80-aa66-11ea-8b3e-f1cef46035f7.png)
