### ISSUE TITLE
spelling error in English gloss

### ISSUE THREAD

**Issue by atticusha** [UAlbertaALTLab/cree-intelligent-dictionary#402]
I'm opening this issue because I've come across a spelling issue in the English gloss of a word. Perhaps I can re open this issue every time I find another error, as I imagine there's enough to fill up the issues tab entirely. 

I also recognize that this is probably my error. Sorry!

```
ohtêw
It gboils
```

Obviously, this should be:

```
ohtêw
It boils
```

**Comment by aarppe** [comment]
Fixed in `crkeng.xml `and `Maskwacis.tsv`. (Would prefer not to update manually engcrk.xml, but may yet have to). What is yet needed is importing this to itwêwina.

**Comment by aarppe** [comment]
@atticusha In the case of MD, one should edit both the original source, `Maskwacis.tsv`, and the derivative,` crkeng.xml` (until we have an automated script creating the XML). Both are to be found in the ALTLab repo: `.../altlab/crk/dicts/`:

```
ls -l Maskwacis.tsv crkeng.xml
-rw-r--r--  1 arppe  staff  1774135 21 Jul 00:08 Maskwacis.tsv
-rw-r--r--  1 arppe  staff  5555255 21 Jul 00:08 crkeng.xml
```

After such edits and fixes, we still need to import `crkeng.xml` into itwêwina.

**Comment by aarppe** [comment]
This seems to have gotten fixed, one way or another, cf.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/15003407/126585109-40e74246-b1cf-4e1c-b317-5d8bc5bdaf42.png">

But on the longer term, the two English definitions should be considered aggregated as one, with the double source coding for `[MD CW]`.
