### ISSUE TITLE
Add recording link to the search page

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#404]
You should be able to hear at least ONE recording for each word that has recordings STRAIGHT FROM the search page!

So the speaker icon should be beside the (i) icon.

**EDIT**: this will avoid the question "_which words have audio?_"

**Comment by aarppe** [comment]
@eddieantonio Added new label to indicate than an issue/feature request is a result of feedback from the end-user community (outside of academia, primarily but not exclusively MESC).

**Comment by aarppe** [comment]
An even greater positive surprise - I can see recordings for inflected forms, e.g. ê-kimiwasik!!!

<img width="381" alt="image" src="https://user-images.githubusercontent.com/15003407/83715442-92ad9080-a5ea-11ea-99e7-cb5a8dedb1b8.png">
