### ISSUE TITLE
Add a page/legend or help text explaining abbreviations

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#405]
Especially Arok's abbreviations, e.g., `s.t.`/`s.o`/`s/he`/`it`, etc.

**Comment by aarppe** [comment]
And/or a pop-up? I.e. when you hover over `s/he`, you got `she or he` (in the English definitions)?

**Comment by aarppe** [comment]
@eddieantonio This is something I can do. Should we have this as a page available under itwêwina, or an external page (under ALTLab)? Eventually we would also have links to the grammar pages that Arok is in the process of creating, but that would be more comprehensive explanations of Cree grammar, while we'd just be explaining tersely the various code we use - so we might have link elsewhere for "More information".

**Comment by eddieantonio** [comment]
Please create a separate page at <https://www.altlab.dev/> (`altlab-gw:/data/www.altlab.dev/`) and add a link to the page in the footer!

**Comment by eddieantonio** [comment]
We need to explain the emoji too — my suggestion: use the exact words that Dorothy uses when teaching the difference between VTA and VTI (e.g., [pêtâ](https://sapir.artsrn.ualberta.ca/cree-dictionary/word/p%C3%AAt%C3%A2w/) masinahikan/[pêsiw](https://sapir.artsrn.ualberta.ca/cree-dictionary/word/p%C3%AAsiw%C3%AAw/) maskwa).
