### ISSUE TITLE
Make relabeling of 1st person plural exclusive more explicit

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#406]
In order to distinguish in the paradigm layouts the exclusive from the inclusive for 1st person person forms, change 1Pl relabeling to `we (but not you)` (and 1PlO to `us (but not you)` and Px1PlO to `our (but not your)`)

**Comment by eddieantonio** [comment]
I love the description of `we (but not you)`. It's important to make this distinction, because English does not have it.

**Comment by aarppe** [comment]
We needed to distinguish also 'us (but not you)' in TA verbs.

This is now implemented as of https://travis-ci.org/github/UAlbertaALTLab/cree-intelligent-dictionary/builds/709279577 / https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/commit/06233c1c5d594a9bdf166687e5c8e5f1f040c235
