### ISSUE TITLE
Dictionary entries for lemmas with both noun and verb reading incorrectly conflated together

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#412]
Following up on #190, so that inflected forms are now matched, the dictionary entries for the noun and verb reading are now conflated, which shouldn't take place, cf.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/15003407/83310432-3ea94300-a1c9-11ea-867c-71039e4b0233.png">

Unless this is so in the source, _winter_ (ni) and _it is winter_ (vii) should be two different dictionary entries also in itwêwina.

**Comment by aarppe** [comment]
@Madoshakalaka Can you follow up on this?

**Comment by Madoshakalaka** [comment]
@aarppe sure thing!

**Comment by Madoshakalaka** [comment]
yay! whack-a-mole!

**Comment by Madoshakalaka** [comment]
I just determined the reason: our legacy code (I wrote) doesn't respect enough the possibilty that a non-lemma could have separate definition from the lemma.

It didn't emerge as a problem as we weren't showing definition for non-lemmas.

**Comment by Madoshakalaka** [comment]
@aarppe I editted the issue several times, hope you don't get confused if you have email notification turned on

**Comment by Madoshakalaka** [comment]
@aarppe
 
> yay! whack-a-mole!

I want to clarify this a bit. I think from the process of whacking-moles, the database is improving a bit by a bit. What is undeniable is that I've been writing effective code and correcting bugs :smiley:

**Comment by Madoshakalaka** [comment]
@aarppe fixed now
