### ISSUE TITLE
Searching with 'nehiyaw' crashes itwêwina

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#413]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/15003407/83335721-ed05c480-a26b-11ea-9102-2c53bb685a77.png">

**Comment by eddieantonio** [comment]
@Madoshakalaka please have a look at this as quickly as possible 😩

**Comment by aarppe** [comment]
Interestingly, searching with the inflected form _nehiyawak_ does work (`https://sapir.artsrn.ualberta.ca/cree-dictionary/search?q=nehiyawak`).

**Comment by Madoshakalaka** [comment]
@aarppe @eddieantonio Fixed, a trivial error in code.

However this is interesting cuz:

These two entries co-exist in the source xml:

```
<e>
   <lg>
      <l pos="Ipc">nêhiyaw-kîkway</l>
      <lc>IPC</lc>
      <stem></stem>
   </lg>
   <mg>
   <tg xml:lang="eng">
       <t pos="Ipc" sources="CW">Cree things</t>
   </tg>
   </mg>
</e>

<e>
   <lg>
      <l pos="">nêhiyaw-kîkway</l>
      <lc>PR</lc>
      <stem></stem>
   </lg>
   <mg>
   <tg xml:lang="eng">
      <t pos="" sources="CW">something Cree, Cree things</t>
   </tg>
 </mg>
</e>


```

The second one has `pos=""` and `<lc>PR</lc>` which confuses the app.

And this is what is shown after the fix:

![Screenshot from 2020-05-30 19-46-01](https://user-images.githubusercontent.com/44753941/83342562-3f67d500-a2ae-11ea-81b4-da69c24b66dd.png)


Notice the second card, there's no word class shown cuz our app is confused.

**Comment by Madoshakalaka** [comment]
The fix is not yet online. It will be online afte the PR is reviewed and merged
