### ISSUE TITLE
Improve presentation of multiple recordings

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#422]
Following up on #347, make the presentation of multiple recordings better, taking inspiration from the UX specs.

**Comment by kobexamoh** [comment]
I didn't add these in on Wednesday afternoon: adding them now. These are the mockups I put together (mobile, desktop) for rethinking the way we display speaker links/multiple recordings (i.e. saving screen space and displaying the bio/image/recordings as a popup).

@eddieantonio, I can put this into Slack if that's better for fleshing it out (e.g. into a 'mockups' or 'design' channel!).

**Comment by eddieantonio** [comment]
> I didn't add these in on Wednesday afternoon: adding them now. These are the mockups I put together (mobile, desktop) for rethinking the way we display speaker links/multiple recordings (i.e. saving screen space and displaying the bio/image/recordings as a popup).
> 
> @eddieantonio, I can put this into Slack if that's better for fleshing it out (e.g. into a 'mockups' or 'design' channel!).
> 
> ### Desktop Imagining
> ![Desktop-Speaker-1](https://user-images.githubusercontent.com/20422653/85891226-f7a07480-b7ab-11ea-9540-a842be8ae898.jpg)
> ![Desktop-Speaker-2](https://user-images.githubusercontent.com/20422653/85891238-fb33fb80-b7ab-11ea-908b-4333d6d657bf.jpg)
> 
> ### Mobile Imagining
> ![Mobile-Speaker-1](https://user-images.githubusercontent.com/20422653/85891248-fe2eec00-b7ab-11ea-98c4-60ef63fa7a93.jpg)
> 
> **Popup version 1**
> ![Mobile-Speaker-2-v2](https://user-images.githubusercontent.com/20422653/85891251-ff601900-b7ab-11ea-9e9c-392d39293026.jpg)
> 
> **Popup version 2**
> ![Mobile-Speaker-2](https://user-images.githubusercontent.com/20422653/85891254-00914600-b7ac-11ea-9124-1a09e5a235ac.jpg)

Please put it in Slack, in a new channel called something like `#mockups`

**Comment by kobexamoh** [comment]
Sounds good!

**Comment by kobexamoh** [comment]
Fixed by #522, #536, and #537.
