### ISSUE TITLE
vowel length causing failed in prefix search

### ISSUE THREAD

**Issue by katieschmirler** [UAlbertaALTLab/cree-intelligent-dictionary#429]
search "nisto-" - results in a list of forms containing "nisto-"
search "niso-" - results in a list of forms containing "nîso-"
search "nîso-" - results only in the preverb "nîso-", not forms containing it
(some further tests: "newo-" works, "nêwo-" does not)

https://sapir.artsrn.ualberta.ca/cree-dictionary/search?q=nisto-
https://sapir.artsrn.ualberta.ca/cree-dictionary/search?q=niso-
https://sapir.artsrn.ualberta.ca/cree-dictionary/search?q=n%C3%AEso-
https://sapir.artsrn.ualberta.ca/cree-dictionary/search?q=newo-
https://sapir.artsrn.ualberta.ca/cree-dictionary/search?q=n%C3%AAwo-

**Comment by Madoshakalaka** [comment]
@katieschmirler fixed now. Should be online in 5 minutes :)

**Comment by katieschmirler** [comment]
Hmmm it's been 7 minutes now.... still not up........ ;)

**Comment by eddieantonio** [comment]
Could you please try it now?

**Comment by katieschmirler** [comment]
Looking great!
