### ISSUE TITLE
Add general word-classes to crk.altlabel.tsv

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#432]
In order to make the presentation of various labels based on explicit linguistic definitions rather than deduced by coding, I would add the general word class to the relabeling scheme in `crk.altlabel.tsv`.

```
Original	General	Short linguistic	Long linguistic	Plain English	Plain nêhiyawêwin	Emoji
TA	V	Transitive Animate		like: wîcihêw, itêw	tâpiskôc: wîcihêw, itêw	🧑🏽➡️🧑🏽
VTA-1	V	VTA-1	transitive animate verb – class 1: regular	like: wîcihêw	tâpiskôc: wîcihêw	-
```
This likely means that the code that makes use of `crk.altlabel.tsv` might need to be revised accordingly. References to general word-classes can the be relabeled according to their own respective relabeling scheme based on user selection / default setting, so `V` --> `Verb` / `Action word` / `ispayin-itwêwin`, etc.

**Comment by aarppe** [comment]
This should become redundant with how the new to-be-imported dictionary data is specified and created (in: https://github.com/UAlbertaALTLab/crk-db).

**Comment by aarppe** [comment]
@dwhieb Isn't this redundant now?

**Comment by dwhieb** [comment]
@aarppe yes, closing this now.
