### ISSUE TITLE
Updated mockups for presenting search results

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#445]
Since the descriptions in several previous issues are out-of-date or do not take into account later developments, this is an attempt at an up-to-date aggregation of all relevant previous ideas, and thus to replace #296, #224, #232 and even #101:

**1. Inflected form with definition – non-emoji**

![image](https://user-images.githubusercontent.com/15003407/84325836-e9f6b800-ab38-11ea-934a-77e7070c933f.png)

**2. Inflected form without definition – non-emoji**

![image](https://user-images.githubusercontent.com/15003407/84325873-01ce3c00-ab39-11ea-8ac2-584bdbe022a9.png)

**3. Lemma definition – non-emoji**

![image](https://user-images.githubusercontent.com/15003407/84326238-ba947b00-ab39-11ea-9751-8be259e50b6f.png)

**4. Inflected form with definition – emoji**

![image](https://user-images.githubusercontent.com/15003407/84325936-23c7be80-ab39-11ea-90a6-a161e67cfb83.png)

**5. Inflected form without definition – emoji**

![image](https://user-images.githubusercontent.com/15003407/84325984-3e9a3300-ab39-11ea-9567-b651385e799f.png)

**6. Lemma definition – emoji**

![image](https://user-images.githubusercontent.com/15003407/84326074-65f10000-ab39-11ea-8452-a3dc3e440fb3.png)

**Comment by aarppe** [comment]
@eddieantonio Here is an attempt at an update to the visual presentation, to replace earlier issues and descriptions.

**Comment by eddieantonio** [comment]
@kobexamoh I've unassigned you from the previous issues, as they are all duplicates of this one
