### ISSUE TITLE
Weird layout on paradigms

### ISSUE THREAD

**Issue by atticusha** [UAlbertaALTLab/cree-intelligent-dictionary#470]
![image](https://user-images.githubusercontent.com/37557159/85231493-a3b11c80-b3b4-11ea-88f1-74317341f5bc.png)

Not functionality breaking, but I thought I’d mention it!

**Comment by Madoshakalaka** [comment]
![300px-Phil_Swift_Slapping_on_Flex_Tape](https://user-images.githubusercontent.com/44753941/85232603-52595b00-b3bd-11ea-92dc-9c8497dbdf54.jpg)

expect the fix from Eddie in 10 minutes
