### ISSUE TITLE
Stem should be shown (instead of lemma) in linguistic analysis pop-up

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#475]
Once #235 is completed, the stem should be shown, instead of the lemma, at least in the linguistic analysis pop-up (maybe elsewhere, but that needs to be determined).  The stem should be with the final and/or initial hyphen, like _atimw-_ and _-ohkom-_, to indicate that it is not always an independent word.

**Comment by aarppe** [comment]
Note that stem should be now shown (instead of lemma) **only** in the pop-up for linguistic analysis.

We might add "somewhere" on the paradigm page an explicit field with the stem.

**Comment by eddieantonio** [comment]
It's been implemented!

<img width="932" alt="Stem: kotiskawê-" src="https://user-images.githubusercontent.com/2294397/95348738-8f1d6500-087b-11eb-96c3-9945994e6339.png">

**Comment by aarppe** [comment]
@eddieantonio Excellent! (I saw that forthcoming yesterday.)
