### ISSUE TITLE
Update layouts (and paradigms) automatically

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#476]
When layout (or paradigm) files are modified, they should be updated automatically to itwêwina (with tests, of course).

**Comment by aarppe** [comment]
@Madoshakalaka Where can I track how updates to *.layout.tsv files are progressing? Under the `Actions` tab? Or elsewhere? I updated the VTA basic layout two hours ago, and I'm still not seeing the result (it appears to have passed the internal tests as well compilations).

**Comment by eddieantonio** [comment]
> @Madoshakalaka Where can I track how updates to *.layout.tsv files are progressing? Under the `Actions` tab? Or elsewhere? I updated the VTA basic layout two hours ago, and I'm still not seeing the result (it appears to have passed the internal tests as well compilations).

It _does_ work automatically! However, the changes introduced [here](https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/commit/7855e1919f3516494866301a3152a3f005e53d53) broke the build:

https://travis-ci.org/github/UAlbertaALTLab/cree-intelligent-dictionary/jobs/709016169#L317-L319

What's the issue?

Each row **must** have the same number of tabs in it. In this file, each row must have 3 tabs.

**Comment by aarppe** [comment]
Ok. The cause of the error is clear to me - I was editing the file in emacs, so didn't explicitly focus on the number of tabs. As a note to ourselves, while I have no longing whatsoever for the old `*.layout` files, they made explicit the number of columns. Maybe we might eventually pad a row with more tabs in order to get the same number of columns - though this `*.layout.tsv` format should get replaced by the pane layout formatting before long.

When wanting to check whether an automated update has worked, how do I find the build? I was looking under the `Actions` tab, and there I saw green check-marks and short compilation times, so I thought it had passed. Based on your comment, I can assess the success of builds in [https://travis-ci.org/github/UAlbertaALTLab/cree-intelligent-dictionary/builds](https://travis-ci.org/github/UAlbertaALTLab/cree-intelligent-dictionary/builds), but I didn't see a link from the `Actions` to `Travis` - maybe just didn't look carefully enough.

Another question is did we intentionally go back to the multi-column presentation for the basic paradigm layouts? I didn't do that explicitly, but there were so many associated files in this latest update that we might have accidentally resurrected an older version. I can always easily recreate the single-column layouts for the basic verb paradigms.

**Comment by eddieantonio** [comment]
> When wanting to check whether an automated update has worked, how do I find the build?

Confusingly, we have _two_ different automated services: GitHub Actions and Travis-CI. The one that actaully updates itwêwina.dev is Travis-CI.

To check if a build is deployed, check this link: https://travis-ci.org/github/UAlbertaALTLab/cree-intelligent-dictionary/branches. Check the status of the **master** branch.

I also have a habit of clicking the [![Build Status](https://travis-ci.org/UAlbertaALTLab/cree-intelligent-dictionary.svg?branch=master)](https://travis-ci.org/UAlbertaALTLab/cree-intelligent-dictionary) badge on the main README.

This is how you can tell if an update happened: find the build of master, and if the "deploy" step exited succesfully (status 0), then the update is available on <https://itwewina.dev/>!

![Screen Recording 2020-07-17 at 10 34 36 AM 2020-07-17 10_37_14](https://user-images.githubusercontent.com/2294397/87810011-8d627900-c819-11ea-9437-fe2057ca4020.gif)

> I was looking under the `Actions` tab, and there I saw green check-marks and short compilation times, so I thought it had passed.

Yes. The GitHub Actions only do reformatting and _may_ handle FST updates.

> Another question is did we intentionally go back to the multi-column presentation for the basic paradigm layouts? I didn't do that explicitly, but there were so many associated files in this latest update that we might have accidentally resurrected an older version. I can always easily recreate the single-column layouts for the basic verb paradigms.

That is how I uploaded them? Maybe it was accidental? There was an awful lot of files updated! 😄

**Comment by aarppe** [comment]
Yes, the multi-column formatting was indeed accidental for the basic paradigm layouts. I've now fixed that, using the automated updating, and checking progress as instructed above - thanks for the instructions.
