### ISSUE TITLE
Create Cree visual image for selected components of itwêwina

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#479]
We need some (external) work on modifying the visual image of itwêwina to be more appropriate for Plains Cree (nêhiyawêwin).

- [x] favicon
- [x] logo (color, font)
- [x] ribbon/banner
- [ ] etc.

**Comment by aarppe** [comment]
Visual image specs received from Tasha Power during first week of October (2020).

**Comment by eddieantonio** [comment]
Now, _somebody_ just needs to impleemted it 😂

**Comment by eddieantonio** [comment]
@aarppe let me know how it looks! https://itwewina.dev/

**Comment by aarppe** [comment]
The footer looks great!

The one detail I'm wondering hould we change the color that indicates a link that has been visited to something else than pink(ish)? I find it unesthetic, and it's also harder to discern?

<img width="105" alt="image" src="https://user-images.githubusercontent.com/15003407/107098010-78f0c880-67cb-11eb-8c3a-3e9aa38b6e1a.png">

This would seem to be connected with the use of blue for the links (that then turns to pink, when visited), cf.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/15003407/107098173-d9800580-67cb-11eb-9f9b-1917001c26fa.png">

Here, I'm thinking the primary color of the links should be the same red as used in the footer (and if we use the turquoise color, then matching that shade of blue), i.e. the brownish red or the like we use in the headers on the About page? I.e.  <img width="288" alt="image" src="https://user-images.githubusercontent.com/15003407/107098601-d46f8600-67cc-11eb-87a3-cf46474f3391.png">

With the blue/turquoise scheme, the alternative pink is probably fine, but with the red/tan/hide scheme we'd like want some other alternative color, perhaps some darker orange, but this could be any standard choice for such a color alternation.

**Comment by eddieantonio** [comment]
@aarppe, how does it seem right now?

**Comment by aarppe** [comment]
The alternate color in the footer works great now. I'm still not sure if the blue/pink'ish for links in the main body is the bestest with the current overall dark red scheme, but than can be tweaked later.

**Comment by eddieantonio** [comment]
My opinion is that blue for links is kind of sacret. Links on the web are blue! But I can be convinced otherwise. That said, I'll mark this issue as closed for now. Feel free to open it again if there's something missing.

**Comment by aarppe** [comment]
Ok - this is what I understood. I can also be convinced otherwise, but we can revisit this later. Perhaps now what strikes my eye the most is not just the blue link color, that I generally liked and had no qualms before we implemented the current color scheme, but also the pink color for the explored links diverge from the general reddish theme.

It would be interesting to see how things would look overall, if we'd instead use the turquoise color scheme that Tasha originally provided. Alternatively, I'd be interested in seeing dark orange (similar to what is uses in the footer) for the accessed links, instead of pink.

**Comment by aarppe** [comment]
The essentials of this have been implemented long ago, so this can effectively be considered closed.

What we will eventually need to deal with is deciding how to adapt the visual image to other Indigenous languages on the Plains (e.g. Tsuut'ina, Woods Cree, [Nakoda, Arapaho]) and those of BC (Haida). E.g. might using the turquoise scheme be a good way to differentiate some Plains language?
