### ISSUE TITLE
Mark un/observed word forms

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#485]
Following further up on #455 and #484, mark unobserved word forms in grey, in contrast to full-black for observed word-forms (or something comparable).

**Comment by aarppe** [comment]
Conceptually, this is actually connected with #111, in that both in that issue and here we are indicating the plausibility of an inflected word form. In #111, the probability =0, here the probability is close to =1, with the intervening forms having a probability somewhere between 0 and 1.

**Comment by eddieantonio** [comment]
Fixed as of 8009e1a16e504ecb1ea275061e86d9069c7d11b8
