### ISSUE TITLE
Revise interpretation of *.layout files

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#487]
Pursuant #392 and #476, the preprocessing of the *.paradigm and *.layout files need to interpret `=` in Conjunct forms so that only the precise, explicitly mentioned preverb (_ê-_, or `PV/e+`) is matched. Otherwise, referring to the unmarked forms, i.e. with only _ê-_ will also match the forms with the tense preverbs, i.e. _ê-kî-_ and _ê-wî-_, which we need to rule out with a strict interpretation of the `=` marker in the layouts.

E.g. `=PV/e+*+V+AI+Cnj+1Sg` should only match `PV/+{{ lemma }}+V+AI+Cnj+1Sg` but
not `PV/+PV/ki+{{ lemma }}+V+AI+Cnj+1Sg` nor `PV/+PV/wi+{{ lemma }}+V+AI+Cnj+1Sg`.

EDIT: removed the `=` sign from the *.paradigm targets (which files we no longer really need, actually).

**Comment by aarppe** [comment]
@Madoshakalaka This would be for you.

**Comment by Madoshakalaka** [comment]
kk

**Comment by aarppe** [comment]
@Madoshakalaka If the layout updating works properly, then my understanding is that this should be done?

**Comment by eddieantonio** [comment]
Why not update this so that instead of `=PV/e+*+V+AI+Cnj+`, it is written as PV/+{{ lemma }}+V+AI+Cnj+1Sg?

**Comment by eddieantonio** [comment]
This interpretation of the spec has _not_ been coded. Note: this is the specification, of sorts: https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/master/docs/paradigm-layouts-and-metadata.md#word-form-templates

Of notes is this table:

> | Pattern           | Special character   | Example                        | Example lookup string              |
> |-------------------|---------------------|--------------------------------|------------------------------------|
> | Exact match       | `=`                 | `=N+I+D+PxX+Sg`                | mitêh+N+I+D+PxX+Sg                 |
> | Match anywhere    | (none)              | `Der/Dim+N+A+D+Px1Sg+Sg`       | nôhkomis+N+A+D+Px1Sg+Sg            |
> | Star substitute   | `*`                 | `PV/e+*+V+TA+Cnj+Prs+1Sg+2SgO` | PV/e+wâpamêw+V+TA+Cnj+Prs+1Sg+2SgO |

Note that "Exact match" and "star substitute" are mutually exclusive lookup types according to the (informal) specs we have. 

What should `=` mean?

**Comment by aarppe** [comment]
Currently, it seems that `=` means matching the exact set of features to the right of the lemma, so `=F1+F2` matches  `{{ lemma }}+F1+F2` but not `{{ lemma }}+F1+F2+F3` nor `F3+{{ lemma }}+F1+F2`. I don't know if this is really useful.

What could be of use, is that `=F1+*+F2` matches only an analysis string that starts with `F1+` immediately preceding a lemma and ends with `+F2` immediately following the lemma, e.g. `F1+{{ lemma }}+F2` but `F1+{{ lemma }}+F3+F2` nor `F1+{{ lemma }}+F2+F3`. But if we're not allowing partial matching, there is no use for `=`.

**Comment by aarppe** [comment]
This has been superseded by #497.
