### ISSUE TITLE
Searching with aya results in an error

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#490]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/15003407/86498858-01465100-bd45-11ea-9d50-431437bca4bd.png">

**Comment by Madoshakalaka** [comment]
I'll have a look

**Comment by Madoshakalaka** [comment]
I think my latest PR #493 should fix this by accident

**Comment by Madoshakalaka** [comment]
This is fixed
