### ISSUE TITLE
Simplify *.paradigm/*.layout files

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#497]
We've inherited a lot of technical debt from the NDS implementation of \*.layout/\*.paradigm files. Here are some ways we can simplify these files:

 - [x] get rid of the \*.layout files, prefering the \*.layout.csv files instead
 - [x] ~~interpret “smart-quotes” as if they're ASCII quotes~~ (see: #511)
 - [x] get rid of \*.paradigm files, as that can can be inferred from \*.layout.csv
 - [x] changes the extension from \*.layout.csv to \*.layout.tsv because that makes more sense!
---

> In principle and in practice, we wouldn't really want to use the old non-TSV layout files anymore, as all the information should be found in the *.layout.tsv files. On occasion, I've found working with the generated *.layout files useful in that the formatting becomes explicit, and you avoid certain spreadsheet application stupidities, such as the automatic conversion of plain quotes to "smart" (i.e. curly) quotes, if you don't watch out.
> 
> If our itwêwina code, reading the *.layout.tsv files, can interpret alike a plain and a curly quote, then that shouldn't be an issue anymore - and it shouldn't be an issue in the new pane layouts, once we get there.
> 
> Also, do note that the new *.layout.tsv (and *.layout) files do not really need the *.paradigm files, as the `*` (or `=`) can be unequivocally replaced by `{{ lemma }}` (and nothing else).

_Originally posted by @aarppe in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/pull/496_

**Comment by aarppe** [comment]
Yes to all. Some comments for the record:

1. Originally, the *.layout files were the primary specifications for the paradigm layout files, and the TSV versions were created to simplify their editing. In this respect, there is no actual need to use *.layout files, and switching only to *.layout.tsv makes perfect sense.
2. Curly quotes are an unintended consequence of using spreadsheet apps, so interpreting all forms of quotes resolves this.
3. Originally, it was thought that being able to refer to full linguistic analyses with underspecified references might be useful with multiple paradigms layouts for the same inflectional category, but that results in quite a deal of fragility. So simply specifying the forms in full in the *.layout.tsv files makes the system more robust. Also, if one could refer to basic paradigm layouts as subsets of the full paradigms (e.g. marking forms in full layouts that would occur also in the basic layouts, as long as the layout structure remains the same), then we would no longer have the issue of having to refer to some particular inflected form in more than one place - though this would probably work best with the multipane approach.
4. Use of CSV is simply a legacy feature, and TSV is more appropriate.

**Comment by aarppe** [comment]
@Madoshakalaka Revised paradigms in new FST branch to use the `${lemma}` notation instead of `=` or `*`. So, now the word form specifications in the *.layout.tsv files should be complete, and the *.paradigm (or *.layout) files should no longer be needed, but we need to ensure that these new TSV files are interpreted correctly.
