### ISSUE TITLE
Interpret smart quotes as ASCII quotes in layouts

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#511]
> 2. Curly quotes are an unintended consequence of using spreadsheet apps, so interpreting all forms of quotes resolves this.

_Originally posted by @aarppe in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/497#issuecomment-655172854_

**Comment by aarppe** [comment]
@eddieantonio Is this relevant any more?

**Comment by eddieantonio** [comment]
I don't believe so.
