### ISSUE TITLE
Support layouts for more than just nouns and verbs

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#513]
Currently, itwêwina crashes on startup if `CreeDictionary/res/layouts` has files [that cannot be parsed as a verb or noun layout file](https://travis-ci.org/github/UAlbertaALTLab/cree-intelligent-dictionary/jobs/709532745#L310-L313); however, we want to incorporate pronoun paradigms (see #164), so we'll need to come up with a way to match these to the correct pronoun!

Question for @aarppe:

_Where_ should the pronoun paradigms appear? For each pronoun definition, we'll list the entire paradigm? e.g., going to niya lists the paradigm with niya, kiya, wiya, etc.?

**Comment by eddieantonio** [comment]
@aarppe: nevermind, I read this from #164:

> these "paradigms" could be invoked from any of their constituent member pronouns, presenting how that pronoun is positioned in relation to the rest in the same subclass

👍

**Comment by aarppe** [comment]
Note that besides personal and demonstrative pronouns, we might eventually add interrogative pronouns, i.e. _kîkwây_, _kîkwâya_, _kîkwâyak_, _awîna_, _awîniki_, though what exactly belongs to that set needs to be sorted out. And besides pronouns, we might add a paradigm for interrogative particles, i.e. _tânisi_, _tânitê_, _tânispî_, _tânitahto_ etc.

**Comment by aarppe** [comment]
Initially implemented with static layouts in e.g. #769.
