### ISSUE TITLE
Debounce queries when typing in the search bar

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#529]
Right now, we send queries per every keystroke, even if the user continues to type more. Here's an idea:

We [debounce][] the input events, and send a search request when it appears the user has stopped typing. I also feel like this would make our Cypress tests run faster! 

[debounce]: https://levelup.gitconnected.com/debounce-in-javascript-improve-your-applications-performance-5b01855e086?gi=2679f37f3d2e#:~:text=The%20debounce%20function%20delays%20the,calls%20sent%20to%20your%20server.

**Comment by Madoshakalaka** [comment]
@dwhieb Thanks! I'm gonna yoink it :^)

**Comment by Madoshakalaka** [comment]
@eddieantonio 

I don't think I executed it good enough. I checked on production and typed into the search bar _wapamat_, it appears to me now all requests are just delayed, not debounced --- we now have 7 simultaneous requests for _wapamat_.

![Screenshot from 2020-09-01 15-23-58](https://user-images.githubusercontent.com/44753941/91907502-37ca1a80-ec67-11ea-8350-9cae5b119b2e.png)

I'll have a follow up on this, please keep this issue open
