### ISSUE TITLE
Reduce amount of queries made when searching (e.g., for English words)

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#531]
Here's me searching for "you" on my local copy of itwêwina:

![Screen Shot 2020-08-21 at 4 13 13 PM](https://user-images.githubusercontent.com/2294397/90939610-6de6df00-e3c9-11ea-96a7-e16a1cff0c10.png)

I'm especially concerned about this:

> **459 queries** including **456 similar** and **314 duplicates**

This can and should be massively improved!

 - [ ] eliminate duplicate queries
 - [ ] reduce amount of similar querires

---

Steps to reproduce that image:

 - run the server with `DEBUG=True`
 - go to <https://localhost:8000/?q=you>
 - Open the debug toolbar (on the right side) and click on "SQL"

You may also want to turn on profiling.

**Comment by aarppe** [comment]
@eddieantonio @andrewdotn How current is this issue still?

**Comment by eddieantonio** [comment]
I would think so! It's 7 queries now, which is much more reasonable:

![Django Debug Toolbar display of all queries run for the search of “you”](https://user-images.githubusercontent.com/2294397/127522604-9f1f1489-1f26-4f2e-a619-f02bb79056b7.png)

I think this is fixed!
