### ISSUE TITLE
Tweaking the linguistic analysis pop-up

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#549]
Based on previous proposals and current implementations, I'd tweak the linguistic analysis pop-up as follows:

<img width="245" alt="image" src="https://user-images.githubusercontent.com/15003407/95300906-17c8e080-083d-11eb-86f8-f10b78f261dd.png">

1. Show stem prominently as a bolded header (similar to how the lemma was shown)

2. Show in the linguistic analysis only those prefixal features which are not already otherwise shown, i.e. leave out the prefixes that are shown quite prominently.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/15003407/95300935-244d3900-083d-11eb-814f-43ae433b5a63.png">

We'd yet need to decide whether we'd show the reduplicative elements similar to preverbs, and where to show Initial Change (which would be quite rare, generally).

**Comment by eddieantonio** [comment]
@aarppe do you want to move the preverbs _below_ the definition?
