### ISSUE TITLE
Issue with the speech samples for pahkwêsikan

### ISSUE THREAD

**Issue by atticusha** [UAlbertaALTLab/cree-intelligent-dictionary#553]
https://sapir.artsrn.ualberta.ca/cree-dictionary/word/pahkw%C3%AAsikan/

Regardless of who you choose as speaker, it's Jerry Roasting

**Comment by eddieantonio** [comment]
Could you please specify what browser/OS you're using? I cannot replicate this on Chome 85 on macOS.

**Comment by atticusha** [comment]
yeah it's not happening anymore to me either. I was on Chrome 86 on macOS 15.5
