### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#559]
Travis-CI is getting _really_ slow, and the integration has broken to show statuses on our PRs. Perhaps we should attempt running the tests on ~~Travis-CI~~ GitHub Actions?

**Comment by dwhieb** [comment]
Do you mean running tests on GitHub Actions instead?

I use GH Actions for all my projects now. Such a good user experience, great documentation, easy to set up.

**Comment by eddieantonio** [comment]
Yes! Haha, messed up the comment. I think migrating the tests may be worthwhile...

**Comment by eddieantonio** [comment]
Update: I migrated the unit tests, but the e2e tests with Cypress are proving to be a challenge. Particularly in spinning up a development server (Python + Django) and using the `wait-on` command to wait for the server to be up. I'm not sure what's wrong, but I deleted it in 58406025cc378298978365c2adb18ad4cffd0b8e

**Comment by eddieantonio** [comment]
It is done! The workflow script is... complicated. But it works!
