### ISSUE TITLE
Bug: Affix searcher returns both English and Cree results

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#572]
I realized this todo while adding optional affix search. Initially I don't think this causes any difference. But I guess it does produces undesired ranking of the entries. Because EnglishResults and CreeResults are ranked differently. Here EnglishResults matched by affix search are wrongly marked as CreeResults.

_Originally posted by @Madoshakalaka in https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/pull/571#discussion_r530609079_

**Comment by Madoshakalaka** [comment]
Thanks you!

**Comment by eddieantonio** [comment]
Fixed since at least 0a05a74a052e3f39cd4b5e5eb281578086963c75
