### ISSUE TITLE
Better layout specification for paradigms

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#581]
Following up on #167, we should first implement a more precise specification for paradigm layouts, which would allow us to address user feedback (#567 and #568).

Row and column labels are marked with `_` and `|`, respectively (in comparison to `<` and `^`). Both labels, but in particular the column labels can have a hierarchy, which is used to organize the panes according to available space. One can also use the column labels to refer to the panes. What is not indicated as a label is a reference to an FST-generated form. In this format, the forms are specified in full, indicating the lemma slot with `{{lemma}}` - this means that one would not necessarily need a separate specification/file for the paradigms and their generation.

Column labels are indicated by a prefixed `|`, and row labels with a prefixed `_`. Cell content to be generated by the FST is not prefixed. These row and column labels can be relabeled according to specifications in `crk.altlabel.tsv` - this should allow for relabeling multiple label sequences.

```
             | AI | Prs | Ind
_ Sg _ 1Sg   {{lemma}}+V+AI+Ind+1Sg
_ Sg _ 2Sg   {{lemma}}+V+AI+Ind+2Sg
_ Sg _ 3Sg   {{lemma}}+V+AI+Ind+3Sg
_ Pl _ 1Pl   {{lemma}}+V+AI+Ind+1Pl
_ Pl _ 12Pl  {{lemma}}+V+AI+Ind+12Pl 
_ Pl _ 2Pl   {{lemma}}+V+AI+Ind+2Pl
_ Pl _ 3Pl   {{lemma}}+V+AI+Ind+3Pl
_  _ 4Sg/Pl  {{lemma}}+V+AI+Ind+4Sg/Pl
_  _ X       {{lemma}}+V+AI+Ind+X

             | AI | Prs | Cnj
_ Sg _ 1Sg   PV/e+{{lemma}}+V+AI+Cnj+1Sg
_ Sg _ 2Sg   PV/e+{{lemma}}+V+AI+Cnj+2Sg
_ Sg _ 3Sg   PV/e+{{lemma}}+V+AI+Cnj+3Sg
_ Pl _ 1Pl   PV/e+{{lemma}}+V+AI+Cnj+1Pl
_ Pl _ 12Pl  PV/e+{{lemma}}+V+AI+Cnj+12Pl 
_ Pl _ 2Pl   PV/e+{{lemma}}+V+AI+Cnj+2Pl
_ Pl _ 3Pl   PV/e+{{lemma}}+V+AI+Cnj+3Pl
_  _ 4Sg/Pl  PV/e+{{lemma}}+V+AI+Cnj+4Sg/Pl
_  _ X       PV/e+{{lemma}}+V+AI+Cnj+X
```
The row and column labels will also allow for grouping the panes according to available space, to be implemented through a later issue.

This issue also requires the conversion of current layout specifications to this new format.

**Comment by aarppe** [comment]
First stab at what the above could look like visually:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/15003407/102448401-4a3a4b00-3fef-11eb-8f94-0948f4ca1d75.png">

What I am dithering about is how much of the above should be specified explicitly, e.g. giving the horizontal top-level labels only for the rows we want to see them, or identifying coding-wise, e.g. recognizing the repetition of the common horizontal top-level labels, and showing them only once.

**Comment by aarppe** [comment]
We're making use of the hierarchical row labeling in the VTA layouts. If that works there, I'll implement this for the other verb layouts as well.

Eventually, it would be nice to implement hierarchial labeling for column labels as well, but that would require more intelligence in determinining how that is shown, so that the entire hierarchy is not shown by default for every pane, but only to the extent to obviously disambiguate panes.

**Comment by eddieantonio** [comment]
This has been completed for full-sized layouts as of #818
