### ISSUE TITLE
Upgrade to at least Python version 3.8

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#590]
Apart from the Walrus operator, there are some nice new features. We could also ditch `attrs` and use `dataclasses` instead!

**Comment by eddieantonio** [comment]
Hey @nienna73 @andrewdotn please send me a thumbs-up reaction if I can try updating the Python version for this project! OR! Reply to this message telling me why updating the Python version is a bad idea.

**Comment by andrewdotn** [comment]
Please do; I’m not sure if we’d run into them, but [3.8 has issues on Big Sur](https://blog.python.org/2020/12/python-387-is-now-available.html) that are already fixed in 3.9.

**Comment by eddieantonio** [comment]
That's very useful to know! Thanks, @andrewdotn!
