### ISSUE TITLE
Tweak <meta> tags to give a nice preview on Facebook/Twitter

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#625]
@aarppe, could you please post a screenshot of what the links look like on Facebook now?

(TODO: Eddie will edit this comment to show what I THINK the social media preview should look like)

See: https://heymeta.com/

**Comment by aarppe** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/15003407/105283967-b9ffa080-5b6e-11eb-810a-8b642bdf6848.png">

**Comment by eddieantonio** [comment]
@aarppe what _should_ this say?

What should be the main title?

Here's what I have so far:

![itwêwina: Plains Cree Dictionary](https://user-images.githubusercontent.com/2294397/107710239-d2516f80-6c83-11eb-8274-fd5a44798d26.png)

Title: **itwêwina: the Plains Cree dictionary**
Description: **A smart online dictionary of Plains Cree (Y-Dialect) | nêhiyawi-masinahikan kâ-iyinîsit**

(See also the discussion in Slack).
