### ISSUE TITLE
Verify that loading the morpheme rankings is... doing it... right

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#649]
https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/034ae2658579fbe141522813cfe615b4184df359/CreeDictionary/API/apps.py#L89-L93

There's a TODO comment about rows? And I don't think it normatizes the text for things like <ý>.

**Comment by aarppe** [comment]
No longer relevant due to #784.
