### ISSUE TITLE
Provide results for multi-word/key (English) searches

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#674]
Feedback via itwêwina feedback form from `███████████████
@gmail.com`:

> translate compound words such as _thank you_ without having to search just the first word. 

> Love the sight and find it very useful

This would appear to be directly relevant in the current work on improving search and relevance.

**Comment by eddieantonio** [comment]
This definitely falls within the view of "better English search" @andrewdotn! Possibly related to #524?

**Comment by aarppe** [comment]
Closed with #785.
