### ISSUE TITLE
searches for terms with many results are slow to load

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/cree-intelligent-dictionary#679]
Searching for terms like "at" or "be", which return many results, takes a good deal longer before results are displayed than other terms with fewer results.

I *think* this is because of how long the search takes to run on the server, not because of how long it takes to render, but I haven't investigated this yet, and it might be a bit of both.

There are multiple ways we could address this, but maybe we could take advantage of pagination and render each page of results as they come in, so that the user gets the first 10-20 results immediately. Then all our searches would display initial results in approximately the same amount of time, regardless of how many results there are.

**Comment by eddieantonio** [comment]
👍🏼 for pagination!

**Comment by andrewdotn** [comment]
We need to gather all the results on the server before we sort any of them for ranking purposes, so unfortunately pagination won’t do much to speed it up. That said, the total number of results returned is something to look at when improving the general search quality.

**Comment by eddieantonio** [comment]
@dwhieb @andrewdotn how are we feeling about the peformance of these results now?

Anecdotally, the performance for these kind of queries feel better but at the same time, we are returning WAY more results now.

**Comment by dwhieb** [comment]
SO much faster! I'm satisfied with both the performance and the number of results. I propose this issue be closed.
