### ISSUE TITLE
Wrong speaker code for many MD recordings

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#688]
For a number of dictionary entries, the speaker codes do not match, e.g.:

https://itwewina.altlab.app/word/otatosk%C3%AAw/

**Comment by aarppe** [comment]
I checked with Atticus yesterday on the annotations, and according to him the students had been given clear instructions on how to code the speaker/annotation tiers. But what might gone fuzzier is how the recording session directories might have been named. Anyhow, if there is remaining doubt about various naming conventions, consulting Atticus may be worthwhile.

**Comment by eddieantonio** [comment]
@aarppe Trust me. There is no way Atticus could help us with the sheer "creativity" to the filenames. I think we covered them all, or nearly all of them. Please see: https://github.com/UAlbertaALTLab/recording-validation-interface/blob/599dbd2fbbb1d83bbc125115dbf1e56ea90875e5/librecval/extract_phrases.py#L500-L535

**Comment by aarppe** [comment]
So much for (undergraduate) students following instructions. But for any later similar project, we need to be dogmatically and compliance-inducingly persistent about such naming conventions.

**Comment by aarppe** [comment]
The speaker codes come from the [Speech DB](https://github.com/UAlbertaALTLab/recording-validation-interface), and it is there that this is being addressed, for eventual resolution.
