### ISSUE TITLE
Temporarily remove on the coding side obvious parenthetical expressions from phrase generation

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#709]
While a linguistic solution is being implemented, we should implement a temporary solution on the coding side

1. In CW, this would mean excluding all parenthetical expressions, i.e. anything in `(...)` or `[...]` except the following:
- [ ] `(it/him)`
- [ ] `(it)`
- [ ] `(s.o. as)`
- [ ] `(s.t.)`
- [ ] `(s.t. as)`

2. In MD, excluding the tail ends of the English definitions which start with the following (capitalized) words:
- [ ] `Also`
- [ ] `Or`
- [ ] `Animate`
- [ ] `Inanimate`

**Comment by aarppe** [comment]
@andrewdotn Let's start with this while @dwhieb works on the more lasting solution. When we do this, we can run the phrase generation again (though I'll need to tweak the plural noun -s generation a bit).

**Comment by andrewdotn** [comment]
Yup, this is now at the top of my list for phrase translation, with the caveat that I’m not currently planning to work on that this week.

**Comment by andrewdotn** [comment]
Fixed by #744.
