### ISSUE TITLE
Show a formatted table version of feature relabelings as interim glossary

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#719]
As in interim solution for #405, first show a nicely formatted version of https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/master/CreeDictionary/res/crk.altlabel.tsv. This could possibly benefit from the organization of the labels into related sets, instead of the current alphabetical ordering.

**Comment by eddieantonio** [comment]
Not sure this would be appropriate as `crk.altlabel.tsv` does not correspond to the things that needed to be placed in the legend, such as Arok's abbreviations.
