### ISSUE TITLE
Access to the actual dictionary data.

### ISSUE THREAD

**Issue by jenstroeger** [UAlbertaALTLab/cree-intelligent-dictionary#730]
Hi,

based on [this comment](https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/master/docs/developers-guide.md#full-database) it sounds like the actual Cree dictionary information (the `crkeng.xml` file) is proprietary information? I’m looking for the owner of that file regarding a project I’m working on. Who should I reach out to?

Thanks!

**Comment by aarppe** [comment]
@jenstroeger Send an email to myself, i.e. arppe@ualberta.ca, and we can follow up there.

**Comment by jenstroeger** [comment]
Thank you @aarppe, I just sent you the email. Closing this issue.
