### ISSUE TITLE
Extend relabeling choice to FST analysis

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#742]
Expanding from #729, when choosing a relabeling mode, apply that to the presentation of the results of the FST linguistic analysis tags as well.

For instance: _nimaskomak_ -> **maskwa+N+A+Px1Sg+Pl** 
- community/Plain English: -> **naming word + like: asikan, iyiniw, maskwa + my + many**
- linguistic mode: **Noun + Animate + Possessor: 1st person singular + Plural**
- nêhiyawêwin mode: **wîhyowin-itwêwin + tâpiskôc: asikan, iyiniw, maskwa + niya + mihcêt**

**Comment by eddieantonio** [comment]
Part of #708
