### ISSUE TITLE
Revise interpretation of future tags

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#750]
Based on further details from Arok, the grammatical preverb _wî-_ should be interpreted as _be going to_, and the preverb _ka-_ as _will_.

Thus, the mappings need to be changed as follows (`Int+` will no longer be needed/used):
- [ ] `PV/wi+` -> `Fut+`
- [ ] `PV/ka+` -> `Def+`

The analyzing and generating transcriptors have already been modified accordingly, but the test cases would need fixing.

**Comment by andrewdotn** [comment]
Fixed by #758.
