### ISSUE TITLE
For II verbs, the general plain English relabeling of +3Sg in the linguistic analysis as s/he is not entirely appropriate. Solution: add it to the subjects?

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#791]
>  1. For II verbs, the general plain English relabeling of +3Sg in the linguistic analysis as s/he is not entirely appropriate. Solution: add `it` to the subjects?

_Original posted by @aarppe in #502_

**Comment by aarppe** [comment]
Implemented in conjunction with #753.
