### ISSUE TITLE
CVD or something else in search not working

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#807]
Try: https://itwewina.altlab.app/search?q=navajo%20verbose%3Atrue - cf. below:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/15003407/118750635-04dbad00-b81d-11eb-8859-5a1d4249fe12.png">

**Comment by andrewdotn** [comment]
The `definitions.kv` file wasn’t automatically moved when we released an updated directory structure yesterday, so CVD wasn’t working.

Fixed by running:

    altlab-itw:/opt/docker-compose/itwewina/cree-intelligent-dictionary$ sudo mv CreeDictionary/res/vector_models/definitions.kv src/CreeDictionary/res/vector_models/
