### ISSUE TITLE
Link forwarding / accessing itwêwina via old NDS link

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#808]
Feedback #32 (May 17, 2021)

**What is the website address (URL) of the page where you found the problem?**
* https://altlab.ualberta.ca/itwewina/crk/eng/
**Tell us what you think was SUPPOSED to happen.**
* I was expecting to go to the regular home page.
**Tell us what ACTUALLY happened instead of what you expected.**
* The link to the home page given above appears to be broken (leads to a 404 page). Accessing the dictionary through googling now leads to what looks like a much older version of the dictionary (e.g. the option to add long vowels by clicking is gone now). I'm not sure what's happened, but this seems like a reversion, not an update.

**Comment by andrewdotn** [comment]
In Wordpress, I have added a redirect so that https://altlab.ualberta.ca/itwewina/crk/eng/ now goes to <https://altlab.ualberta.ca/itwewina/>, the page that describe itwêwina and has a “Yes! Take me to itwewina!” button

**Comment by aarppe** [comment]
This seems to be working now.
