### ISSUE TITLE
Temporary fix concerning source coding for wâpamêw

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#867]
For the entry for _wâpamêw_, below:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/15003407/122485342-de33a200-cf93-11eb-88c3-c5cafe07ae04.png">

We should for now remove the **[AE]** coding from the first definition (leaving that sourced to only **[MD]**).

In actual fact, we will eventually want to treat the **[AE]** and **[MD]** definitions as being effectively the same, but for now I'd simply present three distinct meanings and sources.

**Comment by aarppe** [comment]
@andrewdotn Here's the item that would benefit from immediate fixing.

**Comment by andrewdotn** [comment]
This was fixed as part of the deploy for #874.
