### ISSUE TITLE
[Question]: remove dynamic/static layout directories?

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#870]
Currently, the `crkeng` layouts [are organized into two directories](https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/tree/3ca62a0c68ad444368e646fee2acedaa3b721db2/src/CreeDictionary/res/layouts):
 
 - `layouts/dynamic` — contains layouts with `${lemma}` placeholders
 - `layouts/static` — contains layouts that are displayed verbatim

Recently (#868), we removed the distinction in the code for these two different types of paradigms. They're instantiated in the same way.

**Should we also remove the distinction in the directory structure?** This would mean all paradigm layouts, be they "static" or "dynamic" will be in the `layouts` directory.

@aarppe, please advise.

**Comment by dwhieb** [comment]
I have no strong opinion on this either way. Whichever you like best is good by me!

**Comment by aarppe** [comment]
Neither do I have a strong opinion here, though hot distinguishing the two would appear a simplification. But on the other hand, the two types of paradigms are distinct in their content, so there could be a point in keeping them explicitly separate.
