### ISSUE TITLE
Other phrases ESPT does not recognize (properly)

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#878]
As a follow-up to #875, here are more dysfunctional cases:
* we will speak to you and us
https://itwewina.altlab.app/search?q=we%20will%20speak%20to%20you%20and%20us%20Cree%20espt%3A1
<-- FST phrase analysis: speak to  +V+TA+Def+1Pl+21PlO
--> it seems to be that the first person exclusive actor 'you and we' and goal 'you and us' are analyzed correctly, but not mapped into the Cree features properly.

These imperatives seem not to work due to something wrong with the FST phrase analysis --> AA to resolve
* let you and us sleep now
https://itwewina.altlab.app/search?q=let%20you%20and%20us%20sleep%20now%20espt%3A1
* let us eat later
https://itwewina.altlab.app/search?q=let%20us%20eat%20later%20espt%3A1

**Comment by eddieantonio** [comment]
@aarppe  Can you classify _why_ it's a dysfunctional case? It would be much more helpful to know what could have gone wrong and where it plausibly went wrong. e.g., is it the phrase translation FST or the Python code to implement it in the search? Also, why not add it to #875 if these cases are unclassified?

**Comment by aarppe** [comment]
Duplicate of #875, so examples moved there, and this issue thus closed.
