### ISSUE TITLE
Switch to exact orthographical matching when fetching recordings

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#880]
In the speech DB validation interface, I've gone through some well-know minimal pairs such as sakahikan 'nail' vs. sâkahikan 'lake', kotiskawêw 'try on' vs. kotiskâwêw 'gallop', and nipiy 'water' vs. nîpiy 'leaf', and made sure that the examined recordings (classified as either 'good', or not 'wrong.word') match the transcriptions. There are sure to be some other cases as well.

Thus, we could start considering changing the matching of transcriptions when fetching recordings to an exact orthographical match, instead of the current looser match. At the very least, we'd want to have this in place for the aforementioned minimal pairs, as those are what instructors and students will look up.

**Comment by eddieantonio** [comment]
Requires #UAlbertaALTLab/recording-validation-interface#103.

**Comment by nienna73** [comment]
I think this was resolved with #910
