### ISSUE TITLE
English search takes forever again and returns way too many results

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#891]
Try searching for "it happened" (I won't provide a handy link because I fear some crawler will visit it and unintentionally take down the site).

It about 7 seconds for the request to be ready, and additional time to actually download the page. Compare this to, say, "[love](https://itwewina.altlab.app/search?q=love)", take takes less than a second for the response headers to be sent and the body to download on my home internet connection. Luckily, after the wait, "ispayin" (what I expected to be the best result) is the first result. So at least the search quality is good!

My hypothesis: the search results are just gathering ALL target language definitions (i.e, English) that contain "it" and adding it the result. Ctrl+F in Chrome tells me that "it" can be found 6052 times on the page 🙃

**Comment by aarppe** [comment]
My original proposal for the logic with phrase translation was that, 1) if multiple words could be analyzed as either a noun or verb phrase; 2) then the function words should get analyzed as English features (here: _it_) that are converted into Cree ones in the autotranslation (here: `PV/ki+`); and 3) the actual search should be undertaken with only the remaining lexical elements (here: _happened_ -> _happens_). A further consideration, not yet implemented, would be to restrict the results of the (lexical) search to verbs or nouns based on the phrase analysis, if not actually even more narrowly to the individual transitivity/animacy classes that the phrase analysis provides (II, AI, TI, TA; NB. this would not really work for nouns).

For _it happened_, the English phrase analyzer works properly, cf. https://itwewina.altlab.app/admin/fst-tool?text=it+happened&Analyze=Submit+Query - but the search in itwêwina still leaves 'it' among the search words - which probably, and apparently is not good (cf. the verbose results).

**Comment by aarppe** [comment]
As a further comment for _it_, similar to being interpreted as a function word / feature (and not used in the actual search as a lexical element) when occurring as an existential subject, when used as the object for a verb, this should result in the phrase being analyzed as VTI (in contrast to AI and TA), cf. https://itwewina.altlab.app/admin/fst-tool?text=she+eats+it&Analyze=Submit+Query, where the pronoun should neither be part of the search. However, for 'she eats it', _it_ still appears to hang around in the search, slowing it down and not yielding the intended result.

**Comment by aarppe** [comment]
And finally, now having it as an object results in the following error/warning:  `"espt_analysis_error": "UnknownTagError('+0SgO')"` (which didn't appear to be the case just a while ago).

**Comment by andrewdotn** [comment]
We can drop `+0SgO` fairly easily, but I think there are a few issues with the `+0Sg` case.

  - The phrase analyzer FST analyzes `it happened` as `+V+II+0Sg` but the dictionary FST doesn’t generate anything for `ispayin+V+II+Ind+0Sg`. Should `+0Sg` in an English phrase map to `+3Sg` in a Cree wordform?

  - The phrase analyzer FST turns `it was night` into `is night +V+II+Prt+0Sg`. In addition to the above concerns about `+0Sg`, the phrase analyzer should probably drop the `is` word too.

**Comment by aarppe** [comment]
Yes, `+0Sg` from the English phrase analysis should be converted into `+3Sg` in Cree word form generation (which only applies to II verbs, at that is the only way to get that analysis).

As for dropping `is` from the FST analysis, it is a result of a legitimate analysis, indicating that we're looking for a predicative/attributive verb. So if we'd want to drop it, that should happen in the postprocessing of the analysis.

As for the object/goal analysis of it, the `+0SgO` tag is generated for the sake of completeness, but since TI verbs implicitly contain the inanimate object/goal referred to by that tag, it isn't needed for the generation of crk wordforms.

**Comment by aarppe** [comment]
Fixed `it` as inanimate subject, so that verbs phrases such as _it happened_ gets properly analyzed resulting in quick results, cf.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/15003407/124884999-0d847000-df90-11eb-8e79-505905023f3f.png">

**Comment by aarppe** [comment]
However, deleting `+0SgO` in `espt_crk.py` by adding the line `("+0SgO", "", 3)`, did not appear to entirely work. The search is quick and the object _it_ is discarded, but the phrase is not interpreted as verb phrase.

**Comment by aarppe** [comment]
So, it would seem to me that mostly this issue would be closed to the extent that I had thought ESPT would work in search. What remains to be sorted out at some later point is what to do when ESPT doesn't work, and we might - perhaps, but not necessarily - want to exclude some really frequent function words, such as _it_, and perhaps also _is_ (with the latter seeming to slow down the search substantially).

**Comment by aarppe** [comment]
The remaining open issue is covered in #967.
