### ISSUE TITLE
maci- doesn't show recordings on the search result page

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#922]
For whatever reason, _maci-_ doesn't show recording on the search result page, cf.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/15003407/126557447-7df1cc6a-47a6-4cd4-ac5c-c7a84587a645.png">

... even though these are shown on the details page, cf.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/15003407/126557593-346fc7bc-83c4-4887-8d71-984ad40e9d9f.png">

**Comment by eddieantonio** [comment]
@aarppe could you please link to the segment in the speech-db?

The new API is a lot more strict when choosing a recording. It's possible any recording of "maci-" is no longer matching because, e.g., it was recording of "mâci-".

**Comment by aarppe** [comment]
Here: https://speech-db.altlab.app/segment/9977

You do get the results, but only on the page with further information, though not on the initial search page.

As for _mâci-_ (start), there are recordings for that as well, but those had been all classified as bad - I turned the single least bad one into good so that it could be shown.

**Comment by eddieantonio** [comment]
@aarppe okay! 
Searching for _just_ maci- works: https://speech-db.altlab.app/api/bulk_search?q=maci-

Search for maci- and 168 of its friends... does not: UAlbertaALTLab/recording-validation-interface#239

Looks like the error can be addressed in multiple different ways:

 - [ ] figure out what exactly is causing the 502 Bad Gateway error and resolve that
 - [ ] put a limit on how many recordings itwêwina will look for -- something like 50
 - [ ] put a limit on how many search results to display at once
 - [ ] paginate search results#920 
 
One or all of these are approaches to resolve this issue.

**Comment by aarppe** [comment]
I'll just note now that I don't have a strong opinion about the above options. My initial inclination would be not to paginate the search results, but that may be primarily due to have gotten used to the current presentation scheme.

**Comment by eddieantonio** [comment]
@aarppe try it now! (you may need to <kbd>Shift</kbd>+Refresh): https://itwewina.altlab.app/search?q=maci-
