### ISSUE TITLE
Need Cree altlab.tsv relabelling for awîna

### ISSUE THREAD

**Issue by andrewdotn** [UAlbertaALTLab/cree-intelligent-dictionary#935]
One of the forms of awîna has analysis awîna+Pron+Interr+A+Sg. As there is no relabelling that includes Interr, that distinction is missing from the linguistic popup.

<img width="320" alt="Screen Shot 2021-07-29 at 4 08 04 PM" src="https://user-images.githubusercontent.com/178162/127572016-2fd16281-df08-4367-b4a7-8686138c5624.png">

**Comment by aarppe** [comment]
Fixed with: https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/commit/11ad7f95452e100890df91a2f07fda64909281dd
