### ISSUE TITLE
incorrect forms shown in paradigms for NDI entries

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/cree-intelligent-dictionary#948]
From Arok:

itwêwina correctly recognizes `ocihcîyiwa` or `ocihciyiwa` as a form of `micihciy` or `nicihciy`, and displays those entries in the search results.

However, the 3pl.poss and 4.poss forms of the paradigms for those entries are incorrect. Right now, the paradigms show the following (incorrect forms in bold):

Label         | Singular      | Plural         | Locative
------------- | ------------- | -------------- | --------
Possessor: 3p | ocihcîwâw     | ocihcîwâwa     | ocihcîwâhk
Possessor: 4  | **ocihcîwâw** | **ocihcîwâwa** | ocihcîyihk

The paradigm should look like this instead:

Label         | Singular      | Plural         | Locative
------------- | ------------- | -------------- | --------
Possessor: 3p | ocihcîwâw     | ocihcîwâwa     | ocihcîwâhk
Possessor: 4  | **ocihcîyiw** | **ocihcîyiwa** | ocihcîyihk

This seems to be an issue with NDI paradigms specifically, not with other paradigm types.

Other example issues:

* NDI-1 _ospitoniyiw(a)_ "(an)other(s) arm(s)" and _wahkwaniyiw(a)_ "(an)other(s) heel(s)" > recognized in search but incorrectly displayed in the Poss3p forms (i.e. _ospitoniwâw(a)_ and _wahkwaniwâw(a)_)
* NDI-2 _oskotâkâyiw(a)_ "(an)other(s) coat(s)" and _wanawâyiw(a)_ "(an)other(s) cheek(s)" > recognized in search but incorrectly displayed in the Poss3p forms (i.e. _oskotâkâwâw(a)_ and _wanawâwâw(a)_)
* NDI-3 _oskîsikoyiw(a)_ "(an)other(s) eye(s)" and _wayakaskoyiw(a)_ "(an)other(s) palate(s)" > recognized in search but incorrectly displayed in the Poss3p forms (i.e. _oskîsikowâw(a)_ and _wayakaskowâw(a)_)
* NDI-4 _wîkiyiw(a)_ "(an)other(s) home(s)" > recognized in search but incorrectly displayed in the Poss3p forms (i.e. _wîkiwâw(a)_)

**Comment by dwhieb** [comment]
The FST recognizes the forms correctly:

* ocihcîyiw: nicihciy+N+I+D+Px4Sg/Pl+Sg
* ocihcîyiwa: nicihciy+N+I+D+Px4Sg/Pl+Pl

So this looks like it's an issue with the paradigm layouts.

**Comment by aarppe** [comment]
Yes, this was a matter of the NDI/NID full paradigm layout having an incorrect specification for +Px4Sg/Pl singular and plural forms, which has now been fixed and released, with https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/commit/25032f4b853fbfe97543a60eb81c1634c8162bd1#diff-695534b368abf7fde44f8a30ada0db14f38a7267a97296319487cd7cb81d76e6
