### ISSUE TITLE
Presentation of linguistic analysis corresponding to search string and lemma

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#99]
"Somewhere" (potentially hidden at first), one should receive the linguistic analysis of the search string in relation to the lemma (having applied spell-relaxation).

At the minimum, the linguistic features would be written-out versions of the analysis tags, i.e. (1) below is represented as (2).

1. FST linguistic analysis:
niwî-mowâw ← mowêw+V+TA+Ind+Fut+Int+1Sg+3SgO

2. Basic relabeling using lemma:
niwî-mowâw ← mowêw- +  Verb +  Transitive Animate +  Independent + Future +  Intentional +  Actor: 1st Person Singular +  Goal: 3rd Person Singular

3. Basic relabeling using stem:
niwî-mowâw ← √mow- +  Verb +  Transitive Animate +  Independent + Future +  Intentional +  Actor: 1st Person Singular +  Goal: 3rd Person Singular

4. Advanced relabeling using plain English:
niwî-mowâw ← Action word - like: wâpamew + ni/ki-form + Someone wants something to happen later + I -> him/her/it

5. Advanced relabeling using nêhiyawêwin:
niwî-mowâw ← ispayin-itwêwin - tâpiskoc: wâpamew + ni/ki-itwêwin + awiyak pakosêyimow kâ-wî-ihkik nîkânihk  + niya -> wiya

"Somewhere", one should present the stem for nouns and verbs (as the Wolvengrey dictionary does), as that is considered useful information, and some consider it an alternative to the lemma.

Options 4-5 are for later consideration, as that will require the creation of new relabeling schemes.

Currently, the relabelings are specified in the file: itwewina.relabel - as a potential follow-up issue this file would benefit from some documentation and additional explicit structure (also covering potential additional pop-up information concerning features, such as is currently available for preverbs: PV/kakwê -> Preverb: kakwê- -> 'try, intend, etc.'.

**Comment by aarppe** [comment]
This matches the following user story:

"As a Cree language learner, I want to see the linguistic breakdown of my Cree search query."

**Comment by aarppe** [comment]
In the first instance we can focus on option 2 above, which can be implemented using the itwewina.relabel file.

On the longer term this requires a simple table with the rendering of the features in various forms, as discussed above, which is an issue of its own.

**Comment by aarppe** [comment]
The `improvement` component here means implementing the optional presentation of the linguistic breakdown features with plain English or plain nêhiyawêwin.

**Comment by aarppe** [comment]
An online version of the above `crk.altlabel` file now stored in the Norwegian SVN can be found with the following link:

`https://gtsvn.uit.no/langtech/trunk/langs/crk/inc/paradigms/crk.altlabel`

This five columns in this file should pretty much map with the alternatives 1-5 at head of this issue. However, in some cases, one can come up with a meaningful label for each category, e.g. FST features, but in other cases (inflectional classes and in particular paradigm column/labels) the alternatives only work for perhaps 3-4 of the cases (categories 2-4, or 3-5 above).

**Comment by aarppe** [comment]
This is an extension of #209.

**Comment by eddieantonio** [comment]
Closing this in favour of #209.
